# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Payment.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QFrame,
    QGroupBox, QLabel, QLineEdit, QListView,
    QPushButton, QRadioButton, QSizePolicy, QWidget)

class Ui_payment(object):
    def setupUi(self, payment):
        if not payment.objectName():
            payment.setObjectName(u"payment")
        payment.resize(591, 321)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(170, 85, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush4)
        brush5 = QBrush(QColor(120, 131, 170, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush7 = QBrush(QColor(85, 0, 255, 128))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        brush8 = QBrush(QColor(255, 85, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        brush9 = QBrush(QColor(169, 77, 193, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        brush10 = QBrush(QColor(64, 14, 89, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        payment.setPalette(palette)
        self.frame = QFrame(payment)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(250, 10, 341, 311))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.icost = QLineEdit(self.frame)
        self.icost.setObjectName(u"icost")
        self.icost.setGeometry(QRect(20, 30, 61, 22))
        self.plus = QLabel(self.frame)
        self.plus.setObjectName(u"plus")
        self.plus.setGeometry(QRect(90, 30, 51, 20))
        self.taxes = QLineEdit(self.frame)
        self.taxes.setObjectName(u"taxes")
        self.taxes.setGeometry(QRect(110, 30, 61, 22))
        self.icostlabel = QLabel(self.frame)
        self.icostlabel.setObjectName(u"icostlabel")
        self.icostlabel.setGeometry(QRect(30, 10, 61, 16))
        self.icostlabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.taxeslabel = QLabel(self.frame)
        self.taxeslabel.setObjectName(u"taxeslabel")
        self.taxeslabel.setGeometry(QRect(120, 10, 49, 16))
        self.taxeslabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.equals2 = QLabel(self.frame)
        self.equals2.setObjectName(u"equals2")
        self.equals2.setGeometry(QRect(190, 180, 49, 16))
        self.icandtaxes = QLineEdit(self.frame)
        self.icandtaxes.setObjectName(u"icandtaxes")
        self.icandtaxes.setGeometry(QRect(70, 110, 61, 22))
        self.minus = QLabel(self.frame)
        self.minus.setObjectName(u"minus")
        self.minus.setGeometry(QRect(140, 110, 49, 16))
        self.discount = QLineEdit(self.frame)
        self.discount.setObjectName(u"discount")
        self.discount.setGeometry(QRect(160, 110, 61, 22))
        self.discountlabel = QLabel(self.frame)
        self.discountlabel.setObjectName(u"discountlabel")
        self.discountlabel.setGeometry(QRect(170, 90, 49, 16))
        self.discountlabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.equals = QLabel(self.frame)
        self.equals.setObjectName(u"equals")
        self.equals.setGeometry(QRect(50, 110, 51, 20))
        self.totalcost = QLineEdit(self.frame)
        self.totalcost.setObjectName(u"totalcost")
        self.totalcost.setGeometry(QRect(210, 180, 113, 22))
        self.totalcostlabel = QLabel(self.frame)
        self.totalcostlabel.setObjectName(u"totalcostlabel")
        self.totalcostlabel.setGeometry(QRect(240, 160, 61, 16))
        self.totalcostlabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.coupons = QComboBox(self.frame)
        self.coupons.addItem("")
        self.coupons.setObjectName(u"coupons")
        self.coupons.setGeometry(QRect(250, 30, 69, 22))
        self.couponslabel = QLabel(self.frame)
        self.couponslabel.setObjectName(u"couponslabel")
        self.couponslabel.setGeometry(QRect(260, 10, 49, 16))
        self.couponslabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.clearb = QPushButton(self.frame)
        self.clearb.setObjectName(u"clearb")
        self.clearb.setGeometry(QRect(10, 260, 101, 24))
        self.payb = QPushButton(self.frame)
        self.payb.setObjectName(u"payb")
        self.payb.setGeometry(QRect(230, 260, 101, 24))
        self.closeb = QPushButton(self.frame)
        self.closeb.setObjectName(u"closeb")
        self.closeb.setGeometry(QRect(120, 260, 101, 24))
        self.groupBox = QGroupBox(payment)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(130, 0, 121, 321))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.groupBox.setPalette(palette1)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.groupBox.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.orderlist = QListView(self.groupBox)
        self.orderlist.setObjectName(u"orderlist")
        self.orderlist.setGeometry(QRect(0, 10, 121, 311))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush5)
        brush11 = QBrush(QColor(9, 8, 7, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush11)
        brush12 = QBrush(QColor(255, 255, 0, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush12)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        brush13 = QBrush(QColor(51, 102, 153, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        brush14 = QBrush(QColor(255, 0, 0, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush14)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.orderlist.setPalette(palette2)
        self.orderlist.setMouseTracking(False)
        self.orderlist.setAcceptDrops(False)
        self.orderlist.setAutoFillBackground(True)
        self.orderlist.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.orderlist.setFrameShape(QFrame.Shape.StyledPanel)
        self.orderlist.setFrameShadow(QFrame.Shadow.Plain)
        self.orderlist.setLineWidth(9)
        self.orderlist.setMidLineWidth(0)
        self.orderlist.setTabKeyNavigation(True)
        self.orderlist.setProperty(u"showDropIndicator", False)
        self.orderlist.setAlternatingRowColors(True)
        self.orderlist.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.orderlist.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.orderlist.setModelColumn(0)
        self.orderlist.setUniformItemSizes(True)
        self.orderlist.setItemAlignment(Qt.AlignmentFlag.AlignLeading)
        self.groupBox_2 = QGroupBox(payment)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 0, 131, 321))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.groupBox_2.setPalette(palette3)
        self.groupBox_2.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.groupBox_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cashb = QRadioButton(self.groupBox_2)
        self.cashb.setObjectName(u"cashb")
        self.cashb.setGeometry(QRect(10, 30, 101, 20))
        self.creditb = QRadioButton(self.groupBox_2)
        self.creditb.setObjectName(u"creditb")
        self.creditb.setGeometry(QRect(10, 80, 101, 20))
        self.debitb = QRadioButton(self.groupBox_2)
        self.debitb.setObjectName(u"debitb")
        self.debitb.setGeometry(QRect(10, 130, 101, 20))
        self.checkb = QRadioButton(self.groupBox_2)
        self.checkb.setObjectName(u"checkb")
        self.checkb.setGeometry(QRect(10, 180, 101, 20))
        self.otherb = QRadioButton(self.groupBox_2)
        self.otherb.setObjectName(u"otherb")
        self.otherb.setGeometry(QRect(10, 230, 101, 20))
        self.unableb = QRadioButton(self.groupBox_2)
        self.unableb.setObjectName(u"unableb")
        self.unableb.setGeometry(QRect(10, 280, 101, 20))

        self.retranslateUi(payment)

        QMetaObject.connectSlotsByName(payment)
    # setupUi

    def retranslateUi(self, payment):
        payment.setWindowTitle(QCoreApplication.translate("payment", u"Form", None))
        self.plus.setText(QCoreApplication.translate("payment", u"+", None))
        self.icostlabel.setText(QCoreApplication.translate("payment", u"Initial Cost", None))
        self.taxeslabel.setText(QCoreApplication.translate("payment", u"Taxes", None))
        self.equals2.setText(QCoreApplication.translate("payment", u"=", None))
        self.icandtaxes.setText("")
        self.minus.setText(QCoreApplication.translate("payment", u"-", None))
        self.discount.setText("")
        self.discountlabel.setText(QCoreApplication.translate("payment", u"Discount", None))
        self.equals.setText(QCoreApplication.translate("payment", u"=", None))
        self.totalcostlabel.setText(QCoreApplication.translate("payment", u"Total Cost", None))
        self.coupons.setItemText(0, QCoreApplication.translate("payment", u"5$ Off", None))

        self.couponslabel.setText(QCoreApplication.translate("payment", u"Coupons", None))
        self.clearb.setText(QCoreApplication.translate("payment", u"Clear", None))
        self.payb.setText(QCoreApplication.translate("payment", u"Pay", None))
        self.closeb.setText(QCoreApplication.translate("payment", u"Cancel + Close", None))
        self.groupBox.setTitle(QCoreApplication.translate("payment", u"Orders Being Paid", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("payment", u"Payment Methods", None))
        self.cashb.setText(QCoreApplication.translate("payment", u"  Cash", None))
        self.creditb.setText(QCoreApplication.translate("payment", u"  Credit Card", None))
        self.debitb.setText(QCoreApplication.translate("payment", u"  Debit Card", None))
        self.checkb.setText(QCoreApplication.translate("payment", u"  Check", None))
        self.otherb.setText(QCoreApplication.translate("payment", u"  Other", None))
        self.unableb.setText(QCoreApplication.translate("payment", u"Unable To Pay", None))
    # retranslateUi

