# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'caccountmoreinfo.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QFrame, QGroupBox, QLabel, QLineEdit,
    QProgressBar, QPushButton, QSizePolicy, QVBoxLayout,
    QWidget)
import resources_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1016, 762)
        self.actionClose = QAction(Dialog)
        self.actionClose.setObjectName(u"actionClose")
        icon = QIcon(QIcon.fromTheme(u"application-exit"))
        self.actionClose.setIcon(icon)
        self.actionClose.setMenuRole(QAction.MenuRole.QuitRole)
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(-6, 0, 995, 700))
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(170, 85, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush4)
        brush5 = QBrush(QColor(120, 131, 170, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush7 = QBrush(QColor(85, 0, 255, 128))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        brush8 = QBrush(QColor(255, 85, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        brush9 = QBrush(QColor(169, 77, 193, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        brush10 = QBrush(QColor(64, 14, 89, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.frame.setPalette(palette)
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.buttonBox = QDialogButtonBox(self.frame)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(530, 652, 341, 32))
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.deliveryinfo = QGroupBox(self.frame)
        self.deliveryinfo.setObjectName(u"deliveryinfo")
        self.deliveryinfo.setGeometry(QRect(22, 109, 480, 535))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.deliveryinfo.setPalette(palette1)
        self.deliveryinfo.setStyleSheet(u"")
        self.frame_2 = QFrame(self.deliveryinfo)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(233, 62, 222, 395))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.del_address_input = QLineEdit(self.frame_2)
        self.del_address_input.setObjectName(u"del_address_input")

        self.verticalLayout_2.addWidget(self.del_address_input)

        self.ste_apt_input = QLineEdit(self.frame_2)
        self.ste_apt_input.setObjectName(u"ste_apt_input")

        self.verticalLayout_2.addWidget(self.ste_apt_input)

        self.zip_input = QLineEdit(self.frame_2)
        self.zip_input.setObjectName(u"zip_input")

        self.verticalLayout_2.addWidget(self.zip_input)

        self.special_instructions_input = QLineEdit(self.frame_2)
        self.special_instructions_input.setObjectName(u"special_instructions_input")

        self.verticalLayout_2.addWidget(self.special_instructions_input)

        self.idk = QLineEdit(self.frame_2)
        self.idk.setObjectName(u"idk")

        self.verticalLayout_2.addWidget(self.idk)

        self.frame_4 = QFrame(self.deliveryinfo)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(26, 62, 205, 395))
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label = QLabel(self.frame_4)
        self.label.setObjectName(u"label")

        self.verticalLayout.addWidget(self.label)

        self.label_2 = QLabel(self.frame_4)
        self.label_2.setObjectName(u"label_2")

        self.verticalLayout.addWidget(self.label_2)

        self.label_3 = QLabel(self.frame_4)
        self.label_3.setObjectName(u"label_3")

        self.verticalLayout.addWidget(self.label_3)

        self.label_4 = QLabel(self.frame_4)
        self.label_4.setObjectName(u"label_4")

        self.verticalLayout.addWidget(self.label_4)

        self.idk_2 = QLabel(self.frame_4)
        self.idk_2.setObjectName(u"idk_2")

        self.verticalLayout.addWidget(self.idk_2)

        self.savedelinfo = QPushButton(self.deliveryinfo)
        self.savedelinfo.setObjectName(u"savedelinfo")
        self.savedelinfo.setGeometry(QRect(179, 484, 108, 25))
        self.ccardinfo = QGroupBox(self.frame)
        self.ccardinfo.setObjectName(u"ccardinfo")
        self.ccardinfo.setGeometry(QRect(503, 109, 474, 535))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.ccardinfo.setPalette(palette2)
        self.ccardinfo.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_3 = QFrame(self.ccardinfo)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(231, 66, 185, 388))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.nameoncard = QLineEdit(self.frame_3)
        self.nameoncard.setObjectName(u"nameoncard")

        self.verticalLayout_4.addWidget(self.nameoncard)

        self.ccnumber = QLineEdit(self.frame_3)
        self.ccnumber.setObjectName(u"ccnumber")

        self.verticalLayout_4.addWidget(self.ccnumber)

        self.expdate = QLineEdit(self.frame_3)
        self.expdate.setObjectName(u"expdate")

        self.verticalLayout_4.addWidget(self.expdate)

        self.cvv = QLineEdit(self.frame_3)
        self.cvv.setObjectName(u"cvv")

        self.verticalLayout_4.addWidget(self.cvv)

        self.billingaddress = QLineEdit(self.frame_3)
        self.billingaddress.setObjectName(u"billingaddress")

        self.verticalLayout_4.addWidget(self.billingaddress)

        self.billingzip = QLineEdit(self.frame_3)
        self.billingzip.setObjectName(u"billingzip")

        self.verticalLayout_4.addWidget(self.billingzip)

        self.frame_5 = QFrame(self.ccardinfo)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(19, 60, 136, 400))
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.name_on_card_label = QLabel(self.frame_5)
        self.name_on_card_label.setObjectName(u"name_on_card_label")

        self.verticalLayout_3.addWidget(self.name_on_card_label)

        self.label_7 = QLabel(self.frame_5)
        self.label_7.setObjectName(u"label_7")

        self.verticalLayout_3.addWidget(self.label_7)

        self.label_9 = QLabel(self.frame_5)
        self.label_9.setObjectName(u"label_9")

        self.verticalLayout_3.addWidget(self.label_9)

        self.label_8 = QLabel(self.frame_5)
        self.label_8.setObjectName(u"label_8")

        self.verticalLayout_3.addWidget(self.label_8)

        self.label_10 = QLabel(self.frame_5)
        self.label_10.setObjectName(u"label_10")

        self.verticalLayout_3.addWidget(self.label_10)

        self.label_11 = QLabel(self.frame_5)
        self.label_11.setObjectName(u"label_11")

        self.verticalLayout_3.addWidget(self.label_11)

        self.saveccinfo = QPushButton(self.ccardinfo)
        self.saveccinfo.setObjectName(u"saveccinfo")
        self.saveccinfo.setGeometry(QRect(181, 485, 126, 24))
        self.progressBar = QProgressBar(self.frame)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(67, 649, 269, 37))
        self.progressBar.setSizeIncrement(QSize(0, 0))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.progressBar.setPalette(palette3)
        font = QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.progressBar.setFont(font)
        self.progressBar.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.moreinfoheader = QLabel(self.frame)
        self.moreinfoheader.setObjectName(u"moreinfoheader")
        self.moreinfoheader.setGeometry(QRect(373, 3, 258, 108))
        font1 = QFont()
        font1.setPointSize(32)
        font1.setBold(True)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.moreinfoheader.setFont(font1)
        self.moreinfoheader.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.moreinfoheader.setStyleSheet(u"")
        self.moreinfoheader.setFrameShape(QFrame.Shape.StyledPanel)
        self.moreinfoheader.setFrameShadow(QFrame.Shadow.Plain)
        self.moreinfoheader.setLineWidth(3)
        self.moreinfoheader.setMidLineWidth(3)
        self.moreinfoheader.setPixmap(QPixmap(u":/newPrefix/Images/Logos/OGDC-Logo.jpg"))
        self.moreinfoheader.setScaledContents(True)
        self.moreinfoheader.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.moreinfoheader.setWordWrap(True)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.actionClose.triggered.connect(Dialog.close)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.actionClose.setText(QCoreApplication.translate("Dialog", u"Close", None))
#if QT_CONFIG(tooltip)
        self.actionClose.setToolTip(QCoreApplication.translate("Dialog", u"Close the current window", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionClose.setShortcut(QCoreApplication.translate("Dialog", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.deliveryinfo.setTitle(QCoreApplication.translate("Dialog", u"Delivery Info", None))
        self.del_address_input.setText("")
        self.ste_apt_input.setText("")
        self.zip_input.setText("")
        self.special_instructions_input.setText("")
        self.label.setText(QCoreApplication.translate("Dialog", u"Delivery Address", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Ste or Apt #", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Zip code", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Special instructions for driver", None))
        self.idk_2.setText(QCoreApplication.translate("Dialog", u"???????????", None))
        self.savedelinfo.setText(QCoreApplication.translate("Dialog", u"Save Delivery Info", None))
        self.ccardinfo.setTitle(QCoreApplication.translate("Dialog", u"Credit Card Info", None))
        self.name_on_card_label.setText(QCoreApplication.translate("Dialog", u"Name on Card", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Credit Card #", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Expiration Date", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Cvv", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Billing Address", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Billing Zip Code", None))
        self.saveccinfo.setText(QCoreApplication.translate("Dialog", u"Save Credit Card Info", None))
#if QT_CONFIG(tooltip)
        self.progressBar.setToolTip(QCoreApplication.translate("Dialog", u"Fill out all of the information!", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.progressBar.setWhatsThis(QCoreApplication.translate("Dialog", u"Amount of information filled out", None))
#endif // QT_CONFIG(whatsthis)
        self.moreinfoheader.setText("")
    # retranslateUi

