from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect, Signal, QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform,
    QAction)
from PySide6.QtWidgets import (QApplication, QGroupBox, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTextEdit,
    QTreeWidget, QTreeWidgetItem, QWidget, QDialog,
    QListWidget, QListWidgetItem, QComboBox, QDateEdit,
    QPlainTextEdit, QSpinBox, QTextBrowser, QMenu, QVBoxLayout, QStackedWidget)
import sqlite3



class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.resize(919, 754)
        self.actionAdd_Image = QAction(Main)
        self.actionAdd_Image.setObjectName(u"actionAdd_Image")
        self.actionAdd_Image.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.centralwidget = QWidget(Main)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ncbutton = QPushButton(self.centralwidget)
        self.ncbutton.setObjectName(u"ncbutton")
        self.ncbutton.setGeometry(QRect(0, 0, 121, 31))
        self.ncbutton.setMouseTracking(False)
        self.ncbutton.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.ncbutton.setAcceptDrops(False)
        self.ncbutton.setAutoRepeatDelay(301)
        self.ttcbutton = QPushButton(self.centralwidget)
        self.ttcbutton.setObjectName(u"ttcbutton")
        self.ttcbutton.setGeometry(QRect(260, 0, 121, 31))
        self.gandccbutton = QPushButton(self.centralwidget)
        self.gandccbutton.setObjectName(u"gandccbutton")
        self.gandccbutton.setGeometry(QRect(520, 0, 151, 31))
        self.tocbutton = QPushButton(self.centralwidget)
        self.tocbutton.setObjectName(u"tocbutton")
        self.tocbutton.setGeometry(QRect(790, 0, 131, 31))
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Main)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 919, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        Main.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Main)
        self.statusbar.setObjectName(u"statusbar")
        Main.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionAdd_Image)

        self.retranslateUi(Main)

        self.ncbutton.setDefault(False)


        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"MainWindow", None))
        self.actionAdd_Image.setText(QCoreApplication.translate("Main", u"Add Image", None))
#if QT_CONFIG(shortcut)
        self.actionAdd_Image.setShortcut(QCoreApplication.translate("Main", u"Ctrl+Alt+I", None))
#endif // QT_CONFIG(shortcut)
        self.ncbutton.setText(QCoreApplication.translate("Main", u"Next Customer", None))
        self.ttcbutton.setText(QCoreApplication.translate("Main", u"Ticket Type Creation", None))
        self.gandccbutton.setText(QCoreApplication.translate("Main", u"Garment + Color Creation", None))
        self.tocbutton.setText(QCoreApplication.translate("Main", u"Ticket Options Creation", None))
        self.menuFile.setTitle(QCoreApplication.translate("Main", u"File", None))
    # retranslateUi

class Ui_CustomerSearch(object):
    def setupUi(self, CustomerSearch):
        if not CustomerSearch.objectName():
            CustomerSearch.setObjectName(u"CustomerSearch")
        CustomerSearch.resize(640, 404)
        self.pnsearch = QLineEdit(CustomerSearch)
        self.pnsearch.setObjectName(u"pnsearch")
        self.pnsearch.setGeometry(QRect(50, 160, 113, 22))
        self.lnsearch = QLineEdit(CustomerSearch)
        self.lnsearch.setObjectName(u"lnsearch")
        self.lnsearch.setGeometry(QRect(50, 60, 113, 22))
        self.lnlabel = QLabel(CustomerSearch)
        self.lnlabel.setObjectName(u"lnlabel")
        self.lnlabel.setGeometry(QRect(50, 40, 81, 16))
        self.pnlabel = QLabel(CustomerSearch)
        self.pnlabel.setObjectName(u"pnlabel")
        self.pnlabel.setGeometry(QRect(50, 140, 49, 16))
        self.resultslist = QTreeWidget(CustomerSearch)
        self.resultslist.setObjectName(u"resultslist")
        self.resultslist.setGeometry(QRect(170, 40, 361, 211))
        self.fnsearch = QLineEdit(CustomerSearch)
        self.fnsearch.setObjectName(u"fnsearch")
        self.fnsearch.setGeometry(QRect(50, 110, 113, 22))
        self.fnlabel = QLabel(CustomerSearch)
        self.fnlabel.setObjectName(u"fnlabel")
        self.fnlabel.setGeometry(QRect(50, 90, 71, 16))
        self.ncbutton = QPushButton(CustomerSearch)
        self.ncbutton.setObjectName(u"ncbutton")
        self.ncbutton.setGeometry(QRect(170, 270, 101, 31))
        self.searchbutton = QPushButton(CustomerSearch)
        self.searchbutton.setObjectName(u"searchbutton")
        self.searchbutton.setGeometry(QRect(310, 270, 91, 31))
        self.closebutton = QPushButton(CustomerSearch)
        self.closebutton.setObjectName(u"closebutton")
        self.closebutton.setGeometry(QRect(440, 270, 91, 31))

        self.retranslateUi(CustomerSearch)

        QMetaObject.connectSlotsByName(CustomerSearch)
    # setupUi

    def retranslateUi(self, CustomerSearch):
        CustomerSearch.setWindowTitle(QCoreApplication.translate("CustomerSearch", u"Dialog", None))
        self.lnlabel.setText(QCoreApplication.translate("CustomerSearch", u"Last Name:", None))
        self.pnlabel.setText(QCoreApplication.translate("CustomerSearch", u"Phone#:", None))
        ___qtreewidgetitem = self.resultslist.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("CustomerSearch", u"Phone#", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("CustomerSearch", u"Name                                                                                                        ", None));
        self.fnlabel.setText(QCoreApplication.translate("CustomerSearch", u"First Name:", None))
        self.ncbutton.setText(QCoreApplication.translate("CustomerSearch", u"New Customer", None))
        self.searchbutton.setText(QCoreApplication.translate("CustomerSearch", u"Search", None))
        self.closebutton.setText(QCoreApplication.translate("CustomerSearch", u"Close", None))
    # retranslateUi

class Ui_CustomerAccount(object):
    def setupUi(self, CustomerAccount):
        if not CustomerAccount.objectName():
            CustomerAccount.setObjectName(u"CustomerAccount")
        CustomerAccount.resize(1310, 956)
        self.centralwidget = QWidget(CustomerAccount)
        self.centralwidget.setObjectName(u"centralwidget")
        self.catabs = QTabWidget(self.centralwidget)
        self.catabs.setObjectName(u"catabs")
        self.catabs.setGeometry(QRect(50, 30, 1171, 811))
        self.catabs.setTabShape(QTabWidget.TabShape.Rounded)
        self.catabs.setElideMode(Qt.TextElideMode.ElideNone)
        self.catabs.setTabsClosable(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.cinfobox = QGroupBox(self.tab)
        self.cinfobox.setObjectName(u"cinfobox")
        self.cinfobox.setGeometry(QRect(0, 0, 231, 231))
        self.lninput = QLineEdit(self.cinfobox)
        self.lninput.setObjectName(u"lninput")
        self.lninput.setGeometry(QRect(10, 40, 101, 22))
        self.lnlabel = QLabel(self.cinfobox)
        self.lnlabel.setObjectName(u"lnlabel")
        self.lnlabel.setGeometry(QRect(10, 20, 111, 16))
        self.fnlabel = QLabel(self.cinfobox)
        self.fnlabel.setObjectName(u"fnlabel")
        self.fnlabel.setGeometry(QRect(120, 20, 101, 16))
        self.fninput = QLineEdit(self.cinfobox)
        self.fninput.setObjectName(u"fninput")
        self.fninput.setGeometry(QRect(122, 40, 101, 22))
        self.pnlabel = QLabel(self.cinfobox)
        self.pnlabel.setObjectName(u"pnlabel")
        self.pnlabel.setGeometry(QRect(10, 70, 91, 16))
        self.pninput = QLineEdit(self.cinfobox)
        self.pninput.setObjectName(u"pninput")
        self.pninput.setGeometry(QRect(10, 90, 211, 22))
        self.ninput = QTextEdit(self.cinfobox)
        self.ninput.setObjectName(u"ninput")
        self.ninput.setGeometry(QRect(10, 140, 211, 81))
        self.nlabel = QLabel(self.cinfobox)
        self.nlabel.setObjectName(u"nlabel")
        self.nlabel.setGeometry(QRect(10, 120, 61, 16))
        self.ctlist = QTreeWidget(self.tab)
        self.ctlist.setObjectName(u"ctlist")
        self.ctlist.setGeometry(QRect(240, 10, 641, 581))
        self.qtbutton = QPushButton(self.tab)
        self.qtbutton.setObjectName(u"qtbutton")
        self.qtbutton.setGeometry(QRect(0, 360, 75, 24))
        self.paybutton = QPushButton(self.tab)
        self.paybutton.setObjectName(u"paybutton")
        self.paybutton.setGeometry(QRect(80, 360, 75, 24))
        self.puandpbutton = QPushButton(self.tab)
        self.puandpbutton.setObjectName(u"puandpbutton")
        self.puandpbutton.setGeometry(QRect(160, 360, 81, 24))
        self.pushButton_4 = QPushButton(self.tab)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(0, 240, 75, 24))
        self.pushButton_5 = QPushButton(self.tab)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(80, 240, 75, 24))
        self.pushButton_6 = QPushButton(self.tab)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(160, 240, 75, 24))
        self.pushButton_7 = QPushButton(self.tab)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(0, 270, 75, 24))
        self.pushButton_8 = QPushButton(self.tab)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(80, 270, 75, 24))
        self.pushButton_9 = QPushButton(self.tab)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(160, 270, 75, 24))
        self.catabs.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_10 = QPushButton(self.tab_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(160, 270, 75, 24))
        self.qtbutton_2 = QPushButton(self.tab_2)
        self.qtbutton_2.setObjectName(u"qtbutton_2")
        self.qtbutton_2.setGeometry(QRect(0, 360, 75, 24))
        self.cinfobox_2 = QGroupBox(self.tab_2)
        self.cinfobox_2.setObjectName(u"cinfobox_2")
        self.cinfobox_2.setGeometry(QRect(0, 0, 231, 231))
        self.fninput_2 = QLineEdit(self.cinfobox_2)
        self.fninput_2.setObjectName(u"fninput_2")
        self.fninput_2.setGeometry(QRect(122, 40, 101, 22))
        self.lnlabel_2 = QLabel(self.cinfobox_2)
        self.lnlabel_2.setObjectName(u"lnlabel_2")
        self.lnlabel_2.setGeometry(QRect(10, 20, 111, 16))
        self.pninput_2 = QLineEdit(self.cinfobox_2)
        self.pninput_2.setObjectName(u"pninput_2")
        self.pninput_2.setGeometry(QRect(10, 90, 211, 22))
        self.lninput_2 = QLineEdit(self.cinfobox_2)
        self.lninput_2.setObjectName(u"lninput_2")
        self.lninput_2.setGeometry(QRect(10, 40, 101, 22))
        self.nlabel_2 = QLabel(self.cinfobox_2)
        self.nlabel_2.setObjectName(u"nlabel_2")
        self.nlabel_2.setGeometry(QRect(10, 120, 61, 16))
        self.ninput_2 = QTextEdit(self.cinfobox_2)
        self.ninput_2.setObjectName(u"ninput_2")
        self.ninput_2.setGeometry(QRect(10, 140, 211, 81))
        self.pnlabel_2 = QLabel(self.cinfobox_2)
        self.pnlabel_2.setObjectName(u"pnlabel_2")
        self.pnlabel_2.setGeometry(QRect(10, 70, 91, 16))
        self.fnlabel_2 = QLabel(self.cinfobox_2)
        self.fnlabel_2.setObjectName(u"fnlabel_2")
        self.fnlabel_2.setGeometry(QRect(120, 20, 101, 16))
        self.pushButton_11 = QPushButton(self.tab_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(80, 240, 75, 24))
        self.pushButton_12 = QPushButton(self.tab_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(160, 240, 75, 24))
        self.ctlist_2 = QTreeWidget(self.tab_2)
        self.ctlist_2.setObjectName(u"ctlist_2")
        self.ctlist_2.setGeometry(QRect(240, 10, 641, 581))
        self.pushButton_13 = QPushButton(self.tab_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(80, 270, 75, 24))
        self.pushButton_14 = QPushButton(self.tab_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(0, 240, 75, 24))
        self.puandpbutton_2 = QPushButton(self.tab_2)
        self.puandpbutton_2.setObjectName(u"puandpbutton_2")
        self.puandpbutton_2.setGeometry(QRect(160, 360, 81, 24))
        self.pushButton_15 = QPushButton(self.tab_2)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(0, 270, 75, 24))
        self.paybutton_2 = QPushButton(self.tab_2)
        self.paybutton_2.setObjectName(u"paybutton_2")
        self.paybutton_2.setGeometry(QRect(80, 360, 75, 24))
        self.catabs.addTab(self.tab_2, "")
        CustomerAccount.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(CustomerAccount)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1310, 33))
        CustomerAccount.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(CustomerAccount)
        self.statusbar.setObjectName(u"statusbar")
        CustomerAccount.setStatusBar(self.statusbar)

        self.retranslateUi(CustomerAccount)

        self.catabs.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(CustomerAccount)
    # setupUi

    def retranslateUi(self, CustomerAccount):
        CustomerAccount.setWindowTitle(QCoreApplication.translate("CustomerAccount", u"MainWindow", None))
        self.cinfobox.setTitle(QCoreApplication.translate("CustomerAccount", u"Customer Information", None))
        self.lnlabel.setText(QCoreApplication.translate("CustomerAccount", u"Last Name:", None))
        self.fnlabel.setText(QCoreApplication.translate("CustomerAccount", u"First Name:", None))
        self.pnlabel.setText(QCoreApplication.translate("CustomerAccount", u"Phone#:", None))
        self.nlabel.setText(QCoreApplication.translate("CustomerAccount", u"Notes:", None))
        ___qtreewidgetitem = self.ctlist.headerItem()
        ___qtreewidgetitem.setText(5, QCoreApplication.translate("CustomerAccount", u"Billing Invoice#", None));
        ___qtreewidgetitem.setText(4, QCoreApplication.translate("CustomerAccount", u"Ticket#", None));
        ___qtreewidgetitem.setText(3, QCoreApplication.translate("CustomerAccount", u"Ticket Type", None));
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("CustomerAccount", u"Drop Off Date", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("CustomerAccount", u"Picked up + Paid", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("CustomerAccount", u"Paid", None));
        self.qtbutton.setText(QCoreApplication.translate("CustomerAccount", u"Quick Ticket", None))
        self.paybutton.setText(QCoreApplication.translate("CustomerAccount", u"Pay", None))
        self.puandpbutton.setText(QCoreApplication.translate("CustomerAccount", u"Pick up + Pay", None))
        self.pushButton_4.setText(QCoreApplication.translate("CustomerAccount", u"Dry Clean", None))
        self.pushButton_5.setText(QCoreApplication.translate("CustomerAccount", u"Laundry", None))
        self.pushButton_6.setText(QCoreApplication.translate("CustomerAccount", u"Household", None))
        self.pushButton_7.setText(QCoreApplication.translate("CustomerAccount", u"Alteration", None))
        self.pushButton_8.setText(QCoreApplication.translate("CustomerAccount", u"Press Only", None))
        self.pushButton_9.setText(QCoreApplication.translate("CustomerAccount", u"Fluff + Fold", None))
        self.catabs.setTabText(self.catabs.indexOf(self.tab), QCoreApplication.translate("CustomerAccount", u"Customer1", None))
        self.pushButton_10.setText(QCoreApplication.translate("CustomerAccount", u"Fluff + Fold", None))
        self.qtbutton_2.setText(QCoreApplication.translate("CustomerAccount", u"Quick Ticket", None))
        self.cinfobox_2.setTitle(QCoreApplication.translate("CustomerAccount", u"Customer Information", None))
        self.lnlabel_2.setText(QCoreApplication.translate("CustomerAccount", u"Last Name:", None))
        self.nlabel_2.setText(QCoreApplication.translate("CustomerAccount", u"Notes:", None))
        self.pnlabel_2.setText(QCoreApplication.translate("CustomerAccount", u"Phone#:", None))
        self.fnlabel_2.setText(QCoreApplication.translate("CustomerAccount", u"First Name:", None))
        self.pushButton_11.setText(QCoreApplication.translate("CustomerAccount", u"Laundry", None))
        self.pushButton_12.setText(QCoreApplication.translate("CustomerAccount", u"Household", None))
        ___qtreewidgetitem1 = self.ctlist_2.headerItem()
        ___qtreewidgetitem1.setText(5, QCoreApplication.translate("CustomerAccount", u"Billing Invoice#", None));
        ___qtreewidgetitem1.setText(4, QCoreApplication.translate("CustomerAccount", u"Ticket#", None));
        ___qtreewidgetitem1.setText(3, QCoreApplication.translate("CustomerAccount", u"Ticket Type", None));
        ___qtreewidgetitem1.setText(2, QCoreApplication.translate("CustomerAccount", u"Drop Off Date", None));
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("CustomerAccount", u"Picked up + Paid", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("CustomerAccount", u"Paid", None));
        self.pushButton_13.setText(QCoreApplication.translate("CustomerAccount", u"Press Only", None))
        self.pushButton_14.setText(QCoreApplication.translate("CustomerAccount", u"Dry Clean", None))
        self.puandpbutton_2.setText(QCoreApplication.translate("CustomerAccount", u"Pick up + Pay", None))
        self.pushButton_15.setText(QCoreApplication.translate("CustomerAccount", u"Alteration", None))
        self.paybutton_2.setText(QCoreApplication.translate("CustomerAccount", u"Pay", None))
        self.catabs.setTabText(self.catabs.indexOf(self.tab_2), QCoreApplication.translate("CustomerAccount", u"Customer2", None))
    # retranslateUi

class Ui_CustomerAccount2(object):
    def setupUi(self, CustomerAccount2):
        if not CustomerAccount2.objectName():
            CustomerAccount2.setObjectName(u"CustomerAccount2")
        CustomerAccount2.resize(1460, 1173)
        self.centralwidget = QWidget(CustomerAccount2)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 20, 1451, 1061))
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.puandpbutton = QPushButton(self.page1)
        self.puandpbutton.setObjectName(u"puandpbutton")
        self.puandpbutton.setGeometry(QRect(250, 630, 91, 21))
        self.paybutton = QPushButton(self.page1)
        self.paybutton.setObjectName(u"paybutton")
        self.paybutton.setGeometry(QRect(140, 630, 75, 24))
        self.pushButton_6 = QPushButton(self.page1)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(250, 490, 91, 24))
        self.ctlist = QTreeWidget(self.page1)
        self.ctlist.setObjectName(u"ctlist")
        self.ctlist.setGeometry(QRect(390, 10, 881, 781))
        self.pushButton_7 = QPushButton(self.page1)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(30, 540, 75, 24))
        self.pushButton_4 = QPushButton(self.page1)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(30, 490, 75, 24))
        self.pushButton_5 = QPushButton(self.page1)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(140, 490, 75, 24))
        self.qtbutton = QPushButton(self.page1)
        self.qtbutton.setObjectName(u"qtbutton")
        self.qtbutton.setGeometry(QRect(30, 630, 75, 24))
        self.pushButton_9 = QPushButton(self.page1)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(250, 540, 91, 24))
        self.pushButton_8 = QPushButton(self.page1)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(140, 540, 75, 24))
        self.tabWidget = QTabWidget(self.page1)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 10, 381, 381))
        self.tab1 = QWidget()
        self.tab1.setObjectName(u"tab1")
        self.FirstName = QLabel(self.tab1)
        self.FirstName.setObjectName(u"FirstName")
        self.FirstName.setGeometry(QRect(230, 20, 71, 16))
        self.PhoneNumber = QLabel(self.tab1)
        self.PhoneNumber.setObjectName(u"PhoneNumber")
        self.PhoneNumber.setGeometry(QRect(150, 90, 81, 16))
        self.LastNameInput = QLineEdit(self.tab1)
        self.LastNameInput.setObjectName(u"LastNameInput")
        self.LastNameInput.setGeometry(QRect(40, 50, 141, 31))
        self.NotesInput = QPlainTextEdit(self.tab1)
        self.NotesInput.setObjectName(u"NotesInput")
        self.NotesInput.setGeometry(QRect(40, 200, 301, 131))
        self.PhoneNumberInput = QLineEdit(self.tab1)
        self.PhoneNumberInput.setObjectName(u"PhoneNumberInput")
        self.PhoneNumberInput.setGeometry(QRect(90, 120, 201, 31))
        self.LastName = QLabel(self.tab1)
        self.LastName.setObjectName(u"LastName")
        self.LastName.setGeometry(QRect(40, 20, 61, 16))
        self.FirstNameInput = QLineEdit(self.tab1)
        self.FirstNameInput.setObjectName(u"FirstNameInput")
        self.FirstNameInput.setGeometry(QRect(222, 50, 121, 31))
        self.Notes = QLabel(self.tab1)
        self.Notes.setObjectName(u"Notes")
        self.Notes.setGeometry(QRect(180, 170, 49, 16))
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.lineEdit_9 = QLineEdit(self.tab_2)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(48, 785, 141, 31))
        self.lineEdit_7 = QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(98, 855, 201, 31))
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(48, 755, 61, 16))
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(238, 755, 71, 16))
        self.lineEdit_8 = QLineEdit(self.tab_2)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(230, 785, 121, 31))
        self.tabWidget.addTab(self.tab_2, "")
        self.label_17 = QLabel(self.page1)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(120, 0, 49, 16))
        self.pushButton = QPushButton(self.page1)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(130, 420, 101, 24))
        self.pushButton_16 = QPushButton(self.page1)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(1270, 10, 151, 41))
        self.stackedWidget.addWidget(self.page1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.ctlist_2 = QTreeWidget(self.page_2)
        self.ctlist_2.setObjectName(u"ctlist_2")
        self.ctlist_2.setGeometry(QRect(390, 10, 881, 781))
        self.tabWidget_2 = QTabWidget(self.page_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 10, 381, 381))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.FirstName_2 = QLabel(self.tab_3)
        self.FirstName_2.setObjectName(u"FirstName_2")
        self.FirstName_2.setGeometry(QRect(230, 20, 71, 16))
        self.PhoneNumber_2 = QLabel(self.tab_3)
        self.PhoneNumber_2.setObjectName(u"PhoneNumber_2")
        self.PhoneNumber_2.setGeometry(QRect(150, 90, 81, 16))
        self.LastNameInput_2 = QLineEdit(self.tab_3)
        self.LastNameInput_2.setObjectName(u"LastNameInput_2")
        self.LastNameInput_2.setGeometry(QRect(40, 50, 141, 31))
        self.NotesInput_2 = QPlainTextEdit(self.tab_3)
        self.NotesInput_2.setObjectName(u"NotesInput_2")
        self.NotesInput_2.setGeometry(QRect(40, 200, 301, 131))
        self.PhoneNumberInput_2 = QLineEdit(self.tab_3)
        self.PhoneNumberInput_2.setObjectName(u"PhoneNumberInput_2")
        self.PhoneNumberInput_2.setGeometry(QRect(90, 120, 201, 31))
        self.LastName_2 = QLabel(self.tab_3)
        self.LastName_2.setObjectName(u"LastName_2")
        self.LastName_2.setGeometry(QRect(40, 20, 61, 16))
        self.FirstNameInput_2 = QLineEdit(self.tab_3)
        self.FirstNameInput_2.setObjectName(u"FirstNameInput_2")
        self.FirstNameInput_2.setGeometry(QRect(222, 50, 121, 31))
        self.Notes_2 = QLabel(self.tab_3)
        self.Notes_2.setObjectName(u"Notes_2")
        self.Notes_2.setGeometry(QRect(180, 170, 49, 16))
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.lineEdit_16 = QLineEdit(self.tab_4)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(48, 785, 141, 31))
        self.lineEdit_17 = QLineEdit(self.tab_4)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(98, 855, 201, 31))
        self.label_15 = QLabel(self.tab_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(48, 755, 61, 16))
        self.label_16 = QLabel(self.tab_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(238, 755, 71, 16))
        self.lineEdit_18 = QLineEdit(self.tab_4)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(230, 785, 121, 31))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.pushButton_10 = QPushButton(self.page_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(250, 490, 91, 24))
        self.pushButton_11 = QPushButton(self.page_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(30, 540, 75, 24))
        self.pushButton_12 = QPushButton(self.page_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(250, 540, 91, 24))
        self.puandpbutton_2 = QPushButton(self.page_2)
        self.puandpbutton_2.setObjectName(u"puandpbutton_2")
        self.puandpbutton_2.setGeometry(QRect(250, 630, 91, 21))
        self.pushButton_13 = QPushButton(self.page_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(30, 490, 75, 24))
        self.qtbutton_2 = QPushButton(self.page_2)
        self.qtbutton_2.setObjectName(u"qtbutton_2")
        self.qtbutton_2.setGeometry(QRect(30, 630, 75, 24))
        self.pushButton_14 = QPushButton(self.page_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(140, 490, 75, 24))
        self.paybutton_2 = QPushButton(self.page_2)
        self.paybutton_2.setObjectName(u"paybutton_2")
        self.paybutton_2.setGeometry(QRect(140, 630, 75, 24))
        self.pushButton_15 = QPushButton(self.page_2)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(140, 540, 75, 24))
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(120, 0, 49, 16))
        self.pushButton_2 = QPushButton(self.page_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(130, 420, 101, 24))
        self.pushButton_3 = QPushButton(self.page_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(1270, 10, 151, 41))
        self.stackedWidget.addWidget(self.page_2)
        CustomerAccount2.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(CustomerAccount2)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1460, 33))
        CustomerAccount2.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(CustomerAccount2)
        self.statusbar.setObjectName(u"statusbar")
        CustomerAccount2.setStatusBar(self.statusbar)

        self.retranslateUi(CustomerAccount2)

        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(CustomerAccount2)
    # setupUi

    def retranslateUi(self, CustomerAccount2):
        CustomerAccount2.setWindowTitle(QCoreApplication.translate("CustomerAccount2", u"MainWindow", None))
        self.puandpbutton.setText(QCoreApplication.translate("CustomerAccount2", u"Pick up + Pay", None))
        self.paybutton.setText(QCoreApplication.translate("CustomerAccount2", u"Pay", None))
        self.pushButton_6.setText(QCoreApplication.translate("CustomerAccount2", u"Household", None))
        ___qtreewidgetitem = self.ctlist.headerItem()
        ___qtreewidgetitem.setText(5, QCoreApplication.translate("CustomerAccount2", u"Billing Invoice#", None));
        ___qtreewidgetitem.setText(4, QCoreApplication.translate("CustomerAccount2", u"Ticket#", None));
        ___qtreewidgetitem.setText(3, QCoreApplication.translate("CustomerAccount2", u"Ticket Type", None));
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("CustomerAccount2", u"Drop Off Date", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("CustomerAccount2", u"Picked up + Paid", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("CustomerAccount2", u"Paid", None));
        self.pushButton_7.setText(QCoreApplication.translate("CustomerAccount2", u"Alteration", None))
        self.pushButton_4.setText(QCoreApplication.translate("CustomerAccount2", u"Dry Clean", None))
        self.pushButton_5.setText(QCoreApplication.translate("CustomerAccount2", u"Laundry", None))
        self.qtbutton.setText(QCoreApplication.translate("CustomerAccount2", u"Quick Ticket", None))
        self.pushButton_9.setText(QCoreApplication.translate("CustomerAccount2", u"Fluff + Fold", None))
        self.pushButton_8.setText(QCoreApplication.translate("CustomerAccount2", u"Press Only", None))
        self.FirstName.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.PhoneNumber.setText(QCoreApplication.translate("CustomerAccount2", u"Phone Number", None))
        self.LastName.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.Notes.setText(QCoreApplication.translate("CustomerAccount2", u"Notes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QCoreApplication.translate("CustomerAccount2", u"Tab 1", None))
        self.label_9.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.label_7.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("CustomerAccount2", u"Tab 2", None))
        self.label_17.setText(QCoreApplication.translate("CustomerAccount2", u"Page 1", None))
        self.pushButton.setText(QCoreApplication.translate("CustomerAccount2", u"Next Customer", None))
        self.pushButton_16.setText(QCoreApplication.translate("CustomerAccount2", u"Go To Customer Account 2", None))
        ___qtreewidgetitem1 = self.ctlist_2.headerItem()
        ___qtreewidgetitem1.setText(5, QCoreApplication.translate("CustomerAccount2", u"Billing Invoice#", None));
        ___qtreewidgetitem1.setText(4, QCoreApplication.translate("CustomerAccount2", u"Ticket#", None));
        ___qtreewidgetitem1.setText(3, QCoreApplication.translate("CustomerAccount2", u"Ticket Type", None));
        ___qtreewidgetitem1.setText(2, QCoreApplication.translate("CustomerAccount2", u"Drop Off Date", None));
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("CustomerAccount2", u"Picked up + Paid", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("CustomerAccount2", u"Paid", None));
        self.FirstName_2.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.PhoneNumber_2.setText(QCoreApplication.translate("CustomerAccount2", u"Phone Number", None))
        self.LastName_2.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.Notes_2.setText(QCoreApplication.translate("CustomerAccount2", u"Notes", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("CustomerAccount2", u"Tab 1", None))
        self.label_15.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.label_16.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("CustomerAccount2", u"Tab 2", None))
        self.pushButton_10.setText(QCoreApplication.translate("CustomerAccount2", u"Household", None))
        self.pushButton_11.setText(QCoreApplication.translate("CustomerAccount2", u"Alteration", None))
        self.pushButton_12.setText(QCoreApplication.translate("CustomerAccount2", u"Fluff + Fold", None))
        self.puandpbutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Pick up + Pay", None))
        self.pushButton_13.setText(QCoreApplication.translate("CustomerAccount2", u"Dry Clean", None))
        self.qtbutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Quick Ticket", None))
        self.pushButton_14.setText(QCoreApplication.translate("CustomerAccount2", u"Laundry", None))
        self.paybutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Pay", None))
        self.pushButton_15.setText(QCoreApplication.translate("CustomerAccount2", u"Press Only", None))
        self.label_18.setText(QCoreApplication.translate("CustomerAccount2", u"Page 2", None))
        self.pushButton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Next Customer", None))
        self.pushButton_3.setText(QCoreApplication.translate("CustomerAccount2", u"Go To Customer Account 1", None))
    # retranslateUi






class Ui_GarmentandColorCreation(object):
    def setupUi(self, GarmentandColorCreation):
        if not GarmentandColorCreation.objectName():
            GarmentandColorCreation.setObjectName(u"GarmentandColorCreation")
        GarmentandColorCreation.resize(907, 721)
        GarmentandColorCreation.setStyleSheet(u"font: 9pt \"Segoe UI\";")
        self.centralwidget = QWidget(GarmentandColorCreation)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sgbutton = QPushButton(self.centralwidget)
        self.sgbutton.setObjectName(u"sgbutton")
        self.sgbutton.setGeometry(QRect(140, 300, 91, 24))
        self.sglist = QListWidget(self.centralwidget)
        self.sglist.setObjectName(u"sglist")
        self.sglist.setGeometry(QRect(390, 40, 501, 281))
        self.gninput = QLineEdit(self.centralwidget)
        self.gninput.setObjectName(u"gninput")
        self.gninput.setGeometry(QRect(140, 20, 113, 22))
        self.gnlabel = QLabel(self.centralwidget)
        self.gnlabel.setObjectName(u"gnlabel")
        self.gnlabel.setGeometry(QRect(50, 20, 91, 16))
        self.sglabel = QLabel(self.centralwidget)
        self.sglabel.setObjectName(u"sglabel")
        self.sglabel.setGeometry(QRect(610, 20, 91, 16))
        self.sglabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.avbutton = QPushButton(self.centralwidget)
        self.avbutton.setObjectName(u"avbutton")
        self.avbutton.setGeometry(QRect(130, 100, 121, 24))
        self.sibutton = QPushButton(self.centralwidget)
        self.sibutton.setObjectName(u"sibutton")
        self.sibutton.setGeometry(QRect(130, 60, 121, 24))
        self.avlist = QListWidget(self.centralwidget)
        self.avlist.setObjectName(u"avlist")
        self.avlist.setGeometry(QRect(65, 150, 251, 131))
        self.avlabel = QLabel(self.centralwidget)
        self.avlabel.setObjectName(u"avlabel")
        self.avlabel.setGeometry(QRect(150, 130, 81, 21))
        self.egbutton = QPushButton(self.centralwidget)
        self.egbutton.setObjectName(u"egbutton")
        self.egbutton.setGeometry(QRect(480, 330, 91, 24))
        self.dgbutton = QPushButton(self.centralwidget)
        self.dgbutton.setObjectName(u"dgbutton")
        self.dgbutton.setGeometry(QRect(720, 330, 91, 24))
        self.cninput = QLineEdit(self.centralwidget)
        self.cninput.setObjectName(u"cninput")
        self.cninput.setGeometry(QRect(240, 420, 113, 22))
        self.cnlabel = QLabel(self.centralwidget)
        self.cnlabel.setObjectName(u"cnlabel")
        self.cnlabel.setGeometry(QRect(160, 420, 71, 16))
        self.ccbutton = QPushButton(self.centralwidget)
        self.ccbutton.setObjectName(u"ccbutton")
        self.ccbutton.setGeometry(QRect(240, 500, 111, 24))
        self.sclist = QListWidget(self.centralwidget)
        self.sclist.setObjectName(u"sclist")
        self.sclist.setGeometry(QRect(490, 380, 256, 251))
        self.dcbutton = QPushButton(self.centralwidget)
        self.dcbutton.setObjectName(u"dcbutton")
        self.dcbutton.setGeometry(QRect(630, 640, 111, 24))
        self.scbutton = QPushButton(self.centralwidget)
        self.scbutton.setObjectName(u"scbutton")
        self.scbutton.setGeometry(QRect(240, 550, 111, 24))
        self.sclabel = QLabel(self.centralwidget)
        self.sclabel.setObjectName(u"sclabel")
        self.sclabel.setGeometry(QRect(590, 360, 91, 16))
        self.sclabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.ecbutton = QPushButton(self.centralwidget)
        self.ecbutton.setObjectName(u"ecbutton")
        self.ecbutton.setGeometry(QRect(490, 640, 111, 24))
        GarmentandColorCreation.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(GarmentandColorCreation)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 907, 33))
        GarmentandColorCreation.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(GarmentandColorCreation)
        self.statusbar.setObjectName(u"statusbar")
        GarmentandColorCreation.setStatusBar(self.statusbar)

        self.retranslateUi(GarmentandColorCreation)

        QMetaObject.connectSlotsByName(GarmentandColorCreation)
    # setupUi

    def retranslateUi(self, GarmentandColorCreation):
        GarmentandColorCreation.setWindowTitle(QCoreApplication.translate("GarmentandColorCreation", u"MainWindow", None))
        self.sgbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Save Garment", None))
        self.gnlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Garment Name:", None))
        self.sglabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Saved Garments", None))
        self.avbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Add Variation", None))
        self.sibutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Select Image", None))
        self.avlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"<html><head/><body><p><span style=\" font-size:7pt;\">Added Variations</span></p></body></html>", None))
        self.egbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Edit Garment", None))
        self.dgbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Delete Garment", None))
        self.cnlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Color Name:", None))
        self.ccbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Choose Color", None))
        self.dcbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Delete Color", None))
        self.scbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Save Color", None))
        self.sclabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Saved Colors", None))
        self.ecbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Edit Color", None))
    # retranslateUi


class Ui_TicketOptionsCreation(object):
    def setupUi(self, TicketOptionsCreation):
        if not TicketOptionsCreation.objectName():
            TicketOptionsCreation.setObjectName(u"TicketOptionsCreation")
        TicketOptionsCreation.resize(840, 618)
        self.centralwidget = QWidget(TicketOptionsCreation)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tandpinput = QLineEdit(self.centralwidget)
        self.tandpinput.setObjectName(u"tandpinput")
        self.tandpinput.setGeometry(QRect(20, 70, 121, 22))
        self.tandpnamelabel = QLabel(self.centralwidget)
        self.tandpnamelabel.setObjectName(u"tandpnamelabel")
        self.tandpnamelabel.setGeometry(QRect(20, 50, 49, 16))
        self.savetbutton = QPushButton(self.centralwidget)
        self.savetbutton.setObjectName(u"savetbutton")
        self.savetbutton.setGeometry(QRect(20, 240, 91, 24))
        self.savepbutton = QPushButton(self.centralwidget)
        self.savepbutton.setObjectName(u"savepbutton")
        self.savepbutton.setGeometry(QRect(120, 240, 81, 24))
        self.tlist = QListWidget(self.centralwidget)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(210, 60, 241, 251))
        self.savedtlabel = QLabel(self.centralwidget)
        self.savedtlabel.setObjectName(u"savedtlabel")
        self.savedtlabel.setGeometry(QRect(290, 40, 161, 16))
        self.saveubutton = QPushButton(self.centralwidget)
        self.saveubutton.setObjectName(u"saveubutton")
        self.saveubutton.setGeometry(QRect(30, 500, 101, 24))
        self.uinput = QLineEdit(self.centralwidget)
        self.uinput.setObjectName(u"uinput")
        self.uinput.setGeometry(QRect(30, 350, 113, 22))
        self.unamelabel = QLabel(self.centralwidget)
        self.unamelabel.setObjectName(u"unamelabel")
        self.unamelabel.setGeometry(QRect(30, 330, 49, 16))
        self.unamelabel.setStyleSheet(u"\n"
"font: 9pt \"Segoe UI\";")
        self.uamountinput = QLineEdit(self.centralwidget)
        self.uamountinput.setObjectName(u"uamountinput")
        self.uamountinput.setGeometry(QRect(30, 400, 61, 22))
        self.uamountlabel = QLabel(self.centralwidget)
        self.uamountlabel.setObjectName(u"uamountlabel")
        self.uamountlabel.setGeometry(QRect(30, 380, 49, 16))
        self.ulist = QListWidget(self.centralwidget)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(150, 340, 201, 192))
        self.dnamelabel = QLabel(self.centralwidget)
        self.dnamelabel.setObjectName(u"dnamelabel")
        self.dnamelabel.setGeometry(QRect(360, 330, 49, 16))
        self.dinput = QLineEdit(self.centralwidget)
        self.dinput.setObjectName(u"dinput")
        self.dinput.setGeometry(QRect(360, 350, 113, 22))
        self.savedbutton = QPushButton(self.centralwidget)
        self.savedbutton.setObjectName(u"savedbutton")
        self.savedbutton.setGeometry(QRect(360, 500, 101, 24))
        self.dpercentinput = QLineEdit(self.centralwidget)
        self.dpercentinput.setObjectName(u"dpercentinput")
        self.dpercentinput.setGeometry(QRect(360, 400, 71, 22))
        self.dpercentlabel = QLabel(self.centralwidget)
        self.dpercentlabel.setObjectName(u"dpercentlabel")
        self.dpercentlabel.setGeometry(QRect(360, 380, 49, 16))
        self.damountlabel = QLabel(self.centralwidget)
        self.damountlabel.setObjectName(u"damountlabel")
        self.damountlabel.setGeometry(QRect(360, 430, 71, 16))
        self.damountinput = QLineEdit(self.centralwidget)
        self.damountinput.setObjectName(u"damountinput")
        self.damountinput.setGeometry(QRect(360, 450, 71, 22))
        self.dlist = QListWidget(self.centralwidget)
        self.dlist.setObjectName(u"dlist")
        self.dlist.setGeometry(QRect(480, 340, 211, 192))
        self.plist = QListWidget(self.centralwidget)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(450, 60, 241, 251))
        self.savedplabel = QLabel(self.centralwidget)
        self.savedplabel.setObjectName(u"savedplabel")
        self.savedplabel.setGeometry(QRect(520, 40, 111, 16))
        TicketOptionsCreation.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TicketOptionsCreation)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 840, 33))
        TicketOptionsCreation.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TicketOptionsCreation)
        self.statusbar.setObjectName(u"statusbar")
        TicketOptionsCreation.setStatusBar(self.statusbar)

        self.retranslateUi(TicketOptionsCreation)

        QMetaObject.connectSlotsByName(TicketOptionsCreation)
    # setupUi

    def retranslateUi(self, TicketOptionsCreation):
        TicketOptionsCreation.setWindowTitle(QCoreApplication.translate("TicketOptionsCreation", u"MainWindow", None))
        self.tandpinput.setText("")
        self.tandpnamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name", None))
        self.savetbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Texture", None))
        self.savepbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Pattern", None))
        self.savedtlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Saved Textures ", None))
        self.saveubutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Upcharge", None))
        self.unamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name", None))
        self.uamountlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Amount", None))
        self.dnamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name", None))
        self.savedbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Discount", None))
        self.dpercentlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"%  Off", None))
        self.damountlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Amount Off", None))
        self.savedplabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Saved Patterns", None))
    # retranslateUi

class Ui_DetailedTicketCreation(object):
    def setupUi(self, DetailedTicketCreation):
        if not DetailedTicketCreation.objectName():
            DetailedTicketCreation.setObjectName(u"DetailedTicketCreation")
        DetailedTicketCreation.resize(1257, 773)
        self.plist = QListWidget(DetailedTicketCreation)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(1080, 120, 131, 191))
        self.clist = QListWidget(DetailedTicketCreation)
        self.clist.setObjectName(u"clist")
        self.clist.setGeometry(QRect(940, 120, 131, 191))
        self.ulist = QListWidget(DetailedTicketCreation)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(1080, 340, 131, 191))
        self.ulabel = QLabel(DetailedTicketCreation)
        self.ulabel.setObjectName(u"ulabel")
        self.ulabel.setGeometry(QRect(1090, 320, 61, 16))
        self.plabel = QLabel(DetailedTicketCreation)
        self.plabel.setObjectName(u"plabel")
        self.plabel.setGeometry(QRect(1090, 100, 71, 16))
        self.clabel = QLabel(DetailedTicketCreation)
        self.clabel.setObjectName(u"clabel")
        self.clabel.setGeometry(QRect(950, 100, 49, 16))
        self.glist = QListWidget(DetailedTicketCreation)
        self.glist.setObjectName(u"glist")
        self.glist.setGeometry(QRect(550, 121, 381, 621))
        self.tlist = QListWidget(DetailedTicketCreation)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(940, 340, 131, 191))
        self.tlabel = QLabel(DetailedTicketCreation)
        self.tlabel.setObjectName(u"tlabel")
        self.tlabel.setGeometry(QRect(950, 320, 61, 16))
        self.glabel = QLabel(DetailedTicketCreation)
        self.glabel.setObjectName(u"glabel")
        self.glabel.setGeometry(QRect(560, 100, 61, 16))
        self.piecesinput = QSpinBox(DetailedTicketCreation)
        self.piecesinput.setObjectName(u"piecesinput")
        self.piecesinput.setGeometry(QRect(1020, 610, 131, 61))
        self.pieceslabel = QLabel(DetailedTicketCreation)
        self.pieceslabel.setObjectName(u"pieceslabel")
        self.pieceslabel.setGeometry(QRect(1030, 590, 71, 16))
        self.ugbutton = QPushButton(DetailedTicketCreation)
        self.ugbutton.setObjectName(u"ugbutton")
        self.ugbutton.setGeometry(QRect(30, 370, 111, 24))
        self.egbutton = QPushButton(DetailedTicketCreation)
        self.egbutton.setObjectName(u"egbutton")
        self.egbutton.setGeometry(QRect(30, 330, 111, 24))
        self.dgbutton = QPushButton(DetailedTicketCreation)
        self.dgbutton.setObjectName(u"dgbutton")
        self.dgbutton.setGeometry(QRect(30, 460, 111, 24))
        self.canceltbutton = QPushButton(DetailedTicketCreation)
        self.canceltbutton.setObjectName(u"canceltbutton")
        self.canceltbutton.setGeometry(QRect(30, 720, 111, 24))
        self.ptbutton = QPushButton(DetailedTicketCreation)
        self.ptbutton.setObjectName(u"ptbutton")
        self.ptbutton.setGeometry(QRect(30, 590, 111, 24))
        self.ptandtbutton = QPushButton(DetailedTicketCreation)
        self.ptandtbutton.setObjectName(u"ptandtbutton")
        self.ptandtbutton.setGeometry(QRect(30, 550, 111, 24))
        self.tctabs = QTabWidget(DetailedTicketCreation)
        self.tctabs.setObjectName(u"tctabs")
        self.tctabs.setGeometry(QRect(160, 100, 391, 641))
        self.tctabs1 = QWidget()
        self.tctabs1.setObjectName(u"tctabs1")
        self.sglist = QTreeWidget(self.tctabs1)
        self.sglist.setObjectName(u"sglist")
        self.sglist.setGeometry(QRect(0, 30, 391, 621))
        self.sglist.header().setDefaultSectionSize(139)
        self.ttname = QTextBrowser(self.tctabs1)
        self.ttname.setObjectName(u"ttname")
        self.ttname.setGeometry(QRect(0, 0, 391, 31))
        self.tctabs.addTab(self.tctabs1, "")
        self.tctabs2 = QWidget()
        self.tctabs2.setObjectName(u"tctabs2")
        self.ttname_2 = QTextBrowser(self.tctabs2)
        self.ttname_2.setObjectName(u"ttname_2")
        self.ttname_2.setGeometry(QRect(0, 0, 391, 31))
        self.sglist_2 = QTreeWidget(self.tctabs2)
        self.sglist_2.setObjectName(u"sglist_2")
        self.sglist_2.setGeometry(QRect(0, 30, 391, 621))
        self.sglist_2.header().setDefaultSectionSize(139)
        self.tctabs.addTab(self.tctabs2, "")
        self.tctabs3 = QWidget()
        self.tctabs3.setObjectName(u"tctabs3")
        self.sglist_3 = QTreeWidget(self.tctabs3)
        self.sglist_3.setObjectName(u"sglist_3")
        self.sglist_3.setGeometry(QRect(0, 30, 391, 621))
        self.sglist_3.header().setDefaultSectionSize(139)
        self.ttname_3 = QTextBrowser(self.tctabs3)
        self.ttname_3.setObjectName(u"ttname_3")
        self.ttname_3.setGeometry(QRect(0, 0, 391, 31))
        self.tctabs.addTab(self.tctabs3, "")
        self.pushButton_7 = QPushButton(DetailedTicketCreation)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(30, 130, 111, 24))
        self.pushButton_8 = QPushButton(DetailedTicketCreation)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(30, 170, 111, 24))
        self.pushButton_9 = QPushButton(DetailedTicketCreation)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(30, 210, 111, 24))
        self.pushButton_10 = QPushButton(DetailedTicketCreation)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(30, 250, 111, 24))
        self.ctbutton = QPushButton(DetailedTicketCreation)
        self.ctbutton.setObjectName(u"ctbutton")
        self.ctbutton.setGeometry(QRect(30, 680, 111, 24))

        self.retranslateUi(DetailedTicketCreation)

        self.tctabs.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(DetailedTicketCreation)
    # setupUi

    def retranslateUi(self, DetailedTicketCreation):
        DetailedTicketCreation.setWindowTitle(QCoreApplication.translate("DetailedTicketCreation", u"Form", None))
        self.ulabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Upcharges", None))
        self.plabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Patterns", None))
        self.clabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Colors", None))
        self.tlabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Textures", None))
        self.glabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Garments", None))
        self.pieceslabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"# of Pieces", None))
        self.ugbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Update Garment", None))
        self.egbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Edit Garment", None))
        self.dgbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Delete Garment", None))
        self.canceltbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Cancel Ticket", None))
        self.ptbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Print Ticket", None))
        self.ptandtbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Print Ticket + Tags", None))
        ___qtreewidgetitem = self.sglist.headerItem()
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("DetailedTicketCreation", u"Price", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("DetailedTicketCreation", u"Garment Name", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("DetailedTicketCreation", u"# of Garments", None));
        self.ttname.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700;\">Dry Clean</span></p></body></html>", None))
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs1), QCoreApplication.translate("DetailedTicketCreation", u"Tab 1", None))
        self.ttname_2.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700;\">Laundry</span></p></body></html>", None))
        ___qtreewidgetitem1 = self.sglist_2.headerItem()
        ___qtreewidgetitem1.setText(2, QCoreApplication.translate("DetailedTicketCreation", u"Price", None));
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("DetailedTicketCreation", u"Garment Name", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("DetailedTicketCreation", u"# of Garments", None));
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs2), QCoreApplication.translate("DetailedTicketCreation", u"Tab 2", None))
        ___qtreewidgetitem2 = self.sglist_3.headerItem()
        ___qtreewidgetitem2.setText(2, QCoreApplication.translate("DetailedTicketCreation", u"Price", None));
        ___qtreewidgetitem2.setText(1, QCoreApplication.translate("DetailedTicketCreation", u"Garment Name", None));
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("DetailedTicketCreation", u"# of Garments", None));
        self.ttname_3.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700;\">Alteration</span></p></body></html>", None))
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs3), QCoreApplication.translate("DetailedTicketCreation", u"Page", None))
        self.pushButton_7.setText(QCoreApplication.translate("DetailedTicketCreation", u"Dry Clean", None))
        self.pushButton_8.setText(QCoreApplication.translate("DetailedTicketCreation", u"Laundry", None))
        self.pushButton_9.setText(QCoreApplication.translate("DetailedTicketCreation", u"Household", None))
        self.pushButton_10.setText(QCoreApplication.translate("DetailedTicketCreation", u"Alteration", None))
        self.ctbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Create Ticket", None))
    # retranslateUi

class Ui_QuickTicketCreation(object):
    def setupUi(self, QuickTicketCreation):
        if not QuickTicketCreation.objectName():
            QuickTicketCreation.setObjectName(u"QuickTicketCreation")
        QuickTicketCreation.resize(559, 381)
        self.ttlabel = QLabel(QuickTicketCreation)
        self.ttlabel.setObjectName(u"ttlabel")
        self.ttlabel.setGeometry(QRect(20, 20, 71, 16))
        self.qtdlabel = QLabel(QuickTicketCreation)
        self.qtdlabel.setObjectName(u"qtdlabel")
        self.qtdlabel.setGeometry(QRect(240, 20, 71, 16))
        self.qtdselection = QDateEdit(QuickTicketCreation)
        self.qtdselection.setObjectName(u"qtdselection")
        self.qtdselection.setGeometry(QRect(240, 40, 121, 22))
        self.qtdselection_2 = QDateEdit(QuickTicketCreation)
        self.qtdselection_2.setObjectName(u"qtdselection_2")
        self.qtdselection_2.setGeometry(QRect(240, 130, 121, 22))
        self.qtdselection_3 = QDateEdit(QuickTicketCreation)
        self.qtdselection_3.setObjectName(u"qtdselection_3")
        self.qtdselection_3.setGeometry(QRect(240, 220, 121, 22))
        self.ttselection = QComboBox(QuickTicketCreation)
        self.ttselection.setObjectName(u"ttselection")
        self.ttselection.setGeometry(QRect(20, 40, 111, 22))
        self.ttselection_2 = QComboBox(QuickTicketCreation)
        self.ttselection_2.setObjectName(u"ttselection_2")
        self.ttselection_2.setGeometry(QRect(20, 130, 111, 22))
        self.ttselection_3 = QComboBox(QuickTicketCreation)
        self.ttselection_3.setObjectName(u"ttselection_3")
        self.ttselection_3.setGeometry(QRect(20, 220, 111, 22))
        self.qtninput = QPlainTextEdit(QuickTicketCreation)
        self.qtninput.setObjectName(u"qtninput")
        self.qtninput.setGeometry(QRect(380, 40, 161, 61))
        self.qtninput_2 = QPlainTextEdit(QuickTicketCreation)
        self.qtninput_2.setObjectName(u"qtninput_2")
        self.qtninput_2.setGeometry(QRect(380, 130, 161, 61))
        self.qtninput_3 = QPlainTextEdit(QuickTicketCreation)
        self.qtninput_3.setObjectName(u"qtninput_3")
        self.qtninput_3.setGeometry(QRect(380, 220, 161, 61))
        self.qtnlabel = QLabel(QuickTicketCreation)
        self.qtnlabel.setObjectName(u"qtnlabel")
        self.qtnlabel.setGeometry(QRect(380, 20, 49, 16))
        self.ttlabel_2 = QLabel(QuickTicketCreation)
        self.ttlabel_2.setObjectName(u"ttlabel_2")
        self.ttlabel_2.setGeometry(QRect(20, 110, 71, 16))
        self.ttlabel_3 = QLabel(QuickTicketCreation)
        self.ttlabel_3.setObjectName(u"ttlabel_3")
        self.ttlabel_3.setGeometry(QRect(20, 200, 71, 16))
        self.qtdlabel_2 = QLabel(QuickTicketCreation)
        self.qtdlabel_2.setObjectName(u"qtdlabel_2")
        self.qtdlabel_2.setGeometry(QRect(240, 110, 71, 16))
        self.qtdlabel_3 = QLabel(QuickTicketCreation)
        self.qtdlabel_3.setObjectName(u"qtdlabel_3")
        self.qtdlabel_3.setGeometry(QRect(240, 200, 71, 16))
        self.qtnlabel_2 = QLabel(QuickTicketCreation)
        self.qtnlabel_2.setObjectName(u"qtnlabel_2")
        self.qtnlabel_2.setGeometry(QRect(380, 110, 49, 16))
        self.qtnlabel_3 = QLabel(QuickTicketCreation)
        self.qtnlabel_3.setObjectName(u"qtnlabel_3")
        self.qtnlabel_3.setGeometry(QRect(380, 200, 49, 16))
        self.qtclosebutton = QPushButton(QuickTicketCreation)
        self.qtclosebutton.setObjectName(u"qtclosebutton")
        self.qtclosebutton.setGeometry(QRect(320, 310, 101, 24))
        self.qtsandpbutton = QPushButton(QuickTicketCreation)
        self.qtsandpbutton.setObjectName(u"qtsandpbutton")
        self.qtsandpbutton.setGeometry(QRect(440, 310, 101, 24))
        self.atninput = QPlainTextEdit(QuickTicketCreation)
        self.atninput.setObjectName(u"atninput")
        self.atninput.setGeometry(QRect(20, 290, 291, 71))
        self.atnlabel = QLabel(QuickTicketCreation)
        self.atnlabel.setObjectName(u"atnlabel")
        self.atnlabel.setGeometry(QRect(20, 270, 111, 16))
        self.qtpselection_2 = QSpinBox(QuickTicketCreation)
        self.qtpselection_2.setObjectName(u"qtpselection_2")
        self.qtpselection_2.setGeometry(QRect(160, 130, 88, 22))
        self.qtpselection_3 = QSpinBox(QuickTicketCreation)
        self.qtpselection_3.setObjectName(u"qtpselection_3")
        self.qtpselection_3.setGeometry(QRect(160, 220, 88, 22))
        self.qtpselection = QSpinBox(QuickTicketCreation)
        self.qtpselection.setObjectName(u"qtpselection")
        self.qtpselection.setGeometry(QRect(160, 40, 88, 22))
        self.qtplabel_3 = QLabel(QuickTicketCreation)
        self.qtplabel_3.setObjectName(u"qtplabel_3")
        self.qtplabel_3.setGeometry(QRect(160, 200, 49, 16))
        self.qtplabel_2 = QLabel(QuickTicketCreation)
        self.qtplabel_2.setObjectName(u"qtplabel_2")
        self.qtplabel_2.setGeometry(QRect(160, 110, 49, 16))
        self.qtplabel = QLabel(QuickTicketCreation)
        self.qtplabel.setObjectName(u"qtplabel")
        self.qtplabel.setGeometry(QRect(160, 20, 49, 16))

        self.retranslateUi(QuickTicketCreation)

        QMetaObject.connectSlotsByName(QuickTicketCreation)
    # setupUi

    def retranslateUi(self, QuickTicketCreation):
        QuickTicketCreation.setWindowTitle(QCoreApplication.translate("QuickTicketCreation", u"Form", None))
        self.ttlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.qtdlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Date", None))
        self.qtnlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.ttlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.ttlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.qtdlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Date", None))
        self.qtdlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Date", None))
        self.qtnlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.qtnlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.qtclosebutton.setText(QCoreApplication.translate("QuickTicketCreation", u"Close", None))
        self.qtsandpbutton.setText(QCoreApplication.translate("QuickTicketCreation", u"Save + Print", None))
        self.atnlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes For All Tickets", None))
        self.qtplabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
        self.qtplabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
        self.qtplabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
    # retranslateUi

class Ui_TicketTypeCreation(object):
    def setupUi(self, TicketTypeCreation):
        if not TicketTypeCreation.objectName():
            TicketTypeCreation.setObjectName(u"TicketTypeCreation")
        TicketTypeCreation.resize(1196, 883)
        self.dlist = QListWidget(TicketTypeCreation)
        self.dlist.setObjectName(u"dlist")
        self.dlist.setGeometry(QRect(290, 150, 131, 192))
        self.ulist = QListWidget(TicketTypeCreation)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(290, 370, 131, 192))
        self.tlist = QListWidget(TicketTypeCreation)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(290, 590, 131, 192))
        self.plist = QListWidget(TicketTypeCreation)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(150, 590, 131, 192))
        self.clist = QListWidget(TicketTypeCreation)
        self.clist.setObjectName(u"clist")
        self.clist.setGeometry(QRect(10, 590, 131, 192))
        self.glist = QListWidget(TicketTypeCreation)
        self.glist.setObjectName(u"glist")
        self.glist.setGeometry(QRect(10, 151, 271, 411))
        self.glabel = QLabel(TicketTypeCreation)
        self.glabel.setObjectName(u"glabel")
        self.glabel.setGeometry(QRect(20, 130, 61, 16))
        self.plabel = QLabel(TicketTypeCreation)
        self.plabel.setObjectName(u"plabel")
        self.plabel.setGeometry(QRect(150, 570, 71, 16))
        self.tlabel = QLabel(TicketTypeCreation)
        self.tlabel.setObjectName(u"tlabel")
        self.tlabel.setGeometry(QRect(290, 570, 61, 16))
        self.ulabel = QLabel(TicketTypeCreation)
        self.ulabel.setObjectName(u"ulabel")
        self.ulabel.setGeometry(QRect(290, 350, 61, 16))
        self.clabel = QLabel(TicketTypeCreation)
        self.clabel.setObjectName(u"clabel")
        self.clabel.setGeometry(QRect(10, 570, 49, 16))
        self.ttinput = QLineEdit(TicketTypeCreation)
        self.ttinput.setObjectName(u"ttinput")
        self.ttinput.setGeometry(QRect(500, 80, 113, 22))
        self.ttlabel = QLabel(TicketTypeCreation)
        self.ttlabel.setObjectName(u"ttlabel")
        self.ttlabel.setGeometry(QRect(520, 60, 71, 16))
        self.dlabel = QLabel(TicketTypeCreation)
        self.dlabel.setObjectName(u"dlabel")
        self.dlabel.setGeometry(QRect(290, 130, 61, 16))
        self.cglist = QListWidget(TicketTypeCreation)
        self.cglist.setObjectName(u"cglist")
        self.cglist.setGeometry(QRect(450, 150, 271, 371))
        self.cpandtlist = QTreeWidget(TicketTypeCreation)
        self.cpandtlist.setObjectName(u"cpandtlist")
        self.cpandtlist.setGeometry(QRect(730, 150, 461, 291))
        self.cpandtlist.header().setDefaultSectionSize(229)
        self.cpandtlist.header().setStretchLastSection(False)
        self.cuanddlist = QTreeWidget(TicketTypeCreation)
        self.cuanddlist.setObjectName(u"cuanddlist")
        self.cuanddlist.setGeometry(QRect(730, 450, 461, 291))
        self.cuanddlist.setLineWidth(1)
        self.cuanddlist.setUniformRowHeights(True)
        self.cuanddlist.header().setCascadingSectionResizes(False)
        self.cuanddlist.header().setDefaultSectionSize(229)
        self.cuanddlist.header().setHighlightSections(True)
        self.cuanddlist.header().setProperty("showSortIndicator", False)
        self.cuanddlist.header().setStretchLastSection(False)
        self.cclist = QListWidget(TicketTypeCreation)
        self.cclist.setObjectName(u"cclist")
        self.cclist.setGeometry(QRect(450, 550, 271, 141))
        self.cclabel = QLabel(TicketTypeCreation)
        self.cclabel.setObjectName(u"cclabel")
        self.cclabel.setGeometry(QRect(450, 530, 81, 16))
        self.cglabel = QLabel(TicketTypeCreation)
        self.cglabel.setObjectName(u"cglabel")
        self.cglabel.setGeometry(QRect(450, 130, 111, 16))
        self.savettbutton = QPushButton(TicketTypeCreation)
        self.savettbutton.setObjectName(u"savettbutton")
        self.savettbutton.setGeometry(QRect(150, 820, 131, 24))
        self.editttbutton = QPushButton(TicketTypeCreation)
        self.editttbutton.setObjectName(u"editttbutton")
        self.editttbutton.setGeometry(QRect(810, 810, 111, 24))
        self.deletettbutton = QPushButton(TicketTypeCreation)
        self.deletettbutton.setObjectName(u"deletettbutton")
        self.deletettbutton.setGeometry(QRect(1000, 810, 111, 24))
        self.sttlist = QListWidget(TicketTypeCreation)
        self.sttlist.setObjectName(u"sttlist")
        self.sttlist.setGeometry(QRect(450, 720, 271, 161))
        self.sttlabel = QLabel(TicketTypeCreation)
        self.sttlabel.setObjectName(u"sttlabel")
        self.sttlabel.setGeometry(QRect(450, 700, 101, 16))

        self.retranslateUi(TicketTypeCreation)

        QMetaObject.connectSlotsByName(TicketTypeCreation)
    # setupUi

    def retranslateUi(self, TicketTypeCreation):
        TicketTypeCreation.setWindowTitle(QCoreApplication.translate("TicketTypeCreation", u"Form", None))
        self.glabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Garments", None))
        self.plabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Patterns", None))
        self.tlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Textures", None))
        self.ulabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Upcharges", None))
        self.clabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Colors", None))
        self.ttlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Ticket Type", None))
        self.dlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Discounts", None))
        ___qtreewidgetitem = self.cpandtlist.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("TicketTypeCreation", u"Chosen Textures", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("TicketTypeCreation", u"Chosen Patterns", None));
        ___qtreewidgetitem1 = self.cuanddlist.headerItem()
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("TicketTypeCreation", u"Chosen Discounts", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("TicketTypeCreation", u"Chosen Upcharges", None));
        self.cclabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Colors", None))
        self.cglabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Garments", None))
        self.savettbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Save Ticket Type", None))
        self.editttbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Edit Ticket Type", None))
        self.deletettbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Delete Ticket Type", None))
        self.sttlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Saved Ticket Types", None))
    # retranslateUi

class SearchWindow(QMainWindow):
    customer_selected = Signal(int)

    def __init__(self):
        super().__init__()
        self.ui = Ui_CustomerSearch()
        self.ui.setupUi(self)
        self.ui.ncbutton.clicked.connect(self.create_new_customer)
        self.ui.searchbutton.clicked.connect(self.search_customers)
        self.ui.closebutton.clicked.connect(self.close)
        self.customer_windows = []

    def create_new_customer(self):
        self.customer_selected.emit(None)
        self.close()

    def search_customers(self):
        last_name = self.ui.lnsearch.text()
        first_name = self.ui.fnsearch.text()
        phone_number = self.ui.pnsearch.text()

        conn = sqlite3.connect("pos_system.db")
        cursor = conn.cursor()

        query = """
        SELECT id, first_name, last_name, phone_number FROM customers 
        WHERE last_name LIKE ? OR first_name LIKE ? OR phone_number LIKE ?
        """
        cursor.execute(query, ('%' + last_name + '%', '%' + first_name + '%', '%' + phone_number + '%'))
        results = cursor.fetchall()
        conn.close()

        self.ui.resultslist.clear()
        for result in results:
            item = QTreeWidgetItem(self.ui.resultslist)
            item.setText(0, f"{result[1]} {result[2]}")
            item.setText(1, result[3])
            item.setData(0, Qt.UserRole, result[0])
            self.ui.resultslist.addTopLevelItem(item)

        self.ui.resultslist.itemDoubleClicked.connect(self.select_customer)

    def select_customer(self, item):
        customer_id = item.data(0, Qt.UserRole)
        self.customer_selected.emit(customer_id)
        self.close()

class CustomerAccountWindow(QMainWindow):
    def __init__(self, customer_id=None):
        super().__init__()

        self.customer_tabs = QTabWidget()
        self.setCentralWidget(self.customer_tabs)
        self.search_window = None

        self.init_ui()

        if customer_id is not None:
            self.load_customer_tab(customer_id)
        else:
            self.add_new_tab_button()

    def init_ui(self):
        self.add_new_tab_button()
        self.customer_tabs.tabBarDoubleClicked.connect(self.open_search_window)

    def add_new_tab_button(self):
        new_tab_button = QPushButton("New Customer")
        new_tab_button.clicked.connect(self.open_search_window)
        new_tab = QWidget()
        layout = QVBoxLayout()
        layout.addWidget(new_tab_button)
        new_tab.setLayout(layout)
        self.customer_tabs.addTab(new_tab, "New Customer")

    def open_search_window(self):
        if not self.search_window:
            self.search_window = SearchWindow()
            self.search_window.customer_selected.connect(self.load_customer_tab)
        self.search_window.show()

    def load_customer_tab(self, customer_id):
        customer_account_widget = CustomerAccountWidget(customer_id)
        tab_index = self.customer_tabs.addTab(customer_account_widget, f"Customer {customer_id if customer_id else 'New'}")
        self.customer_tabs.setCurrentIndex(tab_index)

class CustomerAccountWidget(QWidget):
    def __init__(self, customer_id=None):
        super().__init__()
        self.ui = Ui_CustomerAccount()
        self.ui.setupUi(self)

        self.customer_id = customer_id
        self.inputs = [self.ui.lninput, self.ui.fninput, self.ui.pninput, self.ui.ninput]
        for input_field in self.inputs:
            input_field.focusOutEvent = self.save_customer_info

        if customer_id:
            self.load_customer_info()
        else:
            self.create_new_customer()

    def create_new_customer(self):
        conn = sqlite3.connect("pos_system.db")
        cursor = conn.cursor()
        cursor.execute("INSERT INTO customers (first_name, last_name, phone_number, notes) VALUES (?, ?, ?, ?)",
                       ("", "", "", ""))
        conn.commit()
        self.customer_id = cursor.lastrowid
        conn.close()

    def load_customer_info(self):
        conn = sqlite3.connect("pos_system.db")
        cursor = conn.cursor()
        cursor.execute("SELECT first_name, last_name, phone_number, notes FROM customers WHERE id = ?", (self.customer_id,))
        result = cursor.fetchone()
        conn.close()
        if result:
            self.ui.fninput.setText(result[0])
            self.ui.lninput.setText(result[1])
            self.ui.pninput.setText(result[2])
            self.ui.ninput.setPlainText(result[3])

    def save_customer_info(self, event):
        conn = sqlite3.connect("pos_system.db")
        cursor = conn.cursor()
        cursor.execute("""
        UPDATE customers SET first_name = ?, last_name = ?, phone_number = ?, notes = ? WHERE id = ?
        """, (self.ui.fninput.text(), self.ui.lninput.text(), self.ui.pninput.text(), self.ui.ninput.toPlainText(), self.customer_id))
        conn.commit()
        conn.close()
        QLineEdit.focusOutEvent(self.ui.fninput, event)
        QTextEdit.focusOutEvent(self.ui.ninput, event)
        QLineEdit.focusOutEvent(self.ui.lninput, event)
        QLineEdit.focusOutEvent(self.ui.pninput, event)

