from PySide6.QtCore import (QCoreApplication, QLocale,
    QMetaObject, QRect,
    Qt)
from PySide6.QtGui import (QBrush, QColor, QPalette)
from PySide6.QtWidgets import (QAbstractItemView, QComboBox, QFrame,
    QGroupBox, QLabel, QLineEdit, QListView,
    QPushButton, QRadioButton)

class Ui_cashpayment(object):
    def setupUi(self, cashpayment):
        if not cashpayment.objectName():
            cashpayment.setObjectName(u"cashpayment")
        cashpayment.resize(590, 320)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        cashpayment.setPalette(palette)
        self.groupBox_2 = QGroupBox(cashpayment)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 0, 131, 321))
        self.groupBox_2.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.groupBox_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.radioButton = QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(10, 30, 101, 20))
        self.radioButton.setChecked(True)
        self.radioButton_2 = QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(10, 80, 101, 20))
        self.radioButton_3 = QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(10, 130, 101, 20))
        self.radioButton_4 = QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(10, 180, 101, 20))
        self.radioButton_5 = QRadioButton(self.groupBox_2)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(10, 230, 101, 20))
        self.radioButton_6 = QRadioButton(self.groupBox_2)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(10, 280, 101, 20))
        self.frame = QFrame(cashpayment)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(250, 10, 341, 311))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.lineEdit = QLineEdit(self.frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 30, 61, 22))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(90, 30, 51, 20))
        self.lineEdit_2 = QLineEdit(self.frame)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(110, 30, 61, 22))
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 10, 61, 16))
        self.label_2.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(120, 10, 49, 16))
        self.label_4.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(190, 180, 49, 16))
        self.label_7.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.lineEdit_3 = QLineEdit(self.frame)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(70, 110, 61, 22))
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(140, 110, 49, 16))
        self.lineEdit_4 = QLineEdit(self.frame)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(160, 110, 61, 22))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(170, 90, 49, 16))
        self.label_3.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.lineEdit_5 = QLineEdit(self.frame)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(210, 180, 113, 22))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(240, 160, 61, 16))
        self.label_5.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.comboBox = QComboBox(self.frame)
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(250, 30, 69, 22))
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(260, 10, 49, 16))
        self.label_10.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 260, 101, 24))
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(230, 260, 101, 24))
        self.pushButton_3 = QPushButton(self.frame)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(120, 260, 101, 24))
        self.lineEdit_6 = QLineEdit(self.frame)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(10, 230, 91, 22))
        self.label_13 = QLabel(self.frame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 210, 51, 16))
        self.label_13.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.label_14 = QLabel(self.frame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(110, 230, 49, 16))
        self.lineEdit_7 = QLineEdit(self.frame)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(130, 230, 91, 22))
        self.label_15 = QLabel(self.frame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(130, 210, 61, 16))
        self.label_15.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.label_16 = QLabel(self.frame)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(50, 110, 49, 16))
        self.label_16.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(230, 230, 49, 16))
        self.label_9.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.lineEdit_8 = QLineEdit(self.frame)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(250, 230, 81, 22))
        self.label_17 = QLabel(self.frame)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(250, 210, 61, 16))
        self.label_17.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.groupBox = QGroupBox(cashpayment)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(130, 0, 121, 321))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.groupBox.setPalette(palette1)
        self.groupBox.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.groupBox.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)
        self.groupBox.setFlat(False)
        self.listView = QListView(self.groupBox)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(0, 10, 121, 311))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush8 = QBrush(QColor(170, 85, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush8)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        brush9 = QBrush(QColor(169, 77, 193, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        brush10 = QBrush(QColor(64, 14, 89, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        self.listView.setPalette(palette2)
        self.listView.setTabletTracking(False)
        self.listView.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.listView.setAutoFillBackground(True)
        self.listView.setLocale(QLocale(QLocale.English, QLocale.World))
        self.listView.setFrameShape(QFrame.Shape.StyledPanel)
        self.listView.setFrameShadow(QFrame.Shadow.Plain)
        self.listView.setLineWidth(9)
        self.listView.setMidLineWidth(0)
        self.listView.setTabKeyNavigation(True)
        self.listView.setProperty(u"showDropIndicator", False)
        self.listView.setDragDropMode(QAbstractItemView.DragDropMode.InternalMove)
        self.listView.setAlternatingRowColors(True)
        self.listView.setModelColumn(0)
        self.listView.setUniformItemSizes(True)
        self.listView.setItemAlignment(Qt.AlignmentFlag.AlignLeading)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 71, 16))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 50, 71, 16))
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 70, 71, 16))

        self.retranslateUi(cashpayment)

        QMetaObject.connectSlotsByName(cashpayment)
    # setupUi

    def retranslateUi(self, cashpayment):
        cashpayment.setWindowTitle(QCoreApplication.translate("cashpayment", u"Form", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("cashpayment", u"Payment Methods", None))
        self.radioButton.setText(QCoreApplication.translate("cashpayment", u"  Cash", None))
        self.radioButton_2.setText(QCoreApplication.translate("cashpayment", u"  Credit Card", None))
        self.radioButton_3.setText(QCoreApplication.translate("cashpayment", u"  Debit Card", None))
        self.radioButton_4.setText(QCoreApplication.translate("cashpayment", u"  Check", None))
        self.radioButton_5.setText(QCoreApplication.translate("cashpayment", u"  Other", None))
        self.radioButton_6.setText(QCoreApplication.translate("cashpayment", u"Unable To Pay", None))
        self.label_6.setText(QCoreApplication.translate("cashpayment", u"+", None))
        self.label_2.setText(QCoreApplication.translate("cashpayment", u"Initial Cost", None))
        self.label_4.setText(QCoreApplication.translate("cashpayment", u"Taxes", None))
        self.label_7.setText(QCoreApplication.translate("cashpayment", u"=", None))
        self.label_8.setText(QCoreApplication.translate("cashpayment", u"-", None))
        self.label_3.setText(QCoreApplication.translate("cashpayment", u"Discount", None))
        self.label_5.setText(QCoreApplication.translate("cashpayment", u"Total Cost", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("cashpayment", u"5$ Off", None))

        self.label_10.setText(QCoreApplication.translate("cashpayment", u"Coupons", None))
        self.pushButton.setText(QCoreApplication.translate("cashpayment", u"Clear", None))
        self.pushButton_2.setText(QCoreApplication.translate("cashpayment", u"Pay", None))
        self.pushButton_3.setText(QCoreApplication.translate("cashpayment", u"Cancel + Close", None))
        self.label_13.setText(QCoreApplication.translate("cashpayment", u"Cash Paid", None))
        self.label_14.setText(QCoreApplication.translate("cashpayment", u"-", None))
        self.label_15.setText(QCoreApplication.translate("cashpayment", u"Total Cost", None))
        self.label_16.setText(QCoreApplication.translate("cashpayment", u"=", None))
        self.label_9.setText(QCoreApplication.translate("cashpayment", u"=", None))
        self.label_17.setText(QCoreApplication.translate("cashpayment", u"Change", None))
        self.groupBox.setTitle(QCoreApplication.translate("cashpayment", u"Orders Being Paid", None))
        self.label.setText(QCoreApplication.translate("cashpayment", u"#475892 - $15.75", None))
        self.label_11.setText(QCoreApplication.translate("cashpayment", u"#475893 - $ 9.50", None))
        self.label_12.setText(QCoreApplication.translate("cashpayment", u"#475894 - $23.25", None))
    # retranslateUi

