from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, Qt)
from PySide6.QtGui import (QBrush, QColor, QPalette)
from PySide6.QtWidgets import (QLabel, QLineEdit, QPushButton,
    QTreeWidget)


class Ui_CustomerSearch(object):
    def setupUi(self, CustomerSearch):
        if not CustomerSearch.objectName():
            CustomerSearch.setObjectName(u"CustomerSearch")
        CustomerSearch.resize(563, 347)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        CustomerSearch.setPalette(palette)
        self.searchinput = QLineEdit(CustomerSearch)
        self.searchinput.setObjectName(u"searchinput")
        self.searchinput.setGeometry(QRect(30, 120, 113, 22))
        self.searchinput.setAcceptDrops(False)
        self.searchinputlabel = QLabel(CustomerSearch)
        self.searchinputlabel.setObjectName(u"searchinputlabel")
        self.searchinputlabel.setGeometry(QRect(40, 100, 81, 16))
        self.resultslist = QTreeWidget(CustomerSearch)
        self.resultslist.setObjectName(u"resultslist")
        self.resultslist.setGeometry(QRect(160, 40, 361, 211))
        self.ncbutton = QPushButton(CustomerSearch)
        self.ncbutton.setObjectName(u"ncbutton")
        self.ncbutton.setGeometry(QRect(40, 270, 101, 31))
        self.searchbutton = QPushButton(CustomerSearch)
        self.searchbutton.setObjectName(u"searchbutton")
        self.searchbutton.setGeometry(QRect(300, 270, 91, 31))
        self.closebutton = QPushButton(CustomerSearch)
        self.closebutton.setObjectName(u"closebutton")
        self.closebutton.setGeometry(QRect(430, 270, 91, 31))
        self.clearresultsbutton = QPushButton(CustomerSearch)
        self.clearresultsbutton.setObjectName(u"clearresultsbutton")
        self.clearresultsbutton.setGeometry(QRect(170, 270, 101, 31))

        self.retranslateUi(CustomerSearch)

        QMetaObject.connectSlotsByName(CustomerSearch)
    # setupUi

    def retranslateUi(self, CustomerSearch):
        CustomerSearch.setWindowTitle(QCoreApplication.translate("CustomerSearch", u"Dialog", None))
        self.searchinputlabel.setText(QCoreApplication.translate("CustomerSearch", u"Search Input", None))
        ___qtreewidgetitem = self.resultslist.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("CustomerSearch", u"Phone#", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("CustomerSearch", u"Name                                                                                                        ", None));
        self.ncbutton.setText(QCoreApplication.translate("CustomerSearch", u"New Customer", None))
        self.searchbutton.setText(QCoreApplication.translate("CustomerSearch", u"Search", None))
        self.closebutton.setText(QCoreApplication.translate("CustomerSearch", u"Close", None))
        self.clearresultsbutton.setText(QCoreApplication.translate("CustomerSearch", u"Clear Results", None))
    # retranslateUi