from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect,
    QSize, Qt)
from PySide6.QtGui import (QBrush, QColor, QFont, QIcon,
    QPalette, QPixmap)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QCommandLinkButton,
    QFrame, QGridLayout, QLabel,
    QLayout, QLineEdit, QPlainTextEdit,
    QPushButton, QSizePolicy, QStackedWidget, QTabWidget,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_CustomerAccount2(object):
    def setupUi(self, CustomerAccount2):
        if not CustomerAccount2.objectName():
            CustomerAccount2.setObjectName(u"CustomerAccount2")
        CustomerAccount2.resize(1931, 1076)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        CustomerAccount2.setPalette(palette)
        self.centralwidget = QWidget(CustomerAccount2)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pageswidget = QStackedWidget(self.centralwidget)
        self.pageswidget.setObjectName(u"pageswidget")
        self.pageswidget.setGeometry(QRect(1, 0, 1920, 1080))
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.puandpbutton = QPushButton(self.page1)
        self.puandpbutton.setObjectName(u"puandpbutton")
        self.puandpbutton.setGeometry(QRect(315, 850, 147, 51))
        self.paybutton = QPushButton(self.page1)
        self.paybutton.setObjectName(u"paybutton")
        self.paybutton.setGeometry(QRect(160, 850, 147, 51))
        self.qtbutton = QPushButton(self.page1)
        self.qtbutton.setObjectName(u"qtbutton")
        self.qtbutton.setGeometry(QRect(3, 850, 147, 51))
        self.tabWidget = QTabWidget(self.page1)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(2, 30, 461, 382))
        self.tab1 = QWidget()
        self.tab1.setObjectName(u"tab1")
        self.FirstName = QLabel(self.tab1)
        self.FirstName.setObjectName(u"FirstName")
        self.FirstName.setGeometry(QRect(265, 22, 71, 16))
        self.PhoneNumber = QLabel(self.tab1)
        self.PhoneNumber.setObjectName(u"PhoneNumber")
        self.PhoneNumber.setGeometry(QRect(185, 92, 81, 16))
        self.LastNameInput = QLineEdit(self.tab1)
        self.LastNameInput.setObjectName(u"LastNameInput")
        self.LastNameInput.setGeometry(QRect(75, 52, 141, 31))
        self.NotesInput = QPlainTextEdit(self.tab1)
        self.NotesInput.setObjectName(u"NotesInput")
        self.NotesInput.setGeometry(QRect(75, 202, 301, 131))
        self.PhoneNumberInput = QLineEdit(self.tab1)
        self.PhoneNumberInput.setObjectName(u"PhoneNumberInput")
        self.PhoneNumberInput.setGeometry(QRect(125, 122, 201, 31))
        self.LastName = QLabel(self.tab1)
        self.LastName.setObjectName(u"LastName")
        self.LastName.setGeometry(QRect(75, 22, 61, 16))
        self.FirstNameInput = QLineEdit(self.tab1)
        self.FirstNameInput.setObjectName(u"FirstNameInput")
        self.FirstNameInput.setGeometry(QRect(257, 52, 121, 31))
        self.Notes = QLabel(self.tab1)
        self.Notes.setObjectName(u"Notes")
        self.Notes.setGeometry(QRect(215, 172, 49, 16))
        self.label_2 = QLabel(self.tab1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(49, 93, 70, 98))
        self.label_2.setPixmap(QPixmap(u":/images/hangerleft.png"))
        self.label_2.setScaledContents(True)
        self.label = QLabel(self.tab1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(332, 92, 75, 100))
        self.label.setPixmap(QPixmap(u":/images/hangeronlyright.png"))
        self.label.setScaledContents(True)
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.Notes_3 = QLabel(self.tab_2)
        self.Notes_3.setObjectName(u"Notes_3")
        self.Notes_3.setGeometry(QRect(215, 172, 49, 16))
        self.LastName_3 = QLabel(self.tab_2)
        self.LastName_3.setObjectName(u"LastName_3")
        self.LastName_3.setGeometry(QRect(75, 22, 61, 16))
        self.FirstName_3 = QLabel(self.tab_2)
        self.FirstName_3.setObjectName(u"FirstName_3")
        self.FirstName_3.setGeometry(QRect(265, 22, 71, 16))
        self.NotesInput_3 = QPlainTextEdit(self.tab_2)
        self.NotesInput_3.setObjectName(u"NotesInput_3")
        self.NotesInput_3.setGeometry(QRect(75, 202, 301, 131))
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(49, 93, 70, 98))
        self.label_7.setPixmap(QPixmap(u":/images/hangerleft.png"))
        self.label_7.setScaledContents(True)
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(332, 92, 75, 100))
        self.label_9.setPixmap(QPixmap(u":/images/hangeronlyright.png"))
        self.label_9.setScaledContents(True)
        self.LastNameInput_3 = QLineEdit(self.tab_2)
        self.LastNameInput_3.setObjectName(u"LastNameInput_3")
        self.LastNameInput_3.setGeometry(QRect(75, 52, 141, 31))
        self.PhoneNumberInput_3 = QLineEdit(self.tab_2)
        self.PhoneNumberInput_3.setObjectName(u"PhoneNumberInput_3")
        self.PhoneNumberInput_3.setGeometry(QRect(125, 122, 201, 31))
        self.PhoneNumber_3 = QLabel(self.tab_2)
        self.PhoneNumber_3.setObjectName(u"PhoneNumber_3")
        self.PhoneNumber_3.setGeometry(QRect(185, 92, 81, 16))
        self.FirstNameInput_3 = QLineEdit(self.tab_2)
        self.FirstNameInput_3.setObjectName(u"FirstNameInput_3")
        self.FirstNameInput_3.setGeometry(QRect(257, 52, 121, 31))
        self.tabWidget.addTab(self.tab_2, "")
        self.label_17 = QLabel(self.page1)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(120, 0, 49, 16))
        self.ncbutton = QPushButton(self.page1)
        self.ncbutton.setObjectName(u"ncbutton")
        self.ncbutton.setGeometry(QRect(3, 490, 147, 51))
        self.pushButton_16 = QPushButton(self.page1)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(1600, 49, 178, 71))
        self.gridLayoutWidget_2 = QWidget(self.page1)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(3, 551, 456, 292))
        self.tickettypebuttongrid = QGridLayout(self.gridLayoutWidget_2)
        self.tickettypebuttongrid.setObjectName(u"tickettypebuttongrid")
        self.tickettypebuttongrid.setContentsMargins(0, 0, 0, 0)
        self.ctlist = QTableWidget(self.page1)
        if (self.ctlist.columnCount() < 8):
            self.ctlist.setColumnCount(8)
        icon = QIcon()
        icon.addFile(u":/images/Logo2.jpg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setIcon(icon);
        self.ctlist.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.ctlist.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.ctlist.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.ctlist.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.ctlist.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.ctlist.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.ctlist.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        font = QFont()
        font.setBold(False)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setFont(font);
        self.ctlist.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        self.ctlist.setObjectName(u"ctlist")
        self.ctlist.setGeometry(QRect(464, 46, 995, 1040))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlist.sizePolicy().hasHeightForWidth())
        self.ctlist.setSizePolicy(sizePolicy)
        self.ctlist.setAutoFillBackground(False)
        self.ctlist.setFrameShape(QFrame.Shape.StyledPanel)
        self.ctlist.setFrameShadow(QFrame.Shadow.Sunken)
        self.ctlist.setLineWidth(0)
        self.ctlist.setMidLineWidth(0)
        self.ctlist.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.ctlist.setIconSize(QSize(50, 50))
        self.ctlist.setShowGrid(False)
        self.ctlist.setSortingEnabled(True)
        self.ctlist.horizontalHeader().setCascadingSectionResizes(False)
        self.ctlist.horizontalHeader().setDefaultSectionSize(124)
        self.ctlist.horizontalHeader().setProperty(u"showSortIndicator", True)
        self.ctlist.horizontalHeader().setStretchLastSection(True)
        self.ctlist.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.ctlist.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.changetodetailedticket_2 = QPushButton(self.page1)
        self.changetodetailedticket_2.setObjectName(u"changetodetailedticket_2")
        self.changetodetailedticket_2.setGeometry(QRect(1600, 137, 178, 71))
        self.totalowed = QLineEdit(self.page1)
        self.totalowed.setObjectName(u"totalowed")
        self.totalowed.setGeometry(QRect(233, 507, 161, 31))
        self.totalowed.setReadOnly(True)
        self.totalowedlabel = QLabel(self.page1)
        self.totalowedlabel.setObjectName(u"totalowedlabel")
        self.totalowedlabel.setGeometry(QRect(259, 491, 111, 16))
        self.label_4 = QLabel(self.page1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(1510, 817, 465, 287))
        self.label_4.setPixmap(QPixmap(u":/images/Logo2.jpg"))
        self.label_4.setScaledContents(True)
        self.more_info_button_2 = QCommandLinkButton(self.page1)
        self.more_info_button_2.setObjectName(u"more_info_button_2")
        self.more_info_button_2.setGeometry(QRect(148, 428, 172, 41))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DialogInformation))
        self.more_info_button_2.setIcon(icon1)
        self.more_info_button_2.setIconSize(QSize(25, 23))
        self.pageswidget.addWidget(self.page1)
        self.puandpbutton.raise_()
        self.paybutton.raise_()
        self.qtbutton.raise_()
        self.tabWidget.raise_()
        self.label_17.raise_()
        self.ncbutton.raise_()
        self.pushButton_16.raise_()
        self.gridLayoutWidget_2.raise_()
        self.changetodetailedticket_2.raise_()
        self.totalowed.raise_()
        self.totalowedlabel.raise_()
        self.ctlist.raise_()
        self.label_4.raise_()
        self.more_info_button_2.raise_()
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.tabWidget_2 = QTabWidget(self.page_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(2, 30, 461, 382))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.FirstName_2 = QLabel(self.tab_3)
        self.FirstName_2.setObjectName(u"FirstName_2")
        self.FirstName_2.setGeometry(QRect(265, 22, 71, 16))
        self.PhoneNumber_2 = QLabel(self.tab_3)
        self.PhoneNumber_2.setObjectName(u"PhoneNumber_2")
        self.PhoneNumber_2.setGeometry(QRect(185, 92, 81, 16))
        self.LastNameInput_2 = QLineEdit(self.tab_3)
        self.LastNameInput_2.setObjectName(u"LastNameInput_2")
        self.LastNameInput_2.setGeometry(QRect(75, 52, 141, 31))
        self.NotesInput_2 = QPlainTextEdit(self.tab_3)
        self.NotesInput_2.setObjectName(u"NotesInput_2")
        self.NotesInput_2.setGeometry(QRect(75, 202, 301, 131))
        self.PhoneNumberInput_2 = QLineEdit(self.tab_3)
        self.PhoneNumberInput_2.setObjectName(u"PhoneNumberInput_2")
        self.PhoneNumberInput_2.setGeometry(QRect(125, 122, 201, 31))
        self.LastName_2 = QLabel(self.tab_3)
        self.LastName_2.setObjectName(u"LastName_2")
        self.LastName_2.setGeometry(QRect(75, 22, 61, 16))
        self.FirstNameInput_2 = QLineEdit(self.tab_3)
        self.FirstNameInput_2.setObjectName(u"FirstNameInput_2")
        self.FirstNameInput_2.setGeometry(QRect(257, 52, 121, 31))
        self.Notes_2 = QLabel(self.tab_3)
        self.Notes_2.setObjectName(u"Notes_2")
        self.Notes_2.setGeometry(QRect(215, 172, 49, 16))
        self.label_8 = QLabel(self.tab_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(332, 92, 75, 100))
        self.label_8.setPixmap(QPixmap(u":/images/hangeronlyright.png"))
        self.label_8.setScaledContents(True)
        self.label_10 = QLabel(self.tab_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(49, 93, 70, 98))
        self.label_10.setPixmap(QPixmap(u":/images/hangerleft.png"))
        self.label_10.setScaledContents(True)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.lineEdit_16 = QLineEdit(self.tab_4)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(48, 785, 141, 31))
        self.lineEdit_17 = QLineEdit(self.tab_4)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(98, 855, 201, 31))
        self.label_16 = QLabel(self.tab_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(238, 755, 71, 16))
        self.lineEdit_18 = QLineEdit(self.tab_4)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(230, 785, 121, 31))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.puandpbutton_2 = QPushButton(self.page_2)
        self.puandpbutton_2.setObjectName(u"puandpbutton_2")
        self.puandpbutton_2.setGeometry(QRect(315, 850, 147, 51))
        self.qtbutton_2 = QPushButton(self.page_2)
        self.qtbutton_2.setObjectName(u"qtbutton_2")
        self.qtbutton_2.setGeometry(QRect(3, 850, 147, 51))
        self.paybutton_2 = QPushButton(self.page_2)
        self.paybutton_2.setObjectName(u"paybutton_2")
        self.paybutton_2.setGeometry(QRect(160, 850, 147, 51))
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(120, 0, 49, 16))
        self.ncbutton_2 = QPushButton(self.page_2)
        self.ncbutton_2.setObjectName(u"ncbutton_2")
        self.ncbutton_2.setGeometry(QRect(3, 490, 147, 51))
        self.pushButton_3 = QPushButton(self.page_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(1600, 49, 178, 71))
        self.gridLayoutWidget = QWidget(self.page_2)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(4, 550, 456, 292))
        self.tickettypebuttongrid_2 = QGridLayout(self.gridLayoutWidget)
        self.tickettypebuttongrid_2.setObjectName(u"tickettypebuttongrid_2")
        self.tickettypebuttongrid_2.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.tickettypebuttongrid_2.setContentsMargins(1, 1, 1, 1)
        self.ctlist_2 = QTableWidget(self.page_2)
        if (self.ctlist_2.columnCount() < 8):
            self.ctlist_2.setColumnCount(8)
        icon2 = QIcon()
        icon2.addFile(u":/images/Logo2.jpg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setIcon(icon2);
        self.ctlist_2.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.ctlist_2.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.ctlist_2.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.ctlist_2.setHorizontalHeaderItem(3, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.ctlist_2.setHorizontalHeaderItem(4, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.ctlist_2.setHorizontalHeaderItem(5, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.ctlist_2.setHorizontalHeaderItem(6, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.ctlist_2.setHorizontalHeaderItem(7, __qtablewidgetitem15)
        self.ctlist_2.setObjectName(u"ctlist_2")
        self.ctlist_2.setGeometry(QRect(464, 46, 995, 1040))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.ctlist_2.sizePolicy().hasHeightForWidth())
        self.ctlist_2.setSizePolicy(sizePolicy1)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        brush8 = QBrush(QColor(40, 81, 121, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        brush9 = QBrush(QColor(255, 0, 0, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        brush10 = QBrush(QColor(59, 118, 177, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        brush11 = QBrush(QColor(22, 44, 66, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Accent, brush9)
        self.ctlist_2.setPalette(palette1)
        self.ctlist_2.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.ctlist_2.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.ctlist_2.setProperty(u"showDropIndicator", False)
        self.ctlist_2.setDragDropOverwriteMode(False)
        self.ctlist_2.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.ctlist_2.setSortingEnabled(True)
        self.ctlist_2.setWordWrap(False)
        self.ctlist_2.setCornerButtonEnabled(False)
        self.ctlist_2.horizontalHeader().setVisible(True)
        self.ctlist_2.horizontalHeader().setDefaultSectionSize(124)
        self.ctlist_2.horizontalHeader().setStretchLastSection(True)
        self.ctlist_2.verticalHeader().setVisible(False)
        self.ctlist_2.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.ctlist_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.changetodetailedticket = QPushButton(self.page_2)
        self.changetodetailedticket.setObjectName(u"changetodetailedticket")
        self.changetodetailedticket.setGeometry(QRect(1600, 137, 178, 71))
        self.totalowedlabel_2 = QLabel(self.page_2)
        self.totalowedlabel_2.setObjectName(u"totalowedlabel_2")
        self.totalowedlabel_2.setGeometry(QRect(259, 491, 111, 16))
        self.totalowed_2 = QLineEdit(self.page_2)
        self.totalowed_2.setObjectName(u"totalowed_2")
        self.totalowed_2.setGeometry(QRect(233, 507, 161, 31))
        self.totalowed_2.setReadOnly(True)
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1456, 822, 465, 287))
        self.label_5.setPixmap(QPixmap(u":/images/Logo2.jpg"))
        self.label_5.setScaledContents(True)
        self.more_info_button = QCommandLinkButton(self.page_2)
        self.more_info_button.setObjectName(u"more_info_button")
        self.more_info_button.setGeometry(QRect(148, 428, 172, 41))
        self.more_info_button.setIcon(icon1)
        self.more_info_button.setIconSize(QSize(25, 23))
        self.pageswidget.addWidget(self.page_2)
        CustomerAccount2.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.LastNameInput, self.FirstNameInput)
        QWidget.setTabOrder(self.FirstNameInput, self.PhoneNumberInput)
        QWidget.setTabOrder(self.PhoneNumberInput, self.NotesInput)
        QWidget.setTabOrder(self.NotesInput, self.ncbutton)
        QWidget.setTabOrder(self.ncbutton, self.qtbutton)
        QWidget.setTabOrder(self.qtbutton, self.paybutton)
        QWidget.setTabOrder(self.paybutton, self.puandpbutton)
        QWidget.setTabOrder(self.puandpbutton, self.pushButton_16)
        QWidget.setTabOrder(self.pushButton_16, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.LastNameInput_2)
        QWidget.setTabOrder(self.LastNameInput_2, self.FirstNameInput_2)
        QWidget.setTabOrder(self.FirstNameInput_2, self.PhoneNumberInput_2)
        QWidget.setTabOrder(self.PhoneNumberInput_2, self.NotesInput_2)
        QWidget.setTabOrder(self.NotesInput_2, self.ncbutton_2)
        QWidget.setTabOrder(self.ncbutton_2, self.qtbutton_2)
        QWidget.setTabOrder(self.qtbutton_2, self.paybutton_2)
        QWidget.setTabOrder(self.paybutton_2, self.puandpbutton_2)
        QWidget.setTabOrder(self.puandpbutton_2, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.lineEdit_18)
        QWidget.setTabOrder(self.lineEdit_18, self.lineEdit_16)
        QWidget.setTabOrder(self.lineEdit_16, self.lineEdit_17)
        QWidget.setTabOrder(self.lineEdit_17, self.tabWidget_2)

        self.retranslateUi(CustomerAccount2)

        self.pageswidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(CustomerAccount2)
    # setupUi

    def retranslateUi(self, CustomerAccount2):
        CustomerAccount2.setWindowTitle(QCoreApplication.translate("CustomerAccount2", u"MainWindow", None))
        self.puandpbutton.setText(QCoreApplication.translate("CustomerAccount2", u"Pick up + Pay", None))
        self.paybutton.setText(QCoreApplication.translate("CustomerAccount2", u"Pay", None))
        self.qtbutton.setText(QCoreApplication.translate("CustomerAccount2", u"Quick Ticket", None))
        self.FirstName.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.PhoneNumber.setText(QCoreApplication.translate("CustomerAccount2", u"Phone Number", None))
        self.LastName.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.Notes.setText(QCoreApplication.translate("CustomerAccount2", u"Notes", None))
        self.label_2.setText("")
        self.label.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QCoreApplication.translate("CustomerAccount2", u"Tab 1", None))
        self.Notes_3.setText(QCoreApplication.translate("CustomerAccount2", u"Notes", None))
        self.LastName_3.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.FirstName_3.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.label_7.setText("")
        self.label_9.setText("")
        self.PhoneNumber_3.setText(QCoreApplication.translate("CustomerAccount2", u"Phone Number", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("CustomerAccount2", u"Tab 2", None))
        self.label_17.setText(QCoreApplication.translate("CustomerAccount2", u"Page 1", None))
        self.ncbutton.setText(QCoreApplication.translate("CustomerAccount2", u"Next Customer", None))
        self.pushButton_16.setText(QCoreApplication.translate("CustomerAccount2", u"Go To Customer Account 2", None))
        
        # ----------------------------
        # Updated Header Texts for ctlist:
        ___qtablewidgetitem = self.ctlist.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("CustomerAccount2", u"Picked/Paid", None))
        ___qtablewidgetitem1 = self.ctlist.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("CustomerAccount2", u"Ticket Type", None))
        ___qtablewidgetitem2 = self.ctlist.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("CustomerAccount2", u"Drop Off Date", None))
        ___qtablewidgetitem3 = self.ctlist.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("CustomerAccount2", u"Due Date", None))
        ___qtablewidgetitem4 = self.ctlist.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("CustomerAccount2", u"Ticket #", None))
        ___qtablewidgetitem5 = self.ctlist.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("CustomerAccount2", u"Location", None))
        ___qtablewidgetitem6 = self.ctlist.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("CustomerAccount2", u"Pieces", None))
        ___qtablewidgetitem7 = self.ctlist.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("CustomerAccount2", u"Total$", None))
        # ----------------------------
        
        self.changetodetailedticket_2.setText(QCoreApplication.translate("CustomerAccount2", u"Change to Detailed Ticket", None))
        self.totalowedlabel.setText(QCoreApplication.translate("CustomerAccount2", u"Total Amount Owed", None))
        self.label_4.setText("")
        self.more_info_button_2.setText(QCoreApplication.translate("CustomerAccount2", u"       More Info", None))
        self.FirstName_2.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.PhoneNumber_2.setText(QCoreApplication.translate("CustomerAccount2", u"Phone Number", None))
        self.LastName_2.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.Notes_2.setText(QCoreApplication.translate("CustomerAccount2", u"Notes", None))
        self.label_8.setText("")
        self.label_10.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("CustomerAccount2", u"Tab 1", None))
        self.label_16.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("CustomerAccount2", u"Tab 2", None))
        self.puandpbutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Pick up + Pay", None))
        self.qtbutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Quick Ticket", None))
        self.paybutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Pay", None))
        self.label_18.setText(QCoreApplication.translate("CustomerAccount2", u"Page 2", None))
        self.ncbutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Next Customer", None))
        self.pushButton_3.setText(QCoreApplication.translate("CustomerAccount2", u"Go To Customer Account 1", None))
        
        # ----------------------------
        # Updated Header Texts for ctlist_2:
        ___qtablewidgetitem8 = self.ctlist_2.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("CustomerAccount2", u"Picked/Paid", None))
        ___qtablewidgetitem9 = self.ctlist_2.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("CustomerAccount2", u"Ticket Type", None))
        ___qtablewidgetitem10 = self.ctlist_2.horizontalHeaderItem(2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("CustomerAccount2", u"Drop Off Date", None))
        ___qtablewidgetitem11 = self.ctlist_2.horizontalHeaderItem(3)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("CustomerAccount2", u"Due Date", None))
        ___qtablewidgetitem12 = self.ctlist_2.horizontalHeaderItem(4)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("CustomerAccount2", u"Ticket #", None))
        ___qtablewidgetitem13 = self.ctlist_2.horizontalHeaderItem(5)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("CustomerAccount2", u"Location", None))
        ___qtablewidgetitem14 = self.ctlist_2.horizontalHeaderItem(6)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("CustomerAccount2", u"Pieces", None))
        ___qtablewidgetitem15 = self.ctlist_2.horizontalHeaderItem(7)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("CustomerAccount2", u"Total$", None))
        # ----------------------------
        
        self.changetodetailedticket.setText(QCoreApplication.translate("CustomerAccount2", u"Change to Detailed Ticket", None))
        self.totalowedlabel_2.setText(QCoreApplication.translate("CustomerAccount2", u"Total Amount Owed", None))
        self.label_5.setText("")
        self.more_info_button.setText(QCoreApplication.translate("CustomerAccount2", u"       More Info", None))
