from PySide6.QtCore import (QCoreApplication, QRect, QSize, Qt)
from PySide6.QtGui import (QBrush, QColor, QFont, QPalette, QIcon)
from PySide6.QtWidgets import (QLabel, QAbstractScrollArea, QAbstractItemView, QPushButton,
    QTabWidget, QTextEdit, QWidget, QFrame, 
    QListWidget, QTextBrowser, QTableWidget, QTableWidgetItem, QLCDNumber,
    QTreeWidget)



class Ui_DetailedTicketCreation(object):
    def setupUi(self, DetailedTicketCreation):
        if not DetailedTicketCreation.objectName():
            DetailedTicketCreation.setObjectName(u"DetailedTicketCreation")
        DetailedTicketCreation.resize(1481, 944)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
    #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
    #endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        DetailedTicketCreation.setPalette(palette)
        self.plist = QListWidget(DetailedTicketCreation)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(891, 540, 131, 191))
        self.clist = QListWidget(DetailedTicketCreation)
        self.clist.setObjectName(u"clist")
        self.clist.setGeometry(QRect(891, 750, 411, 151))
        self.ulist = QListWidget(DetailedTicketCreation)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(1171, 540, 131, 191))
        self.ulabel = QLabel(DetailedTicketCreation)
        self.ulabel.setObjectName(u"ulabel")
        self.ulabel.setGeometry(QRect(1181, 520, 61, 16))
        self.plabel = QLabel(DetailedTicketCreation)
        self.plabel.setObjectName(u"plabel")
        self.plabel.setGeometry(QRect(901, 520, 71, 16))
        self.clabel = QLabel(DetailedTicketCreation)
        self.clabel.setObjectName(u"clabel")
        self.clabel.setGeometry(QRect(901, 730, 49, 16))
        self.glist = QTreeWidget(DetailedTicketCreation)
        self.glist.setObjectName(u"glist")
        self.glist.setGeometry(QRect(891, 109, 411, 401))
        font = QFont()
        font.setPointSize(12)
        self.glist.setFont(font)
        self.glist.setHeaderLabels(["Garments"])  
        self.glist.setIconSize(QSize(0, 0))

        self.tlist = QListWidget(DetailedTicketCreation)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(1031, 540, 131, 151))
        self.tlabel = QLabel(DetailedTicketCreation)
        self.tlabel.setObjectName(u"tlabel")
        self.tlabel.setGeometry(QRect(1041, 520, 61, 16))
        self.glabel = QLabel(DetailedTicketCreation)
        self.glabel.setObjectName(u"glabel")
        self.glabel.setGeometry(QRect(901, 90, 61, 16))
        self.pieces_label = QLabel(DetailedTicketCreation)
        self.pieces_label.setObjectName(u"pieces_label")
        self.pieces_label.setGeometry(QRect(1029, 690, 40, 18))
        font1 = QFont()
        font1.setPointSize(7)
        self.pieces_label.setFont(font1)
        self.editgarmentbutton = QPushButton(DetailedTicketCreation)
        self.editgarmentbutton.setObjectName(u"editgarmentbutton")
        self.editgarmentbutton.setGeometry(QRect(1312, 691, 121, 41))
        self.deletegarmentbutton = QPushButton(DetailedTicketCreation)
        self.deletegarmentbutton.setObjectName(u"deletegarmentbutton")
        self.deletegarmentbutton.setGeometry(QRect(1312, 750, 121, 41))
        self.canceltbutton = QPushButton(DetailedTicketCreation)
        self.canceltbutton.setObjectName(u"canceltbutton")
        self.canceltbutton.setGeometry(QRect(71, 857, 111, 41))
        self.ptbutton = QPushButton(DetailedTicketCreation)
        self.ptbutton.setObjectName(u"ptbutton")
        self.ptbutton.setGeometry(QRect(71, 720, 111, 41))
        self.ptandtbutton = QPushButton(DetailedTicketCreation)
        self.ptandtbutton.setObjectName(u"ptandtbutton")
        self.ptandtbutton.setGeometry(QRect(71, 667, 111, 41))
        self.tctabs = QTabWidget(DetailedTicketCreation)
        self.tctabs.setObjectName(u"tctabs")
        self.tctabs.setGeometry(QRect(201, 90, 681, 811))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
    #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
    #endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.tctabs.setPalette(palette1)
        self.tctabs.setFont(font1)
        self.tctabs1 = QWidget()
        self.tctabs1.setObjectName(u"tctabs1")
        self.ttname = QTextBrowser(self.tctabs1)
        self.ttname.setObjectName(u"ttname")
        self.ttname.setGeometry(QRect(-10, -10, 701, 51))
        self.sglist = QTableWidget(self.tctabs1)
        if (self.sglist.columnCount() < 7):
            self.sglist.setColumnCount(7)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font1)
        self.sglist.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setFont(font1)
        self.sglist.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font1)
        self.sglist.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setFont(font1)
        self.sglist.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setFont(font1)
        self.sglist.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setFont(font1)
        self.sglist.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setFont(font1)
        self.sglist.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        self.sglist.setObjectName(u"sglist")
        self.sglist.setEnabled(True)
        self.sglist.setGeometry(QRect(-10, 30, 691, 631))
        self.sglist.setBaseSize(QSize(0, 0))
        self.sglist.setLineWidth(0)
        self.sglist.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.sglist.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.sglist.setTabKeyNavigation(True)
        self.sglist.setProperty(u"showDropIndicator", False)
        self.sglist.setDragEnabled(True)
        self.sglist.setDragDropOverwriteMode(False)
        self.sglist.setDragDropMode(QAbstractItemView.DragDropMode.InternalMove)
        self.sglist.setDefaultDropAction(Qt.DropAction.MoveAction)
        self.sglist.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.sglist.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.sglist.setTextElideMode(Qt.TextElideMode.ElideRight)
        self.sglist.setShowGrid(False)
        self.sglist.setSortingEnabled(True)
        self.sglist.setCornerButtonEnabled(True)
        self.sglist.horizontalHeader().setVisible(True)
        self.sglist.horizontalHeader().setCascadingSectionResizes(False)
        self.sglist.horizontalHeader().setHighlightSections(True)
        self.sglist.horizontalHeader().setProperty(u"showSortIndicator", True)
        self.sglist.horizontalHeader().setStretchLastSection(False)
        self.sglist.verticalHeader().setVisible(False)
        self.sglist.verticalHeader().setHighlightSections(False)
        self.pricesframe = QFrame(self.tctabs1)
        self.pricesframe.setObjectName(u"pricesframe")
        self.pricesframe.setGeometry(QRect(-10, 650, 691, 141))
        self.pricesframe.setFrameShape(QFrame.Shape.StyledPanel)
        self.pricesframe.setFrameShadow(QFrame.Shadow.Raised)
        self.line = QFrame(self.pricesframe)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, -40, 681, 81))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.ticketnotes = QTextEdit(self.pricesframe)
        self.ticketnotes.setObjectName(u"ticketnotes")
        self.ticketnotes.setGeometry(QRect(10, 3, 441, 131))
        self.total_price_label = QLabel(self.pricesframe)
        self.total_price_label.setObjectName(u"total_price_label")
        self.total_price_label.setGeometry(QRect(400, 115, 271, 20))
        self.total_price_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.delivery_fee_label = QLabel(self.pricesframe)
        self.delivery_fee_label.setObjectName(u"delivery_fee_label")
        self.delivery_fee_label.setGeometry(QRect(400, 90, 271, 20))
        self.delivery_fee_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.taxes_label = QLabel(self.pricesframe)
        self.taxes_label.setObjectName(u"taxes_label")
        self.taxes_label.setGeometry(QRect(400, 65, 271, 20))
        self.taxes_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.deductions_label = QLabel(self.pricesframe)
        self.deductions_label.setObjectName(u"deductions_label")
        self.deductions_label.setGeometry(QRect(400, 40, 271, 20))
        self.deductions_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.initial_price_label = QLabel(self.pricesframe)
        self.initial_price_label.setObjectName(u"initial_price_label")
        self.initial_price_label.setGeometry(QRect(400, 15, 271, 20))
        self.initial_price_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.tctabs.addTab(self.tctabs1, "")
        self.tctabs2 = QWidget()
        self.tctabs2.setObjectName(u"tctabs2")
        self.ttname_2 = QTextBrowser(self.tctabs2)
        self.ttname_2.setObjectName(u"ttname_2")
        self.ttname_2.setGeometry(QRect(-10, -10, 701, 51))
        self.sglist_2 = QTableWidget(self.tctabs2)
        if (self.sglist_2.columnCount() < 7):
            self.sglist_2.setColumnCount(7)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.sglist_2.setHorizontalHeaderItem(0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.sglist_2.setHorizontalHeaderItem(1, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.sglist_2.setHorizontalHeaderItem(2, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.sglist_2.setHorizontalHeaderItem(3, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.sglist_2.setHorizontalHeaderItem(4, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.sglist_2.setHorizontalHeaderItem(5, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.sglist_2.setHorizontalHeaderItem(6, __qtablewidgetitem13)
        self.sglist_2.setObjectName(u"sglist_2")
        self.sglist_2.setGeometry(QRect(-10, 30, 691, 631))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
    #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
    #endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.sglist_2.setPalette(palette2)
        self.sglist_2.setFont(font1)
        self.sglist_2.setLineWidth(1)
        self.sglist_2.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.sglist_2.setShowGrid(False)
        self.sglist_2.setSortingEnabled(True)
        self.sglist_2.setCornerButtonEnabled(False)
        self.pricesframe_2 = QFrame(self.tctabs2)
        self.pricesframe_2.setObjectName(u"pricesframe_2")
        self.pricesframe_2.setGeometry(QRect(-10, 650, 691, 141))
        self.pricesframe_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.pricesframe_2.setFrameShadow(QFrame.Shadow.Raised)
        self.line_2 = QFrame(self.pricesframe_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, -40, 681, 81))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.ticketnotes_2 = QTextEdit(self.pricesframe_2)
        self.ticketnotes_2.setObjectName(u"ticketnotes_2")
        self.ticketnotes_2.setGeometry(QRect(10, 3, 441, 131))
        self.total_price_label_2 = QLabel(self.pricesframe_2)
        self.total_price_label_2.setObjectName(u"total_price_label_2")
        self.total_price_label_2.setGeometry(QRect(400, 115, 271, 20))
        self.total_price_label_2.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.taxes_label_2 = QLabel(self.pricesframe_2)
        self.taxes_label_2.setObjectName(u"taxes_label_2")
        self.taxes_label_2.setGeometry(QRect(400, 65, 271, 20))
        self.taxes_label_2.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.delivery_fee_label_2 = QLabel(self.pricesframe_2)
        self.delivery_fee_label_2.setObjectName(u"delivery_fee_label_2")
        self.delivery_fee_label_2.setGeometry(QRect(400, 90, 271, 20))
        self.delivery_fee_label_2.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.initial_price_label_2 = QLabel(self.pricesframe_2)
        self.initial_price_label_2.setObjectName(u"initial_price_label_2")
        self.initial_price_label_2.setGeometry(QRect(400, 15, 271, 20))
        self.initial_price_label_2.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.deductions_label_2 = QLabel(self.pricesframe_2)
        self.deductions_label_2.setObjectName(u"deductions_label_2")
        self.deductions_label_2.setGeometry(QRect(400, 40, 271, 20))
        self.deductions_label_2.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.tctabs.addTab(self.tctabs2, "")
        self.tctabs3 = QWidget()
        self.tctabs3.setObjectName(u"tctabs3")
        self.ttname_3 = QTextBrowser(self.tctabs3)
        self.ttname_3.setObjectName(u"ttname_3")
        self.ttname_3.setGeometry(QRect(-10, -10, 701, 51))
        self.sglist_3 = QTableWidget(self.tctabs3)
        if (self.sglist_3.columnCount() < 7):
            self.sglist_3.setColumnCount(7)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.sglist_3.setHorizontalHeaderItem(0, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.sglist_3.setHorizontalHeaderItem(1, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.sglist_3.setHorizontalHeaderItem(2, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.sglist_3.setHorizontalHeaderItem(3, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.sglist_3.setHorizontalHeaderItem(4, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.sglist_3.setHorizontalHeaderItem(5, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.sglist_3.setHorizontalHeaderItem(6, __qtablewidgetitem20)
        self.sglist_3.setObjectName(u"sglist_3")
        self.sglist_3.setGeometry(QRect(-10, 30, 691, 631))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
    #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
    #endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.sglist_3.setPalette(palette3)
        self.sglist_3.setSortingEnabled(True)
        self.pricesframe_3 = QFrame(self.tctabs3)
        self.pricesframe_3.setObjectName(u"pricesframe_3")
        self.pricesframe_3.setGeometry(QRect(-10, 650, 691, 141))
        self.pricesframe_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.pricesframe_3.setFrameShadow(QFrame.Shadow.Raised)
        self.line_3 = QFrame(self.pricesframe_3)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, -40, 681, 81))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.ticketnotes_3 = QTextEdit(self.pricesframe_3)
        self.ticketnotes_3.setObjectName(u"ticketnotes_3")
        self.ticketnotes_3.setGeometry(QRect(10, 3, 441, 131))
        self.total_price_label_3 = QLabel(self.pricesframe_3)
        self.total_price_label_3.setObjectName(u"total_price_label_3")
        self.total_price_label_3.setGeometry(QRect(400, 115, 271, 20))
        self.total_price_label_3.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.taxes_label_3 = QLabel(self.pricesframe_3)
        self.taxes_label_3.setObjectName(u"taxes_label_3")
        self.taxes_label_3.setGeometry(QRect(400, 65, 271, 20))
        self.taxes_label_3.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.delivery_fee_label_3 = QLabel(self.pricesframe_3)
        self.delivery_fee_label_3.setObjectName(u"delivery_fee_label_3")
        self.delivery_fee_label_3.setGeometry(QRect(400, 90, 271, 20))
        self.delivery_fee_label_3.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.initial_price_label_3 = QLabel(self.pricesframe_3)
        self.initial_price_label_3.setObjectName(u"initial_price_label_3")
        self.initial_price_label_3.setGeometry(QRect(400, 15, 271, 20))
        self.initial_price_label_3.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.deductions_label_3 = QLabel(self.pricesframe_3)
        self.deductions_label_3.setObjectName(u"deductions_label_3")
        self.deductions_label_3.setGeometry(QRect(400, 40, 271, 20))
        self.deductions_label_3.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTrailing | Qt.AlignmentFlag.AlignVCenter)
        self.tctabs.addTab(self.tctabs3, "")
        self.ctbutton = QPushButton(DetailedTicketCreation)
        self.ctbutton.setObjectName(u"ctbutton")
        self.ctbutton.setGeometry(QRect(71, 800, 111, 41))
        self.addgarmentbutton = QPushButton(DetailedTicketCreation)
        self.addgarmentbutton.setObjectName(u"addgarmentbutton")
        self.addgarmentbutton.setGeometry(QRect(1313, 574, 121, 41))
        self.addtogarmentbutton = QPushButton(DetailedTicketCreation)
        self.addtogarmentbutton.setObjectName(u"addtogarmentbutton")
        self.addtogarmentbutton.setGeometry(QRect(1312, 632, 121, 41))
        self.tickettypebuttonwidget = QWidget(DetailedTicketCreation)
        self.tickettypebuttonwidget.setObjectName(u"tickettypebuttonwidget")
        self.tickettypebuttonwidget.setGeometry(QRect(50, 120, 141, 521))
        self.label_5 = QLabel(DetailedTicketCreation)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(360, 20, 811, 61))
        palette4 = QPalette()
        brush8 = QBrush(QColor(85, 0, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush8)
        brush9 = QBrush(QColor(255, 170, 255, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush9)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush9)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush8)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        self.label_5.setPalette(palette4)
        font2 = QFont()
        font2.setFamilies([u"Ravie"])
        font2.setPointSize(36)
        font2.setBold(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        self.label_5.setFont(font2)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setTextFormat(Qt.TextFormat.RichText)
        self.label_5.setScaledContents(False)
        self.lcd_number = QLCDNumber(DetailedTicketCreation)
        self.lcd_number.setObjectName(u"lcd_number")
        self.lcd_number.setGeometry(QRect(1071, 703, 51, 36))
        self.lcd_number.setFrameShape(QFrame.Shape.StyledPanel)
        self.lcd_number.setFrameShadow(QFrame.Shadow.Sunken)
        self.lcd_number.setSmallDecimalPoint(False)
        self.lcd_number.setDigitCount(3)
        self.lcd_number.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcd_number.setProperty(u"value", 0.000000000000000)
        self.lcd_number.setProperty(u"intValue", 0)
        self.add_piece = QPushButton(DetailedTicketCreation)
        self.add_piece.setObjectName(u"add_piece")
        self.add_piece.setGeometry(QRect(1131, 705, 35, 32))
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListAdd))
        self.add_piece.setIcon(icon)
        self.subtract_piece = QPushButton(DetailedTicketCreation)
        self.subtract_piece.setObjectName(u"subtract_piece")
        self.subtract_piece.setGeometry(QRect(1028, 706, 35, 32))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListRemove))
        self.subtract_piece.setIcon(icon1)

        self.retranslateUi(DetailedTicketCreation)
        self.tctabs.setCurrentIndex(0)

        # --- Connect the add and subtract buttons to their functions ---
        self.add_piece.clicked.connect(self.add_piece_action)
        self.subtract_piece.clicked.connect(self.subtract_piece_action)

    def retranslateUi(self, DetailedTicketCreation):
        DetailedTicketCreation.setWindowTitle(QCoreApplication.translate("DetailedTicketCreation", u"Form", None))
        self.ulabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Upcharges", None))
        self.plabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Patterns", None))
        self.clabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Colors", None))
        self.tlabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Textures", None))
        self.glabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Garments", None))
        self.pieces_label.setText(QCoreApplication.translate("DetailedTicketCreation", u"#Pieces", None))
        self.editgarmentbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Remove Detail", None))
        self.deletegarmentbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Delete Garment", None))
        self.canceltbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Cancel Ticket", None))
        self.ptbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Print Ticket", None))
        self.ptandtbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Print Ticket + Tags", None))
        self.ttname.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>", None))
        ___qtablewidgetitem = self.sglist.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("DetailedTicketCreation", u"Pieces", None));
        ___qtablewidgetitem1 = self.sglist.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("DetailedTicketCreation", u"Garment Variant", None));
        ___qtablewidgetitem2 = self.sglist.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("DetailedTicketCreation", u"Colors", None));
        ___qtablewidgetitem3 = self.sglist.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("DetailedTicketCreation", u"Patterns", None));
        ___qtablewidgetitem4 = self.sglist.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("DetailedTicketCreation", u"Textures", None));
        ___qtablewidgetitem5 = self.sglist.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("DetailedTicketCreation", u"Upcharges", None));
        ___qtablewidgetitem6 = self.sglist.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("DetailedTicketCreation", u"Price", None));
        self.total_price_label.setText(QCoreApplication.translate("DetailedTicketCreation", u"Total Price: $0.00", None))
        self.delivery_fee_label.setText(QCoreApplication.translate("DetailedTicketCreation", u"Delivery Fee: $0.00", None))
        self.taxes_label.setText(QCoreApplication.translate("DetailedTicketCreation", u"Taxes: $0.00", None))
        self.deductions_label.setText(QCoreApplication.translate("DetailedTicketCreation", u"Deductions: $0.00", None))
        self.initial_price_label.setText(QCoreApplication.translate("DetailedTicketCreation", u"Initial Price: $0.00", None))
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs1), QCoreApplication.translate("DetailedTicketCreation", u"ticket1", None))
        self.ttname_2.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>", None))
        ___qtablewidgetitem7 = self.sglist_2.horizontalHeaderItem(0)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("DetailedTicketCreation", u"Pieces", None));
        ___qtablewidgetitem8 = self.sglist_2.horizontalHeaderItem(1)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("DetailedTicketCreation", u"Garment Variant", None));
        ___qtablewidgetitem9 = self.sglist_2.horizontalHeaderItem(2)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("DetailedTicketCreation", u"Colors", None));
        ___qtablewidgetitem10 = self.sglist_2.horizontalHeaderItem(3)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("DetailedTicketCreation", u"Patterns", None));
        ___qtablewidgetitem11 = self.sglist_2.horizontalHeaderItem(4)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("DetailedTicketCreation", u"Textures", None));
        ___qtablewidgetitem12 = self.sglist_2.horizontalHeaderItem(5)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("DetailedTicketCreation", u"Upcharges", None));
        ___qtablewidgetitem13 = self.sglist_2.horizontalHeaderItem(6)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("DetailedTicketCreation", u"Price", None));
        self.total_price_label_2.setText(QCoreApplication.translate("DetailedTicketCreation", u"Total Price: $0.00", None))
        self.taxes_label_2.setText(QCoreApplication.translate("DetailedTicketCreation", u"Taxes: $0.00", None))
        self.delivery_fee_label_2.setText(QCoreApplication.translate("DetailedTicketCreation", u"Delivery Fee: $0.00", None))
        self.initial_price_label_2.setText(QCoreApplication.translate("DetailedTicketCreation", u"Initial Price: $0.00", None))
        self.deductions_label_2.setText(QCoreApplication.translate("DetailedTicketCreation", u"Deductions: $0.00", None))
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs2), QCoreApplication.translate("DetailedTicketCreation", u"ticket2", None))
        self.ttname_3.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>", None))
        ___qtablewidgetitem14 = self.sglist_3.horizontalHeaderItem(0)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("DetailedTicketCreation", u"Pieces", None));
        ___qtablewidgetitem15 = self.sglist_3.horizontalHeaderItem(1)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("DetailedTicketCreation", u"Garment Variant", None));
        ___qtablewidgetitem16 = self.sglist_3.horizontalHeaderItem(2)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("DetailedTicketCreation", u"Colors", None));
        ___qtablewidgetitem17 = self.sglist_3.horizontalHeaderItem(3)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("DetailedTicketCreation", u"Patterns", None));
        ___qtablewidgetitem18 = self.sglist_3.horizontalHeaderItem(4)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("DetailedTicketCreation", u"Textures", None));
        ___qtablewidgetitem19 = self.sglist_3.horizontalHeaderItem(5)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("DetailedTicketCreation", u"Upcharges", None));
        ___qtablewidgetitem20 = self.sglist_3.horizontalHeaderItem(6)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("DetailedTicketCreation", u"Price", None));
        self.total_price_label_3.setText(QCoreApplication.translate("DetailedTicketCreation", u"Total Price: $0.00", None))
        self.taxes_label_3.setText(QCoreApplication.translate("DetailedTicketCreation", u"Taxes: $0.00", None))
        self.delivery_fee_label_3.setText(QCoreApplication.translate("DetailedTicketCreation", u"Delivery Fee: $0.00", None))
        self.initial_price_label_3.setText(QCoreApplication.translate("DetailedTicketCreation", u"Initial Price: $0.00", None))
        self.deductions_label_3.setText(QCoreApplication.translate("DetailedTicketCreation", u"Deductions: $0.00", None))
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs3), QCoreApplication.translate("DetailedTicketCreation", u"ticket3", None))
        self.ctbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Create Ticket", None))
        self.addgarmentbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Add Garment", None))
        self.addtogarmentbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Add Garment Details", None))
        self.label_5.setText(QCoreApplication.translate("DetailedTicketCreation", u"Detailed Ticket Creation", None))
        self.add_piece.setText("")
        self.subtract_piece.setText("")

    # --- New methods for incrementing/decrementing the piece count ---
    def add_piece_action(self):
        # Get current integer value from lcd_number, increment by 1, and update display.
        current_value = self.lcd_number.value()
        new_value = current_value + 1
        self.lcd_number.display(new_value)

    def subtract_piece_action(self):
        # Get current value; if greater than zero, subtract 1.
        current_value = self.lcd_number.value()
        new_value = current_value - 1 if current_value > 0 else 0
        self.lcd_number.display(new_value)
