from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, Qt)
from PySide6.QtGui import (QBrush, QColor, QPalette)
from PySide6.QtWidgets import (QLabel, QLineEdit, QMenuBar, QPushButton,
    QStatusBar, QWidget, QListWidget)


class Ui_GarmentandColorCreation(object):
    def setupUi(self, GarmentandColorCreation):
        if not GarmentandColorCreation.objectName():
            GarmentandColorCreation.setObjectName(u"GarmentandColorCreation")
        GarmentandColorCreation.resize(1007, 842)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        GarmentandColorCreation.setPalette(palette)
        GarmentandColorCreation.setStyleSheet(u"font: 9pt \"Segoe UI\";")
        self.centralwidget = QWidget(GarmentandColorCreation)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sgbutton = QPushButton(self.centralwidget)
        self.sgbutton.setObjectName(u"sgbutton")
        self.sgbutton.setGeometry(QRect(160, 370, 91, 24))
        self.sglist = QListWidget(self.centralwidget)
        self.sglist.setObjectName(u"sglist")
        self.sglist.setGeometry(QRect(460, 50, 501, 281))
        self.gninput = QLineEdit(self.centralwidget)
        self.gninput.setObjectName(u"gninput")
        self.gninput.setGeometry(QRect(140, 20, 113, 22))
        self.gnlabel = QLabel(self.centralwidget)
        self.gnlabel.setObjectName(u"gnlabel")
        self.gnlabel.setGeometry(QRect(30, 20, 91, 16))
        self.sglabel = QLabel(self.centralwidget)
        self.sglabel.setObjectName(u"sglabel")
        self.sglabel.setGeometry(QRect(680, 30, 91, 16))
        self.sglabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.avbutton = QPushButton(self.centralwidget)
        self.avbutton.setObjectName(u"avbutton")
        self.avbutton.setGeometry(QRect(270, 170, 121, 24))
        self.sibutton = QPushButton(self.centralwidget)
        self.sibutton.setObjectName(u"sibutton")
        self.sibutton.setGeometry(QRect(20, 90, 91, 24))
        self.avlist = QListWidget(self.centralwidget)
        self.avlist.setObjectName(u"avlist")
        self.avlist.setGeometry(QRect(80, 230, 251, 131))
        self.avlabel = QLabel(self.centralwidget)
        self.avlabel.setObjectName(u"avlabel")
        self.avlabel.setGeometry(QRect(160, 210, 81, 21))
        self.egbutton = QPushButton(self.centralwidget)
        self.egbutton.setObjectName(u"egbutton")
        self.egbutton.setGeometry(QRect(550, 340, 91, 24))
        self.dgbutton = QPushButton(self.centralwidget)
        self.dgbutton.setObjectName(u"dgbutton")
        self.dgbutton.setGeometry(QRect(790, 340, 91, 24))
        self.cninput = QLineEdit(self.centralwidget)
        self.cninput.setObjectName(u"cninput")
        self.cninput.setGeometry(QRect(150, 500, 113, 22))
        self.cnlabel = QLabel(self.centralwidget)
        self.cnlabel.setObjectName(u"cnlabel")
        self.cnlabel.setGeometry(QRect(70, 500, 71, 16))
        self.ccbutton = QPushButton(self.centralwidget)
        self.ccbutton.setObjectName(u"ccbutton")
        self.ccbutton.setGeometry(QRect(150, 580, 111, 24))
        self.sclist = QListWidget(self.centralwidget)
        self.sclist.setObjectName(u"sclist")
        self.sclist.setGeometry(QRect(580, 430, 256, 251))
        self.dcbutton = QPushButton(self.centralwidget)
        self.dcbutton.setObjectName(u"dcbutton")
        self.dcbutton.setGeometry(QRect(720, 690, 111, 24))
        self.scbutton = QPushButton(self.centralwidget)
        self.scbutton.setObjectName(u"scbutton")
        self.scbutton.setGeometry(QRect(150, 630, 111, 24))
        self.sclabel = QLabel(self.centralwidget)
        self.sclabel.setObjectName(u"sclabel")
        self.sclabel.setGeometry(QRect(680, 410, 91, 16))
        self.sclabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.ecbutton = QPushButton(self.centralwidget)
        self.ecbutton.setObjectName(u"ecbutton")
        self.ecbutton.setGeometry(QRect(580, 690, 111, 24))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(140, 170, 111, 22))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 170, 51, 20))
        self.ImageLabel = QLabel(self.centralwidget)
        self.ImageLabel.setObjectName(u"ImageLabel")
        self.ImageLabel.setGeometry(QRect(120, 50, 151, 111))
        GarmentandColorCreation.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(GarmentandColorCreation)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1007, 33))
        GarmentandColorCreation.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(GarmentandColorCreation)
        self.statusbar.setObjectName(u"statusbar")
        GarmentandColorCreation.setStatusBar(self.statusbar)

        self.retranslateUi(GarmentandColorCreation)

        QMetaObject.connectSlotsByName(GarmentandColorCreation)
    # setupUi

    def retranslateUi(self, GarmentandColorCreation):
        GarmentandColorCreation.setWindowTitle(QCoreApplication.translate("GarmentandColorCreation", u"MainWindow", None))
        self.sgbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Save Garment", None))
        self.gnlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Garment Name:", None))
        self.sglabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Saved Garments", None))
        self.avbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Add Variation", None))
        self.sibutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Select Image", None))
        self.avlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"<html><head/><body><p><span style=\" font-size:7pt;\">Added Variations:</span></p></body></html>", None))
        self.egbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Edit Garment", None))
        self.dgbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Delete Garment", None))
        self.cnlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Color Name:", None))
        self.ccbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Choose Color", None))
        self.dcbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Delete Color", None))
        self.scbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Save Color", None))
        self.sclabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Saved Colors", None))
        self.ecbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Edit Color", None))
        self.label.setText(QCoreApplication.translate("GarmentandColorCreation", u"Variation:", None))
        self.ImageLabel.setText("")
    # retranslateUi



