from PySide6.QtCore import (QCoreApplication, QLocale,
    QMetaObject, QRect, Qt)
from PySide6.QtGui import (QBrush, QColor, QCursor,
    QFont, QPalette)
from PySide6.QtWidgets import (QLabel, QLineEdit, QPushButton,
    QStatusBar, QTreeWidget, QWidget)


class Ui_garmentpricing(object):
    def setupUi(self, garmentpricing):
        if not garmentpricing.objectName():
            garmentpricing.setObjectName(u"garmentpricing")
        garmentpricing.setEnabled(True)
        garmentpricing.resize(708, 602)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        garmentpricing.setPalette(palette)
        font = QFont()
        font.setBold(True)
        garmentpricing.setFont(font)
        garmentpricing.setMouseTracking(False)
        garmentpricing.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        garmentpricing.setAcceptDrops(False)
        self.centralwidget = QWidget(garmentpricing)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.garmentvariationlist = QTreeWidget(self.centralwidget)
        self.garmentvariationlist.setObjectName(u"garmentvariationlist")
        self.garmentvariationlist.setGeometry(QRect(20, 100, 351, 461))
        self.garmentvariationlist.setMouseTracking(False)
        self.garmentvariationlist.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.garmentvariationlist.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.setprice = QPushButton(self.centralwidget)
        self.setprice.setObjectName(u"setprice")
        self.setprice.setGeometry(QRect(480, 370, 121, 41))
        self.price = QLineEdit(self.centralwidget)
        self.price.setObjectName(u"price")
        self.price.setGeometry(QRect(480, 290, 121, 31))
        self.price.setMouseTracking(True)
        self.price.setContextMenuPolicy(Qt.ContextMenuPolicy.PreventContextMenu)
        self.price.setAcceptDrops(False)
        self.price.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.price.setAutoFillBackground(False)
        self.price.setMaxLength(32766)
        self.price.setDragEnabled(True)
        self.price.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 0, 401, 81))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(36)
        font1.setWeight(QFont.Black)
        font1.setItalic(False)
        self.label.setFont(font1)
        self.label.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label.setMouseTracking(False)
        self.label.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.label.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"")
        self.label.setLocale(QLocale(QLocale.Embu, QLocale.Kenya))
        self.label.setLineWidth(1)
        self.label.setTextFormat(Qt.TextFormat.PlainText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setIndent(3)
        garmentpricing.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(garmentpricing)
        self.statusbar.setObjectName(u"statusbar")
        garmentpricing.setStatusBar(self.statusbar)

        self.retranslateUi(garmentpricing)

        QMetaObject.connectSlotsByName(garmentpricing)
    # setupUi

    def retranslateUi(self, garmentpricing):
        garmentpricing.setWindowTitle(QCoreApplication.translate("garmentpricing", u"MainWindow", None))
        ___qtreewidgetitem = self.garmentvariationlist.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("garmentpricing", u"Garments and Variations Pricing", None));
        self.setprice.setText(QCoreApplication.translate("garmentpricing", u"Set Price", None))
        self.price.setText("")
        self.price.setPlaceholderText(QCoreApplication.translate("garmentpricing", u"Input Price", None))
        self.label.setText(QCoreApplication.translate("garmentpricing", u"Garment Pricing", None))
    # retranslateUi

