from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect,
    Qt)
from PySide6.QtGui import (QBrush, QColor, QCursor,
    QFont, QIcon,
    QPalette, QPixmap)
from PySide6.QtWidgets import (QCheckBox, QFrame,
    QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTableWidget, QTableWidgetItem, QAbstractItemView,
    QComboBox, QPlainTextEdit)

class Ui_MoreInfoDialog(object):
    def setupUi(self, MoreInfoDialog):
        if not MoreInfoDialog.objectName():
            MoreInfoDialog.setObjectName(u"MoreInfoDialog")
        MoreInfoDialog.resize(741, 837)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(34, 34, 34, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        MoreInfoDialog.setPalette(palette)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.HelpAbout))
        MoreInfoDialog.setWindowIcon(icon)
        self.delivery_checkbox = QCheckBox(MoreInfoDialog)
        self.delivery_checkbox.setObjectName(u"delivery_checkbox")
        self.delivery_checkbox.setGeometry(QRect(478, 212, 164, 29))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush7 = QBrush(QColor(120, 131, 170, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush8 = QBrush(QColor(255, 85, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        brush9 = QBrush(QColor(255, 255, 255, 107))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        brush10 = QBrush(QColor(255, 255, 255, 135))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.delivery_checkbox.setPalette(palette1)
        font = QFont()
        font.setPointSize(12)
        self.delivery_checkbox.setFont(font)
        self.moreinfoheader = QLabel(MoreInfoDialog)
        self.moreinfoheader.setObjectName(u"moreinfoheader")
        self.moreinfoheader.setGeometry(QRect(202, 32, 328, 128))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.moreinfoheader.setPalette(palette2)
        font1 = QFont()
        font1.setPointSize(32)
        font1.setBold(True)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.moreinfoheader.setFont(font1)
        self.moreinfoheader.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.moreinfoheader.setStyleSheet(u"")
        self.moreinfoheader.setFrameShape(QFrame.Shape.StyledPanel)
        self.moreinfoheader.setFrameShadow(QFrame.Shadow.Plain)
        self.moreinfoheader.setLineWidth(3)
        self.moreinfoheader.setMidLineWidth(3)
        self.moreinfoheader.setPixmap(QPixmap(u":/newPrefix/Images/Logos/OGDC-Logo.jpg"))
        self.moreinfoheader.setScaledContents(True)
        self.moreinfoheader.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.moreinfoheader.setWordWrap(True)
        self.email_customer = QPushButton(MoreInfoDialog)
        self.email_customer.setObjectName(u"email_customer")
        self.email_customer.setGeometry(QRect(566, 660, 127, 42))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.email_customer.setPalette(palette3)
        self.email_customer.setFont(font)
        self.fold_shirts_checkbox = QCheckBox(MoreInfoDialog)
        self.fold_shirts_checkbox.setObjectName(u"fold_shirts_checkbox")
        self.fold_shirts_checkbox.setGeometry(QRect(478, 288, 100, 20))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.fold_shirts_checkbox.setPalette(palette4)
        self.fold_shirts_checkbox.setFont(font)
        self.tableWidget = QTableWidget(MoreInfoDialog)
        if (self.tableWidget.columnCount() < 3):
            self.tableWidget.setColumnCount(3)
        icon1 = QIcon(QIcon.fromTheme(u"preferences-desktop-locale"))
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setIcon(icon1);
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        icon2 = QIcon(QIcon.fromTheme(u"input-keyboard"))
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setIcon(icon2);
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        icon3 = QIcon(QIcon.fromTheme(u"insert-image"))
        font2 = QFont()
        font2.setBold(False)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font2);
        __qtablewidgetitem2.setIcon(icon3);
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(49, 573, 320, 169))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.tableWidget.setPalette(palette5)
        self.tableWidget.setFont(font)
        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.label_9 = QLabel(MoreInfoDialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(476, 506, 90, 20))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label_9.setPalette(palette6)
        self.label_9.setFont(font)
        self.send_notification = QPushButton(MoreInfoDialog)
        self.send_notification.setObjectName(u"send_notification")
        self.send_notification.setGeometry(QRect(405, 660, 127, 42))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette7.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette7.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.send_notification.setPalette(palette7)
        self.send_notification.setFont(font)
        self.box_shirts_checkbox = QCheckBox(MoreInfoDialog)
        self.box_shirts_checkbox.setObjectName(u"box_shirts_checkbox")
        self.box_shirts_checkbox.setGeometry(QRect(478, 324, 99, 20))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette8.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette8.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette8.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette8.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.box_shirts_checkbox.setPalette(palette8)
        self.box_shirts_checkbox.setFont(font)
        self.fluff_fold_checkbox = QCheckBox(MoreInfoDialog)
        self.fluff_fold_checkbox.setObjectName(u"fluff_fold_checkbox")
        self.fluff_fold_checkbox.setGeometry(QRect(478, 360, 123, 20))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette9.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette9.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.fluff_fold_checkbox.setPalette(palette9)
        self.fluff_fold_checkbox.setFont(font)
        self.save_info_button = QPushButton(MoreInfoDialog)
        self.save_info_button.setObjectName(u"save_info_button")
        self.save_info_button.setGeometry(QRect(566, 751, 127, 42))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette10.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette10.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.save_info_button.setPalette(palette10)
        self.save_info_button.setFont(font)
        self.label_8 = QLabel(MoreInfoDialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(477, 414, 90, 20))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette11.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette11.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette11.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette11.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label_8.setPalette(palette11)
        self.label_8.setFont(font)
        self.billing_checkbox = QCheckBox(MoreInfoDialog)
        self.billing_checkbox.setObjectName(u"billing_checkbox")
        self.billing_checkbox.setGeometry(QRect(478, 251, 203, 20))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette12.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette12.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette12.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette12.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.billing_checkbox.setPalette(palette12)
        self.billing_checkbox.setFont(font)
        self.zip_code = QLineEdit(MoreInfoDialog)
        self.zip_code.setObjectName(u"zip_code")
        self.zip_code.setGeometry(QRect(193, 385, 175, 30))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette13.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette13.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette13.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette13.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.zip_code.setPalette(palette13)
        self.zip_code.setFont(font)
        self.home_address = QLineEdit(MoreInfoDialog)
        self.home_address.setObjectName(u"home_address")
        self.home_address.setGeometry(QRect(193, 275, 175, 30))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette14.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette14.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette14.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette14.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.home_address.setPalette(palette14)
        self.home_address.setFont(font)
        self.label_3 = QLabel(MoreInfoDialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(83, 393, 69, 20))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette15.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette15.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette15.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette15.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label_3.setPalette(palette15)
        self.label_3.setFont(font)
        self.email_add = QLineEdit(MoreInfoDialog)
        self.email_add.setObjectName(u"email_add")
        self.email_add.setGeometry(QRect(193, 220, 175, 30))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush)
        palette16.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette16.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette16.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette16.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette16.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette16.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette16.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette16.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.email_add.setPalette(palette16)
        self.email_add.setFont(font)
        self.label_4 = QLabel(MoreInfoDialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(74, 334, 85, 20))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Text, brush)
        palette17.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette17.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette17.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette17.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette17.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette17.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette17.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label_4.setPalette(palette17)
        self.label_4.setFont(font)
        self.label_6 = QLabel(MoreInfoDialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(28, 484, 159, 20))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette18.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette18.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette18.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette18.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette18.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette18.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label_6.setPalette(palette18)
        self.label_6.setFont(font)
        self.ste_apt = QLineEdit(MoreInfoDialog)
        self.ste_apt.setObjectName(u"ste_apt")
        self.ste_apt.setGeometry(QRect(193, 330, 175, 30))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette19.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush)
        palette19.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette19.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette19.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette19.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette19.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette19.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette19.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette19.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette19.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette19.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.ste_apt.setPalette(palette19)
        self.ste_apt.setFont(font)
        self.label = QLabel(MoreInfoDialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(58, 216, 107, 20))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette20.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette20.setBrush(QPalette.Active, QPalette.Text, brush)
        palette20.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette20.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette20.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette20.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette20.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette20.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette20.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette20.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette20.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette20.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette20.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label.setPalette(palette20)
        self.label.setFont(font)
        self.label_2 = QLabel(MoreInfoDialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(61, 275, 106, 20))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette21.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette21.setBrush(QPalette.Active, QPalette.Text, brush)
        palette21.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette21.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette21.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette21.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette21.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette21.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette21.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette21.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette21.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette21.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette21.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label_2.setPalette(palette21)
        self.label_2.setFont(font)
        self.send_cc_link = QPushButton(MoreInfoDialog)
        self.send_cc_link.setObjectName(u"send_cc_link")
        self.send_cc_link.setGeometry(QRect(49, 751, 127, 42))
        self.send_cc_link.setFont(font)
        self.close_button = QPushButton(MoreInfoDialog)
        self.close_button.setObjectName(u"close_button")
        self.close_button.setGeometry(QRect(405, 751, 127, 42))
        self.close_button.setFont(font)
        self.label_5 = QLabel(MoreInfoDialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(142, 547, 140, 20))
        self.label_5.setFont(font)
        self.add_cc_button = QPushButton(MoreInfoDialog)
        self.add_cc_button.setObjectName(u"add_cc_button")
        self.add_cc_button.setGeometry(QRect(241, 751, 127, 42))
        self.add_cc_button.setFont(font)
        self.pricelist_selection = QComboBox(MoreInfoDialog)
        self.pricelist_selection.setObjectName(u"pricelist_selection")
        self.pricelist_selection.setGeometry(QRect(468, 591, 137, 39))
        self.pricelist_selection.setFont(font)
        self.pricelist_selection.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pricelist_selection.setMinimumContentsLength(1)
        self.line = QFrame(MoreInfoDialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(476, 489, 118, 3))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(MoreInfoDialog)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(476, 581, 118, 3))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(MoreInfoDialog)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(476, 401, 118, 3))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.jean_starch_box = QComboBox(MoreInfoDialog)
        self.jean_starch_box.addItem("")
        self.jean_starch_box.addItem("")
        self.jean_starch_box.addItem("")
        self.jean_starch_box.addItem("")
        self.jean_starch_box.setObjectName(u"jean_starch_box")
        self.jean_starch_box.setGeometry(QRect(473, 448, 123, 36))
        self.shirt_starch_box = QComboBox(MoreInfoDialog)
        self.shirt_starch_box.addItem("")
        self.shirt_starch_box.addItem("")
        self.shirt_starch_box.addItem("")
        self.shirt_starch_box.addItem("")
        self.shirt_starch_box.setObjectName(u"shirt_starch_box")
        self.shirt_starch_box.setGeometry(QRect(472, 538, 124, 37))
        self.customer_preferences = QPlainTextEdit(MoreInfoDialog)
        self.customer_preferences.setObjectName(u"customer_preferences")
        self.customer_preferences.setGeometry(QRect(193, 440, 175, 103))

        self.retranslateUi(MoreInfoDialog)

        QMetaObject.connectSlotsByName(MoreInfoDialog)
    # setupUi

    def retranslateUi(self, MoreInfoDialog):
        MoreInfoDialog.setWindowTitle(QCoreApplication.translate("MoreInfoDialog", u"Dialog", None))
        self.delivery_checkbox.setText(QCoreApplication.translate("MoreInfoDialog", u"Delivery Customer", None))
        self.moreinfoheader.setText("")
        self.email_customer.setText(QCoreApplication.translate("MoreInfoDialog", u"Email Customer", None))
        self.fold_shirts_checkbox.setText(QCoreApplication.translate("MoreInfoDialog", u"Fold Shirts", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MoreInfoDialog", u"Brand", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MoreInfoDialog", u"Last 4", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MoreInfoDialog", u"Expiration Date", None));
        self.label_9.setText(QCoreApplication.translate("MoreInfoDialog", u"Shirts Starch", None))
        self.send_notification.setText(QCoreApplication.translate("MoreInfoDialog", u"Send Notification", None))
        self.box_shirts_checkbox.setText(QCoreApplication.translate("MoreInfoDialog", u"Box Shirts", None))
        self.fluff_fold_checkbox.setText(QCoreApplication.translate("MoreInfoDialog", u"Fluff and Fold", None))
        self.save_info_button.setText(QCoreApplication.translate("MoreInfoDialog", u"Save Info", None))
        self.label_8.setText(QCoreApplication.translate("MoreInfoDialog", u"Jeans Starch", None))
        self.billing_checkbox.setText(QCoreApplication.translate("MoreInfoDialog", u"Billing Account Customer", None))
        self.label_3.setText(QCoreApplication.translate("MoreInfoDialog", u"Zip Code", None))
        self.label_4.setText(QCoreApplication.translate("MoreInfoDialog", u"Ste or Apt #", None))
        self.label_6.setText(QCoreApplication.translate("MoreInfoDialog", u"Customer Preferences", None))
        self.label.setText(QCoreApplication.translate("MoreInfoDialog", u"Email Address", None))
        self.label_2.setText(QCoreApplication.translate("MoreInfoDialog", u"Home Address", None))
        self.send_cc_link.setText(QCoreApplication.translate("MoreInfoDialog", u"Send CC Link", None))
        self.close_button.setText(QCoreApplication.translate("MoreInfoDialog", u"Close", None))
        self.label_5.setText(QCoreApplication.translate("MoreInfoDialog", u"Saved Credit Cards", None))
        self.add_cc_button.setText(QCoreApplication.translate("MoreInfoDialog", u"Add Card", None))
#if QT_CONFIG(tooltip)
        self.pricelist_selection.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pricelist_selection.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pricelist_selection.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pricelist_selection.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.pricelist_selection.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.pricelist_selection.setCurrentText("")
        self.pricelist_selection.setPlaceholderText(QCoreApplication.translate("MoreInfoDialog", u"Price Lists", None))
        self.jean_starch_box.setItemText(0, QCoreApplication.translate("MoreInfoDialog", u"No Starch", None))
        self.jean_starch_box.setItemText(1, QCoreApplication.translate("MoreInfoDialog", u"Light Starch", None))
        self.jean_starch_box.setItemText(2, QCoreApplication.translate("MoreInfoDialog", u"Medium Starch", None))
        self.jean_starch_box.setItemText(3, QCoreApplication.translate("MoreInfoDialog", u"Heavy Starch", None))

        self.shirt_starch_box.setItemText(0, QCoreApplication.translate("MoreInfoDialog", u"No Starch", None))
        self.shirt_starch_box.setItemText(1, QCoreApplication.translate("MoreInfoDialog", u"Light Starch", None))
        self.shirt_starch_box.setItemText(2, QCoreApplication.translate("MoreInfoDialog", u"Medium Starch", None))
        self.shirt_starch_box.setItemText(3, QCoreApplication.translate("MoreInfoDialog", u"Heavy Starch", None))

    # retranslateUi

