from PySide6.QtCore import (QCoreApplication, QLocale,
    QMetaObject, QRect, Qt)
from PySide6.QtGui import (QBrush, QColor, QPalette, QFont)
from PySide6.QtWidgets import (QGroupBox, QLabel, QAbstractItemView, QLineEdit, QPushButton,
    QRadioButton, QListView,
    QFrame, 
    QComboBox)


class Ui_payment(object):
    def setupUi(self, payment):
        if not payment.objectName():
            payment.setObjectName(u"payment")
        payment.resize(588, 316)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(170, 85, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush4)
        brush5 = QBrush(QColor(120, 131, 170, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush7 = QBrush(QColor(85, 0, 255, 128))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        brush8 = QBrush(QColor(169, 77, 193, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        brush9 = QBrush(QColor(64, 14, 89, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        payment.setPalette(palette)
        self.frame = QFrame(payment)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(250, 10, 341, 311))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.icostlabel = QLabel(self.frame)
        self.icostlabel.setObjectName(u"icostlabel")
        self.icostlabel.setGeometry(QRect(82, 24, 61, 16))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.icostlabel.setFont(font)
        self.icostlabel.setStyleSheet(u"")
        self.taxeslabel = QLabel(self.frame)
        self.taxeslabel.setObjectName(u"taxeslabel")
        self.taxeslabel.setGeometry(QRect(98, 48, 49, 16))
        self.taxeslabel.setFont(font)
        self.taxeslabel.setStyleSheet(u"")
        self.totalcostlabel = QLabel(self.frame)
        self.totalcostlabel.setObjectName(u"totalcostlabel")
        self.totalcostlabel.setGeometry(QRect(82, 102, 61, 16))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(9)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setKerning(False)
        self.totalcostlabel.setFont(font1)
        self.totalcostlabel.setStyleSheet(u"")
        self.coupons = QComboBox(self.frame)
        self.coupons.addItem("")
        self.coupons.setObjectName(u"coupons")
        self.coupons.setGeometry(QRect(165, 73, 69, 22))
        self.couponslabel = QLabel(self.frame)
        self.couponslabel.setObjectName(u"couponslabel")
        self.couponslabel.setGeometry(QRect(85, 73, 49, 16))
        self.couponslabel.setFont(font)
        self.couponslabel.setStyleSheet(u"")
        self.clearb = QPushButton(self.frame)
        self.clearb.setObjectName(u"clearb")
        self.clearb.setGeometry(QRect(10, 260, 101, 24))
        self.payb = QPushButton(self.frame)
        self.payb.setObjectName(u"payb")
        self.payb.setGeometry(QRect(230, 260, 101, 24))
        self.closeb = QPushButton(self.frame)
        self.closeb.setObjectName(u"closeb")
        self.closeb.setGeometry(QRect(120, 260, 101, 24))
        self.initial_cost_display = QLineEdit(self.frame)
        self.initial_cost_display.setObjectName(u"initial_cost_display")
        self.initial_cost_display.setGeometry(QRect(166, 22, 113, 22))
        self.taxes_display = QLineEdit(self.frame)
        self.taxes_display.setObjectName(u"taxes_display")
        self.taxes_display.setGeometry(QRect(165, 44, 113, 22))
        self.total_cost_display = QLineEdit(self.frame)
        self.total_cost_display.setObjectName(u"total_cost_display")
        self.total_cost_display.setGeometry(QRect(168, 101, 113, 22))
        self.cash_received_label = QLabel(self.frame)
        self.cash_received_label.setObjectName(u"cash_received_label")
        self.cash_received_label.setGeometry(QRect(82, 174, 81, 16))
        self.cash_received_input = QLineEdit(self.frame)
        self.cash_received_input.setObjectName(u"cash_received_input")
        self.cash_received_input.setGeometry(QRect(180, 170, 113, 22))
        self.customer_change_display = QLineEdit(self.frame)
        self.customer_change_display.setObjectName(u"customer_change_display")
        self.customer_change_display.setGeometry(QRect(177, 200, 113, 22))
        self.customer_change_label = QLabel(self.frame)
        self.customer_change_label.setObjectName(u"customer_change_label")
        self.customer_change_label.setGeometry(QRect(61, 201, 104, 16))
        self.selected_tickets_list = QGroupBox(payment)
        self.selected_tickets_list.setObjectName(u"selected_tickets_list")
        self.selected_tickets_list.setGeometry(QRect(130, 0, 121, 321))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        brush10 = QBrush(QColor(255, 85, 255, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.selected_tickets_list.setPalette(palette1)
        self.selected_tickets_list.setAutoFillBackground(True)
        self.selected_tickets_list.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.selected_tickets_list.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)
        self.selected_tickets_list.setFlat(False)
        self.selected_tickets_list.setCheckable(False)
        self.tickets_list = QListView(self.selected_tickets_list)
        self.tickets_list.setObjectName(u"tickets_list")
        self.tickets_list.setGeometry(QRect(0, 10, 121, 311))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush5)
        brush11 = QBrush(QColor(9, 8, 7, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush11)
        brush12 = QBrush(QColor(255, 255, 0, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush12)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        brush13 = QBrush(QColor(51, 102, 153, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        brush14 = QBrush(QColor(255, 0, 0, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush14)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Accent, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.tickets_list.setPalette(palette2)
        self.tickets_list.setMouseTracking(False)
        self.tickets_list.setAcceptDrops(False)
        self.tickets_list.setAutoFillBackground(True)
        self.tickets_list.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.tickets_list.setFrameShape(QFrame.Shape.StyledPanel)
        self.tickets_list.setFrameShadow(QFrame.Shadow.Plain)
        self.tickets_list.setLineWidth(9)
        self.tickets_list.setMidLineWidth(0)
        self.tickets_list.setTabKeyNavigation(True)
        self.tickets_list.setProperty(u"showDropIndicator", False)
        self.tickets_list.setAlternatingRowColors(True)
        self.tickets_list.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tickets_list.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tickets_list.setModelColumn(0)
        self.tickets_list.setUniformItemSizes(True)
        self.tickets_list.setItemAlignment(Qt.AlignmentFlag.AlignLeading)
        self.payment_methods = QGroupBox(payment)
        self.payment_methods.setObjectName(u"payment_methods")
        self.payment_methods.setGeometry(QRect(0, 0, 131, 321))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Accent, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        self.payment_methods.setPalette(palette3)
        self.payment_methods.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.payment_methods.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cashb = QRadioButton(self.payment_methods)
        self.cashb.setObjectName(u"cashb")
        self.cashb.setGeometry(QRect(10, 30, 101, 20))
        self.creditb = QRadioButton(self.payment_methods)
        self.creditb.setObjectName(u"creditb")
        self.creditb.setGeometry(QRect(10, 80, 101, 20))
        self.debitb = QRadioButton(self.payment_methods)
        self.debitb.setObjectName(u"debitb")
        self.debitb.setGeometry(QRect(10, 130, 101, 20))
        self.checkb = QRadioButton(self.payment_methods)
        self.checkb.setObjectName(u"checkb")
        self.checkb.setGeometry(QRect(10, 180, 101, 20))
        self.otherb = QRadioButton(self.payment_methods)
        self.otherb.setObjectName(u"otherb")
        self.otherb.setGeometry(QRect(10, 230, 101, 20))
        self.unableb = QRadioButton(self.payment_methods)
        self.unableb.setObjectName(u"unableb")
        self.unableb.setGeometry(QRect(10, 280, 101, 20))

        self.retranslateUi(payment)

        QMetaObject.connectSlotsByName(payment)
    # setupUi

    def retranslateUi(self, payment):
        payment.setWindowTitle(QCoreApplication.translate("payment", u"Form", None))
        self.icostlabel.setText(QCoreApplication.translate("payment", u"Initial Cost", None))
        self.taxeslabel.setText(QCoreApplication.translate("payment", u"Taxes", None))
        self.totalcostlabel.setText(QCoreApplication.translate("payment", u"Total Cost", None))
        self.coupons.setItemText(0, QCoreApplication.translate("payment", u"5$ Off", None))

        self.couponslabel.setText(QCoreApplication.translate("payment", u"Coupons", None))
        self.clearb.setText(QCoreApplication.translate("payment", u"Clear", None))
        self.payb.setText(QCoreApplication.translate("payment", u"Pay", None))
        self.closeb.setText(QCoreApplication.translate("payment", u"Cancel + Close", None))
        self.cash_received_label.setText(QCoreApplication.translate("payment", u"Cash Received", None))
        self.customer_change_label.setText(QCoreApplication.translate("payment", u"Customers Change", None))
        self.selected_tickets_list.setTitle(QCoreApplication.translate("payment", u"Orders Being Paid", None))
        self.payment_methods.setTitle(QCoreApplication.translate("payment", u"Payment Methods", None))
        self.cashb.setText(QCoreApplication.translate("payment", u"  Cash", None))
        self.creditb.setText(QCoreApplication.translate("payment", u"  Credit Card", None))
        self.debitb.setText(QCoreApplication.translate("payment", u"  Debit Card", None))
        self.checkb.setText(QCoreApplication.translate("payment", u"  Check", None))
        self.otherb.setText(QCoreApplication.translate("payment", u"  Other", None))
        self.unableb.setText(QCoreApplication.translate("payment", u"Unable To Pay", None))
    # retranslateUi

