from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, Qt)
from PySide6.QtGui import (QBrush, QColor, QFont, QPalette)
from PySide6.QtWidgets import (QLabel, QDateTimeEdit, QAbstractSpinBox, QDial,
    QPushButton,
    QComboBox, QPlainTextEdit, QSpinBox)



class Ui_QuickTicketCreation(object):
    def setupUi(self, QuickTicketCreation):
        if not QuickTicketCreation.objectName():
            QuickTicketCreation.setObjectName(u"QuickTicketCreation")
        QuickTicketCreation.resize(647, 491)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        QuickTicketCreation.setPalette(palette)
        self.ttlabel = QLabel(QuickTicketCreation)
        self.ttlabel.setObjectName(u"ttlabel")
        self.ttlabel.setGeometry(QRect(23, 93, 71, 16))
        self.qtdlabel = QLabel(QuickTicketCreation)
        self.qtdlabel.setObjectName(u"qtdlabel")
        self.qtdlabel.setGeometry(QRect(327, 96, 71, 16))
        self.ttselection = QComboBox(QuickTicketCreation)
        self.ttselection.setObjectName(u"ttselection")
        self.ttselection.setGeometry(QRect(19, 112, 111, 25))
        self.ttselection_2 = QComboBox(QuickTicketCreation)
        self.ttselection_2.setObjectName(u"ttselection_2")
        self.ttselection_2.setGeometry(QRect(21, 204, 111, 25))
        self.ttselection_3 = QComboBox(QuickTicketCreation)
        self.ttselection_3.setObjectName(u"ttselection_3")
        self.ttselection_3.setGeometry(QRect(21, 290, 111, 25))
        self.qtninput = QPlainTextEdit(QuickTicketCreation)
        self.qtninput.setObjectName(u"qtninput")
        self.qtninput.setGeometry(QRect(458, 111, 171, 61))
        self.qtninput_2 = QPlainTextEdit(QuickTicketCreation)
        self.qtninput_2.setObjectName(u"qtninput_2")
        self.qtninput_2.setGeometry(QRect(458, 201, 171, 61))
        self.qtninput_3 = QPlainTextEdit(QuickTicketCreation)
        self.qtninput_3.setObjectName(u"qtninput_3")
        self.qtninput_3.setGeometry(QRect(458, 291, 171, 61))
        self.qtnlabel = QLabel(QuickTicketCreation)
        self.qtnlabel.setObjectName(u"qtnlabel")
        self.qtnlabel.setGeometry(QRect(468, 91, 49, 16))
        self.ttlabel_2 = QLabel(QuickTicketCreation)
        self.ttlabel_2.setObjectName(u"ttlabel_2")
        self.ttlabel_2.setGeometry(QRect(20, 180, 71, 16))
        self.ttlabel_3 = QLabel(QuickTicketCreation)
        self.ttlabel_3.setObjectName(u"ttlabel_3")
        self.ttlabel_3.setGeometry(QRect(20, 270, 71, 16))
        self.qtdlabel_2 = QLabel(QuickTicketCreation)
        self.qtdlabel_2.setObjectName(u"qtdlabel_2")
        self.qtdlabel_2.setGeometry(QRect(327, 187, 71, 16))
        self.qtdlabel_3 = QLabel(QuickTicketCreation)
        self.qtdlabel_3.setObjectName(u"qtdlabel_3")
        self.qtdlabel_3.setGeometry(QRect(327, 277, 71, 16))
        self.qtnlabel_2 = QLabel(QuickTicketCreation)
        self.qtnlabel_2.setObjectName(u"qtnlabel_2")
        self.qtnlabel_2.setGeometry(QRect(468, 181, 49, 16))
        self.qtnlabel_3 = QLabel(QuickTicketCreation)
        self.qtnlabel_3.setObjectName(u"qtnlabel_3")
        self.qtnlabel_3.setGeometry(QRect(468, 271, 49, 16))
        self.qtclosebutton = QPushButton(QuickTicketCreation)
        self.qtclosebutton.setObjectName(u"qtclosebutton")
        self.qtclosebutton.setGeometry(QRect(388, 381, 111, 41))
        self.qtsandpbutton = QPushButton(QuickTicketCreation)
        self.qtsandpbutton.setObjectName(u"qtsandpbutton")
        self.qtsandpbutton.setGeometry(QRect(518, 381, 111, 41))
        self.atninput = QPlainTextEdit(QuickTicketCreation)
        self.atninput.setObjectName(u"atninput")
        self.atninput.setGeometry(QRect(20, 360, 291, 101))
        self.atnlabel = QLabel(QuickTicketCreation)
        self.atnlabel.setObjectName(u"atnlabel")
        self.atnlabel.setGeometry(QRect(20, 340, 111, 16))
        self.qtpselection_2 = QSpinBox(QuickTicketCreation)
        self.qtpselection_2.setObjectName(u"qtpselection_2")
        self.qtpselection_2.setGeometry(QRect(144, 203, 75, 25))
        self.qtpselection_3 = QSpinBox(QuickTicketCreation)
        self.qtpselection_3.setObjectName(u"qtpselection_3")
        self.qtpselection_3.setGeometry(QRect(142, 289, 75, 25))
        self.qtpselection = QSpinBox(QuickTicketCreation)
        self.qtpselection.setObjectName(u"qtpselection")
        self.qtpselection.setGeometry(QRect(145, 111, 75, 25))
        self.qtplabel_3 = QLabel(QuickTicketCreation)
        self.qtplabel_3.setObjectName(u"qtplabel_3")
        self.qtplabel_3.setGeometry(QRect(145, 272, 49, 16))
        self.qtplabel_2 = QLabel(QuickTicketCreation)
        self.qtplabel_2.setObjectName(u"qtplabel_2")
        self.qtplabel_2.setGeometry(QRect(148, 185, 49, 16))
        self.qtplabel = QLabel(QuickTicketCreation)
        self.qtplabel.setObjectName(u"qtplabel")
        self.qtplabel.setGeometry(QRect(149, 95, 49, 16))
        self.dateTimeEdit_3 = QDateTimeEdit(QuickTicketCreation)
        self.dateTimeEdit_3.setObjectName(u"dateTimeEdit_3")
        self.dateTimeEdit_3.setGeometry(QRect(322, 290, 131, 25))
        self.dateTimeEdit_3.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.dateTimeEdit_3.setProperty(u"showGroupSeparator", False)
        self.dateTimeEdit_3.setCalendarPopup(True)
        self.dateTimeEdit_3.setCurrentSectionIndex(0)
        self.dial_3 = QDial(QuickTicketCreation)
        self.dial_3.setObjectName(u"dial_3")
        self.dial_3.setGeometry(QRect(391, 314, 66, 61))
        self.dial_3.setMaximum(1000)
        self.dial_3.setSingleStep(2)
        self.dial_3.setWrapping(True)
        self.dial_3.setNotchTarget(27.699999999999999)
        self.dial_3.setNotchesVisible(True)
        self.dateTimeEdit_2 = QDateTimeEdit(QuickTicketCreation)
        self.dateTimeEdit_2.setObjectName(u"dateTimeEdit_2")
        self.dateTimeEdit_2.setGeometry(QRect(322, 201, 131, 25))
        self.dateTimeEdit_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.dateTimeEdit_2.setProperty(u"showGroupSeparator", False)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setCurrentSectionIndex(0)
        self.dateTimeEdit_1 = QDateTimeEdit(QuickTicketCreation)
        self.dateTimeEdit_1.setObjectName(u"dateTimeEdit_1")
        self.dateTimeEdit_1.setGeometry(QRect(321, 111, 131, 25))
        self.dateTimeEdit_1.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.dateTimeEdit_1.setProperty(u"showGroupSeparator", False)
        self.dateTimeEdit_1.setCalendarPopup(True)
        self.dateTimeEdit_1.setCurrentSectionIndex(0)
        self.dial_2 = QDial(QuickTicketCreation)
        self.dial_2.setObjectName(u"dial_2")
        self.dial_2.setGeometry(QRect(391, 225, 67, 61))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.dial_2.setPalette(palette1)
        self.dial_2.setStyleSheet(u"color (0, 0, 0)")
        self.dial_2.setMaximum(1000)
        self.dial_2.setSingleStep(2)
        self.dial_2.setInvertedAppearance(False)
        self.dial_2.setInvertedControls(False)
        self.dial_2.setWrapping(True)
        self.dial_2.setNotchTarget(27.699999999999999)
        self.dial_2.setNotchesVisible(True)
        self.dial_1 = QDial(QuickTicketCreation)
        self.dial_1.setObjectName(u"dial_1")
        self.dial_1.setGeometry(QRect(394, 138, 63, 61))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.dial_1.setPalette(palette2)
        self.dial_1.setAutoFillBackground(False)
        self.dial_1.setStyleSheet(u"color rgb(85, 0, 255)")
        self.dial_1.setMaximum(1000)
        self.dial_1.setSingleStep(2)
        self.dial_1.setWrapping(True)
        self.dial_1.setNotchTarget(27.699999999999999)
        self.dial_1.setNotchesVisible(True)
        self.quickticket = QLabel(QuickTicketCreation)
        self.quickticket.setObjectName(u"quickticket")
        self.quickticket.setGeometry(QRect(110, 10, 411, 61))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.quickticket.setPalette(palette3)
        font = QFont()
        font.setFamilies([u"Ravie"])
        font.setPointSize(36)
        self.quickticket.setFont(font)
        self.quickticket.setAutoFillBackground(False)
        self.quickticket.setTextFormat(Qt.TextFormat.RichText)
        self.quickticket.setOpenExternalLinks(False)
        self.createdetailedticket = QPushButton(QuickTicketCreation)
        self.createdetailedticket.setObjectName(u"createdetailedticket")
        self.createdetailedticket.setGeometry(QRect(398, 421, 221, 41))
        self.comboBox = QComboBox(QuickTicketCreation)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(224, 112, 87, 25))
        self.comboBox_2 = QComboBox(QuickTicketCreation)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(223, 202, 87, 25))
        self.comboBox_3 = QComboBox(QuickTicketCreation)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(225, 290, 87, 25))
        self.starch_label3 = QLabel(QuickTicketCreation)
        self.starch_label3.setObjectName(u"starch_label3")
        self.starch_label3.setGeometry(QRect(230, 272, 49, 16))
        self.starch_label2 = QLabel(QuickTicketCreation)
        self.starch_label2.setObjectName(u"starch_label2")
        self.starch_label2.setGeometry(QRect(227, 182, 49, 16))
        self.starch_label1 = QLabel(QuickTicketCreation)
        self.starch_label1.setObjectName(u"starch_label1")
        self.starch_label1.setGeometry(QRect(230, 94, 49, 16))

        self.retranslateUi(QuickTicketCreation)

        QMetaObject.connectSlotsByName(QuickTicketCreation)
    # setupUi

    def retranslateUi(self, QuickTicketCreation):
        QuickTicketCreation.setWindowTitle(QCoreApplication.translate("QuickTicketCreation", u"Form", None))
        self.ttlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.qtdlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Date + Time", None))
        self.qtnlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.ttlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.ttlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.qtdlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Date + Time", None))
        self.qtdlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Date + Time", None))
        self.qtnlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.qtnlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.qtclosebutton.setText(QCoreApplication.translate("QuickTicketCreation", u"Close", None))
        self.qtsandpbutton.setText(QCoreApplication.translate("QuickTicketCreation", u"Create + Print", None))
        self.atnlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes For All Tickets", None))
        self.qtplabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
        self.qtplabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
        self.qtplabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
        self.quickticket.setText(QCoreApplication.translate("QuickTicketCreation", u"<html><head/><body><p><span style=\" color:#5500ff;\">Quick Ticket</span></p></body></html>", None))
        self.createdetailedticket.setText(QCoreApplication.translate("QuickTicketCreation", u"Create Detailed Ticket", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("QuickTicketCreation", u"No Starch", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("QuickTicketCreation", u"Sizing", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("QuickTicketCreation", u"Light", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("QuickTicketCreation", u"Medium", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("QuickTicketCreation", u"Heavy", None))

        self.comboBox_2.setItemText(0, QCoreApplication.translate("QuickTicketCreation", u"No Starch", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("QuickTicketCreation", u"Sizing", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("QuickTicketCreation", u"Light", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("QuickTicketCreation", u"Medium", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("QuickTicketCreation", u"Heavy", None))

        self.comboBox_3.setItemText(0, QCoreApplication.translate("QuickTicketCreation", u"No Starch", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("QuickTicketCreation", u"Sizing", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("QuickTicketCreation", u"Light", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("QuickTicketCreation", u"Medium", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("QuickTicketCreation", u"Heavy", None))

        self.starch_label3.setText(QCoreApplication.translate("QuickTicketCreation", u"Starch", None))
        self.starch_label2.setText(QCoreApplication.translate("QuickTicketCreation", u"Starch", None))
        self.starch_label1.setText(QCoreApplication.translate("QuickTicketCreation", u"Starch", None))
    # retranslateUi

