from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect, Signal, QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform,
    QAction)
from PySide6.QtWidgets import (QApplication, QGroupBox, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTextEdit,
    QTreeWidget, QTreeWidgetItem, QWidget, QDialog, QFrame, 
    QListWidget, QListWidgetItem, QComboBox, QDateEdit,
    QPlainTextEdit, QSpinBox, QTextBrowser, QMenu, QVBoxLayout, QGridLayout, QStackedWidget)
import sqlite3

import images_rc

class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.resize(974, 965)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        Main.setPalette(palette)
        self.actionAdd_Image = QAction(Main)
        self.actionAdd_Image.setObjectName(u"actionAdd_Image")
        self.actionAdd_Image.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.centralwidget = QWidget(Main)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(-20, -10, 1061, 61))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.ncbutton = QPushButton(self.frame)
        self.ncbutton.setObjectName(u"ncbutton")
        self.ncbutton.setGeometry(QRect(50, 20, 121, 31))
        self.ncbutton.setMouseTracking(False)
        self.ncbutton.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.ncbutton.setAcceptDrops(False)
        self.ncbutton.setAutoRepeatDelay(301)
        self.ttcbutton = QPushButton(self.frame)
        self.ttcbutton.setObjectName(u"ttcbutton")
        self.ttcbutton.setGeometry(QRect(240, 20, 121, 31))
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(440, 20, 121, 31))
        self.gandccbutton = QPushButton(self.frame)
        self.gandccbutton.setObjectName(u"gandccbutton")
        self.gandccbutton.setGeometry(QRect(630, 20, 151, 31))
        self.tocbutton = QPushButton(self.frame)
        self.tocbutton.setObjectName(u"tocbutton")
        self.tocbutton.setGeometry(QRect(840, 20, 131, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-50, 50, 1181, 901))
        self.label.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.label.setToolTipDuration(-2)
        self.label.setLocale(QLocale(QLocale.Ewe, QLocale.Ghana))
        self.label.setPixmap(QPixmap(u":/images/Logo #2.jpg"))
        Main.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Main)
        self.statusbar.setObjectName(u"statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)

        self.ncbutton.setDefault(False)


        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"MainWindow", None))
        self.actionAdd_Image.setText(QCoreApplication.translate("Main", u"Add Image", None))
#if QT_CONFIG(shortcut)
        self.actionAdd_Image.setShortcut(QCoreApplication.translate("Main", u"Ctrl+Alt+I", None))
#endif // QT_CONFIG(shortcut)
        self.ncbutton.setText(QCoreApplication.translate("Main", u"Next Customer", None))
        self.ttcbutton.setText(QCoreApplication.translate("Main", u"Ticket Type Creation", None))
        self.pushButton.setText(QCoreApplication.translate("Main", u"Garment Pricing", None))
        self.gandccbutton.setText(QCoreApplication.translate("Main", u"Garment + Color Creation", None))
        self.tocbutton.setText(QCoreApplication.translate("Main", u"Ticket Options Creation", None))
        self.label.setText("")
    # retranslateUi







class Ui_CustomerSearch(object):
    def setupUi(self, CustomerSearch):
        if not CustomerSearch.objectName():
            CustomerSearch.setObjectName(u"CustomerSearch")
        CustomerSearch.resize(640, 404)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        CustomerSearch.setPalette(palette)
        self.pnsearch = QLineEdit(CustomerSearch)
        self.pnsearch.setObjectName(u"pnsearch")
        self.pnsearch.setGeometry(QRect(50, 160, 113, 22))
        self.lnsearch = QLineEdit(CustomerSearch)
        self.lnsearch.setObjectName(u"lnsearch")
        self.lnsearch.setGeometry(QRect(50, 60, 113, 22))
        self.lnlabel = QLabel(CustomerSearch)
        self.lnlabel.setObjectName(u"lnlabel")
        self.lnlabel.setGeometry(QRect(50, 40, 81, 16))
        self.pnlabel = QLabel(CustomerSearch)
        self.pnlabel.setObjectName(u"pnlabel")
        self.pnlabel.setGeometry(QRect(50, 140, 49, 16))
        self.resultslist = QTreeWidget(CustomerSearch)
        self.resultslist.setObjectName(u"resultslist")
        self.resultslist.setGeometry(QRect(170, 40, 361, 211))
        self.fnsearch = QLineEdit(CustomerSearch)
        self.fnsearch.setObjectName(u"fnsearch")
        self.fnsearch.setGeometry(QRect(50, 110, 113, 22))
        self.fnlabel = QLabel(CustomerSearch)
        self.fnlabel.setObjectName(u"fnlabel")
        self.fnlabel.setGeometry(QRect(50, 90, 71, 16))
        self.ncbutton = QPushButton(CustomerSearch)
        self.ncbutton.setObjectName(u"ncbutton")
        self.ncbutton.setGeometry(QRect(170, 270, 101, 31))
        self.searchbutton = QPushButton(CustomerSearch)
        self.searchbutton.setObjectName(u"searchbutton")
        self.searchbutton.setGeometry(QRect(310, 270, 91, 31))
        self.closebutton = QPushButton(CustomerSearch)
        self.closebutton.setObjectName(u"closebutton")
        self.closebutton.setGeometry(QRect(440, 270, 91, 31))

        self.retranslateUi(CustomerSearch)

        QMetaObject.connectSlotsByName(CustomerSearch)
    # setupUi

    def retranslateUi(self, CustomerSearch):
        CustomerSearch.setWindowTitle(QCoreApplication.translate("CustomerSearch", u"Dialog", None))
        self.lnlabel.setText(QCoreApplication.translate("CustomerSearch", u"Last Name:", None))
        self.pnlabel.setText(QCoreApplication.translate("CustomerSearch", u"Phone#:", None))
        ___qtreewidgetitem = self.resultslist.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("CustomerSearch", u"Phone#", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("CustomerSearch", u"Name                                                                                                        ", None));
        self.fnlabel.setText(QCoreApplication.translate("CustomerSearch", u"First Name:", None))
        self.ncbutton.setText(QCoreApplication.translate("CustomerSearch", u"New Customer", None))
        self.searchbutton.setText(QCoreApplication.translate("CustomerSearch", u"Search", None))
        self.closebutton.setText(QCoreApplication.translate("CustomerSearch", u"Close", None))
    # retranslateUi



class Ui_CustomerAccount(object):
    def setupUi(self, CustomerAccount):
        if not CustomerAccount.objectName():
            CustomerAccount.setObjectName(u"CustomerAccount")
        CustomerAccount.resize(1310, 956)
        self.centralwidget = QWidget(CustomerAccount)
        self.centralwidget.setObjectName(u"centralwidget")
        self.catabs = QTabWidget(self.centralwidget)
        self.catabs.setObjectName(u"catabs")
        self.catabs.setGeometry(QRect(50, 30, 1171, 811))
        self.catabs.setTabShape(QTabWidget.TabShape.Rounded)
        self.catabs.setElideMode(Qt.TextElideMode.ElideNone)
        self.catabs.setTabsClosable(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.cinfobox = QGroupBox(self.tab)
        self.cinfobox.setObjectName(u"cinfobox")
        self.cinfobox.setGeometry(QRect(0, 0, 231, 231))
        self.lninput = QLineEdit(self.cinfobox)
        self.lninput.setObjectName(u"lninput")
        self.lninput.setGeometry(QRect(10, 40, 101, 22))
        self.lnlabel = QLabel(self.cinfobox)
        self.lnlabel.setObjectName(u"lnlabel")
        self.lnlabel.setGeometry(QRect(10, 20, 111, 16))
        self.fnlabel = QLabel(self.cinfobox)
        self.fnlabel.setObjectName(u"fnlabel")
        self.fnlabel.setGeometry(QRect(120, 20, 101, 16))
        self.fninput = QLineEdit(self.cinfobox)
        self.fninput.setObjectName(u"fninput")
        self.fninput.setGeometry(QRect(122, 40, 101, 22))
        self.pnlabel = QLabel(self.cinfobox)
        self.pnlabel.setObjectName(u"pnlabel")
        self.pnlabel.setGeometry(QRect(10, 70, 91, 16))
        self.pninput = QLineEdit(self.cinfobox)
        self.pninput.setObjectName(u"pninput")
        self.pninput.setGeometry(QRect(10, 90, 211, 22))
        self.ninput = QTextEdit(self.cinfobox)
        self.ninput.setObjectName(u"ninput")
        self.ninput.setGeometry(QRect(10, 140, 211, 81))
        self.nlabel = QLabel(self.cinfobox)
        self.nlabel.setObjectName(u"nlabel")
        self.nlabel.setGeometry(QRect(10, 120, 61, 16))
        self.ctlist = QTreeWidget(self.tab)
        self.ctlist.setObjectName(u"ctlist")
        self.ctlist.setGeometry(QRect(240, 10, 641, 581))
        self.qtbutton = QPushButton(self.tab)
        self.qtbutton.setObjectName(u"qtbutton")
        self.qtbutton.setGeometry(QRect(0, 360, 75, 24))
        self.paybutton = QPushButton(self.tab)
        self.paybutton.setObjectName(u"paybutton")
        self.paybutton.setGeometry(QRect(80, 360, 75, 24))
        self.puandpbutton = QPushButton(self.tab)
        self.puandpbutton.setObjectName(u"puandpbutton")
        self.puandpbutton.setGeometry(QRect(160, 360, 81, 24))
        self.pushButton_4 = QPushButton(self.tab)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(0, 240, 75, 24))
        self.pushButton_5 = QPushButton(self.tab)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(80, 240, 75, 24))
        self.pushButton_6 = QPushButton(self.tab)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(160, 240, 75, 24))
        self.pushButton_7 = QPushButton(self.tab)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(0, 270, 75, 24))
        self.pushButton_8 = QPushButton(self.tab)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(80, 270, 75, 24))
        self.pushButton_9 = QPushButton(self.tab)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(160, 270, 75, 24))
        self.catabs.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_10 = QPushButton(self.tab_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(160, 270, 75, 24))
        self.qtbutton_2 = QPushButton(self.tab_2)
        self.qtbutton_2.setObjectName(u"qtbutton_2")
        self.qtbutton_2.setGeometry(QRect(0, 360, 75, 24))
        self.cinfobox_2 = QGroupBox(self.tab_2)
        self.cinfobox_2.setObjectName(u"cinfobox_2")
        self.cinfobox_2.setGeometry(QRect(0, 0, 231, 231))
        self.fninput_2 = QLineEdit(self.cinfobox_2)
        self.fninput_2.setObjectName(u"fninput_2")
        self.fninput_2.setGeometry(QRect(122, 40, 101, 22))
        self.lnlabel_2 = QLabel(self.cinfobox_2)
        self.lnlabel_2.setObjectName(u"lnlabel_2")
        self.lnlabel_2.setGeometry(QRect(10, 20, 111, 16))
        self.pninput_2 = QLineEdit(self.cinfobox_2)
        self.pninput_2.setObjectName(u"pninput_2")
        self.pninput_2.setGeometry(QRect(10, 90, 211, 22))
        self.lninput_2 = QLineEdit(self.cinfobox_2)
        self.lninput_2.setObjectName(u"lninput_2")
        self.lninput_2.setGeometry(QRect(10, 40, 101, 22))
        self.nlabel_2 = QLabel(self.cinfobox_2)
        self.nlabel_2.setObjectName(u"nlabel_2")
        self.nlabel_2.setGeometry(QRect(10, 120, 61, 16))
        self.ninput_2 = QTextEdit(self.cinfobox_2)
        self.ninput_2.setObjectName(u"ninput_2")
        self.ninput_2.setGeometry(QRect(10, 140, 211, 81))
        self.pnlabel_2 = QLabel(self.cinfobox_2)
        self.pnlabel_2.setObjectName(u"pnlabel_2")
        self.pnlabel_2.setGeometry(QRect(10, 70, 91, 16))
        self.fnlabel_2 = QLabel(self.cinfobox_2)
        self.fnlabel_2.setObjectName(u"fnlabel_2")
        self.fnlabel_2.setGeometry(QRect(120, 20, 101, 16))
        self.pushButton_11 = QPushButton(self.tab_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(80, 240, 75, 24))
        self.pushButton_12 = QPushButton(self.tab_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(160, 240, 75, 24))
        self.ctlist_2 = QTreeWidget(self.tab_2)
        self.ctlist_2.setObjectName(u"ctlist_2")
        self.ctlist_2.setGeometry(QRect(240, 10, 641, 581))
        self.pushButton_13 = QPushButton(self.tab_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(80, 270, 75, 24))
        self.pushButton_14 = QPushButton(self.tab_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(0, 240, 75, 24))
        self.puandpbutton_2 = QPushButton(self.tab_2)
        self.puandpbutton_2.setObjectName(u"puandpbutton_2")
        self.puandpbutton_2.setGeometry(QRect(160, 360, 81, 24))
        self.pushButton_15 = QPushButton(self.tab_2)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(0, 270, 75, 24))
        self.paybutton_2 = QPushButton(self.tab_2)
        self.paybutton_2.setObjectName(u"paybutton_2")
        self.paybutton_2.setGeometry(QRect(80, 360, 75, 24))
        self.catabs.addTab(self.tab_2, "")
        CustomerAccount.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(CustomerAccount)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1310, 33))
        CustomerAccount.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(CustomerAccount)
        self.statusbar.setObjectName(u"statusbar")
        CustomerAccount.setStatusBar(self.statusbar)

        self.retranslateUi(CustomerAccount)

        self.catabs.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(CustomerAccount)
    # setupUi

    def retranslateUi(self, CustomerAccount):
        CustomerAccount.setWindowTitle(QCoreApplication.translate("CustomerAccount", u"MainWindow", None))
        self.cinfobox.setTitle(QCoreApplication.translate("CustomerAccount", u"Customer Information", None))
        self.lnlabel.setText(QCoreApplication.translate("CustomerAccount", u"Last Name:", None))
        self.fnlabel.setText(QCoreApplication.translate("CustomerAccount", u"First Name:", None))
        self.pnlabel.setText(QCoreApplication.translate("CustomerAccount", u"Phone#:", None))
        self.nlabel.setText(QCoreApplication.translate("CustomerAccount", u"Notes:", None))
        ___qtreewidgetitem = self.ctlist.headerItem()
        ___qtreewidgetitem.setText(5, QCoreApplication.translate("CustomerAccount", u"Billing Invoice#", None));
        ___qtreewidgetitem.setText(4, QCoreApplication.translate("CustomerAccount", u"Ticket#", None));
        ___qtreewidgetitem.setText(3, QCoreApplication.translate("CustomerAccount", u"Ticket Type", None));
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("CustomerAccount", u"Drop Off Date", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("CustomerAccount", u"Picked up + Paid", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("CustomerAccount", u"Paid", None));
        self.qtbutton.setText(QCoreApplication.translate("CustomerAccount", u"Quick Ticket", None))
        self.paybutton.setText(QCoreApplication.translate("CustomerAccount", u"Pay", None))
        self.puandpbutton.setText(QCoreApplication.translate("CustomerAccount", u"Pick up + Pay", None))
        self.pushButton_4.setText(QCoreApplication.translate("CustomerAccount", u"Dry Clean", None))
        self.pushButton_5.setText(QCoreApplication.translate("CustomerAccount", u"Laundry", None))
        self.pushButton_6.setText(QCoreApplication.translate("CustomerAccount", u"Household", None))
        self.pushButton_7.setText(QCoreApplication.translate("CustomerAccount", u"Alteration", None))
        self.pushButton_8.setText(QCoreApplication.translate("CustomerAccount", u"Press Only", None))
        self.pushButton_9.setText(QCoreApplication.translate("CustomerAccount", u"Fluff + Fold", None))
        self.catabs.setTabText(self.catabs.indexOf(self.tab), QCoreApplication.translate("CustomerAccount", u"Customer1", None))
        self.pushButton_10.setText(QCoreApplication.translate("CustomerAccount", u"Fluff + Fold", None))
        self.qtbutton_2.setText(QCoreApplication.translate("CustomerAccount", u"Quick Ticket", None))
        self.cinfobox_2.setTitle(QCoreApplication.translate("CustomerAccount", u"Customer Information", None))
        self.lnlabel_2.setText(QCoreApplication.translate("CustomerAccount", u"Last Name:", None))
        self.nlabel_2.setText(QCoreApplication.translate("CustomerAccount", u"Notes:", None))
        self.pnlabel_2.setText(QCoreApplication.translate("CustomerAccount", u"Phone#:", None))
        self.fnlabel_2.setText(QCoreApplication.translate("CustomerAccount", u"First Name:", None))
        self.pushButton_11.setText(QCoreApplication.translate("CustomerAccount", u"Laundry", None))
        self.pushButton_12.setText(QCoreApplication.translate("CustomerAccount", u"Household", None))
        ___qtreewidgetitem1 = self.ctlist_2.headerItem()
        ___qtreewidgetitem1.setText(5, QCoreApplication.translate("CustomerAccount", u"Billing Invoice#", None));
        ___qtreewidgetitem1.setText(4, QCoreApplication.translate("CustomerAccount", u"Ticket#", None));
        ___qtreewidgetitem1.setText(3, QCoreApplication.translate("CustomerAccount", u"Ticket Type", None));
        ___qtreewidgetitem1.setText(2, QCoreApplication.translate("CustomerAccount", u"Drop Off Date", None));
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("CustomerAccount", u"Picked up + Paid", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("CustomerAccount", u"Paid", None));
        self.pushButton_13.setText(QCoreApplication.translate("CustomerAccount", u"Press Only", None))
        self.pushButton_14.setText(QCoreApplication.translate("CustomerAccount", u"Dry Clean", None))
        self.puandpbutton_2.setText(QCoreApplication.translate("CustomerAccount", u"Pick up + Pay", None))
        self.pushButton_15.setText(QCoreApplication.translate("CustomerAccount", u"Alteration", None))
        self.paybutton_2.setText(QCoreApplication.translate("CustomerAccount", u"Pay", None))
        self.catabs.setTabText(self.catabs.indexOf(self.tab_2), QCoreApplication.translate("CustomerAccount", u"Customer2", None))
    # retranslateUi

class Ui_CustomerAccount2(object):
    def setupUi(self, CustomerAccount2):
        if not CustomerAccount2.objectName():
            CustomerAccount2.setObjectName(u"CustomerAccount2")
        CustomerAccount2.resize(1545, 1247)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        CustomerAccount2.setPalette(palette)
        self.centralwidget = QWidget(CustomerAccount2)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pageswidget = QStackedWidget(self.centralwidget)
        self.pageswidget.setObjectName(u"pageswidget")
        self.pageswidget.setGeometry(QRect(10, 40, 1441, 831))
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.puandpbutton = QPushButton(self.page1)
        self.puandpbutton.setObjectName(u"puandpbutton")
        self.puandpbutton.setGeometry(QRect(280, 770, 101, 41))
        self.paybutton = QPushButton(self.page1)
        self.paybutton.setObjectName(u"paybutton")
        self.paybutton.setGeometry(QRect(140, 770, 101, 41))
        self.ctlist = QTreeWidget(self.page1)
        self.ctlist.setObjectName(u"ctlist")
        self.ctlist.setGeometry(QRect(390, 30, 881, 781))
        self.qtbutton = QPushButton(self.page1)
        self.qtbutton.setObjectName(u"qtbutton")
        self.qtbutton.setGeometry(QRect(0, 770, 101, 41))
        self.tabWidget = QTabWidget(self.page1)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 10, 381, 381))
        self.tab1 = QWidget()
        self.tab1.setObjectName(u"tab1")
        self.FirstName = QLabel(self.tab1)
        self.FirstName.setObjectName(u"FirstName")
        self.FirstName.setGeometry(QRect(230, 20, 71, 16))
        self.PhoneNumber = QLabel(self.tab1)
        self.PhoneNumber.setObjectName(u"PhoneNumber")
        self.PhoneNumber.setGeometry(QRect(150, 90, 81, 16))
        self.LastNameInput = QLineEdit(self.tab1)
        self.LastNameInput.setObjectName(u"LastNameInput")
        self.LastNameInput.setGeometry(QRect(40, 50, 141, 31))
        self.NotesInput = QPlainTextEdit(self.tab1)
        self.NotesInput.setObjectName(u"NotesInput")
        self.NotesInput.setGeometry(QRect(40, 200, 301, 131))
        self.PhoneNumberInput = QLineEdit(self.tab1)
        self.PhoneNumberInput.setObjectName(u"PhoneNumberInput")
        self.PhoneNumberInput.setGeometry(QRect(90, 120, 201, 31))
        self.LastName = QLabel(self.tab1)
        self.LastName.setObjectName(u"LastName")
        self.LastName.setGeometry(QRect(40, 20, 61, 16))
        self.FirstNameInput = QLineEdit(self.tab1)
        self.FirstNameInput.setObjectName(u"FirstNameInput")
        self.FirstNameInput.setGeometry(QRect(222, 50, 121, 31))
        self.Notes = QLabel(self.tab1)
        self.Notes.setObjectName(u"Notes")
        self.Notes.setGeometry(QRect(180, 170, 49, 16))
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.lineEdit_9 = QLineEdit(self.tab_2)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(48, 785, 141, 31))
        self.lineEdit_7 = QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(98, 855, 201, 31))
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(48, 755, 61, 16))
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(238, 755, 71, 16))
        self.lineEdit_8 = QLineEdit(self.tab_2)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(230, 785, 121, 31))
        self.tabWidget.addTab(self.tab_2, "")
        self.label_17 = QLabel(self.page1)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(120, 0, 49, 16))
        self.pushButton = QPushButton(self.page1)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(140, 420, 101, 41))
        self.pushButton_16 = QPushButton(self.page1)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(1270, 30, 151, 51))
        self.gridLayoutWidget_2 = QWidget(self.page1)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(0, 469, 371, 291))
        self.tickettypebuttongrid_2 = QGridLayout(self.gridLayoutWidget_2)
        self.tickettypebuttongrid_2.setObjectName(u"tickettypebuttongrid_2")
        self.tickettypebuttongrid_2.setContentsMargins(0, 0, 0, 0)
        self.pageswidget.addWidget(self.page1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.ctlist_2 = QTreeWidget(self.page_2)
        self.ctlist_2.setObjectName(u"ctlist_2")
        self.ctlist_2.setGeometry(QRect(390, 30, 881, 781))
        self.tabWidget_2 = QTabWidget(self.page_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 10, 381, 381))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.FirstName_2 = QLabel(self.tab_3)
        self.FirstName_2.setObjectName(u"FirstName_2")
        self.FirstName_2.setGeometry(QRect(230, 20, 71, 16))
        self.PhoneNumber_2 = QLabel(self.tab_3)
        self.PhoneNumber_2.setObjectName(u"PhoneNumber_2")
        self.PhoneNumber_2.setGeometry(QRect(150, 90, 81, 16))
        self.LastNameInput_2 = QLineEdit(self.tab_3)
        self.LastNameInput_2.setObjectName(u"LastNameInput_2")
        self.LastNameInput_2.setGeometry(QRect(40, 50, 141, 31))
        self.NotesInput_2 = QPlainTextEdit(self.tab_3)
        self.NotesInput_2.setObjectName(u"NotesInput_2")
        self.NotesInput_2.setGeometry(QRect(40, 200, 301, 131))
        self.PhoneNumberInput_2 = QLineEdit(self.tab_3)
        self.PhoneNumberInput_2.setObjectName(u"PhoneNumberInput_2")
        self.PhoneNumberInput_2.setGeometry(QRect(90, 120, 201, 31))
        self.LastName_2 = QLabel(self.tab_3)
        self.LastName_2.setObjectName(u"LastName_2")
        self.LastName_2.setGeometry(QRect(40, 20, 61, 16))
        self.FirstNameInput_2 = QLineEdit(self.tab_3)
        self.FirstNameInput_2.setObjectName(u"FirstNameInput_2")
        self.FirstNameInput_2.setGeometry(QRect(222, 50, 121, 31))
        self.Notes_2 = QLabel(self.tab_3)
        self.Notes_2.setObjectName(u"Notes_2")
        self.Notes_2.setGeometry(QRect(180, 170, 49, 16))
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.lineEdit_16 = QLineEdit(self.tab_4)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(48, 785, 141, 31))
        self.lineEdit_17 = QLineEdit(self.tab_4)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(98, 855, 201, 31))
        self.label_15 = QLabel(self.tab_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(48, 755, 61, 16))
        self.label_16 = QLabel(self.tab_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(238, 755, 71, 16))
        self.lineEdit_18 = QLineEdit(self.tab_4)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(230, 785, 121, 31))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.puandpbutton_2 = QPushButton(self.page_2)
        self.puandpbutton_2.setObjectName(u"puandpbutton_2")
        self.puandpbutton_2.setGeometry(QRect(280, 770, 101, 41))
        self.qtbutton_2 = QPushButton(self.page_2)
        self.qtbutton_2.setObjectName(u"qtbutton_2")
        self.qtbutton_2.setGeometry(QRect(0, 770, 101, 41))
        self.paybutton_2 = QPushButton(self.page_2)
        self.paybutton_2.setObjectName(u"paybutton_2")
        self.paybutton_2.setGeometry(QRect(140, 770, 101, 41))
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(120, 0, 49, 16))
        self.pushButton_2 = QPushButton(self.page_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(140, 420, 101, 41))
        self.pushButton_3 = QPushButton(self.page_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(1270, 30, 151, 51))
        self.gridLayoutWidget = QWidget(self.page_2)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 470, 381, 291))
        self.tickettypebuttongrid = QGridLayout(self.gridLayoutWidget)
        self.tickettypebuttongrid.setObjectName(u"tickettypebuttongrid")
        self.tickettypebuttongrid.setContentsMargins(0, 0, 0, 0)
        self.pageswidget.addWidget(self.page_2)
        CustomerAccount2.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(CustomerAccount2)
        self.statusbar.setObjectName(u"statusbar")
        CustomerAccount2.setStatusBar(self.statusbar)

        self.retranslateUi(CustomerAccount2)

        self.pageswidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(CustomerAccount2)
    # setupUi

    def retranslateUi(self, CustomerAccount2):
        CustomerAccount2.setWindowTitle(QCoreApplication.translate("CustomerAccount2", u"MainWindow", None))
        self.puandpbutton.setText(QCoreApplication.translate("CustomerAccount2", u"Pick up + Pay", None))
        self.paybutton.setText(QCoreApplication.translate("CustomerAccount2", u"Pay", None))
        ___qtreewidgetitem = self.ctlist.headerItem()
        ___qtreewidgetitem.setText(5, QCoreApplication.translate("CustomerAccount2", u"Billing Invoice#", None));
        ___qtreewidgetitem.setText(4, QCoreApplication.translate("CustomerAccount2", u"Ticket#", None));
        ___qtreewidgetitem.setText(3, QCoreApplication.translate("CustomerAccount2", u"Ticket Type", None));
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("CustomerAccount2", u"Drop Off Date", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("CustomerAccount2", u"Picked up + Paid", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("CustomerAccount2", u"Paid", None));
        self.qtbutton.setText(QCoreApplication.translate("CustomerAccount2", u"Quick Ticket", None))
        self.FirstName.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.PhoneNumber.setText(QCoreApplication.translate("CustomerAccount2", u"Phone Number", None))
        self.LastName.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.Notes.setText(QCoreApplication.translate("CustomerAccount2", u"Notes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QCoreApplication.translate("CustomerAccount2", u"Tab 1", None))
        self.label_9.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.label_7.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("CustomerAccount2", u"Tab 2", None))
        self.label_17.setText(QCoreApplication.translate("CustomerAccount2", u"Page 1", None))
        self.pushButton.setText(QCoreApplication.translate("CustomerAccount2", u"Next Customer", None))
        self.pushButton_16.setText(QCoreApplication.translate("CustomerAccount2", u"Go To Customer Account 2", None))
        ___qtreewidgetitem1 = self.ctlist_2.headerItem()
        ___qtreewidgetitem1.setText(5, QCoreApplication.translate("CustomerAccount2", u"Billing Invoice#", None));
        ___qtreewidgetitem1.setText(4, QCoreApplication.translate("CustomerAccount2", u"Ticket#", None));
        ___qtreewidgetitem1.setText(3, QCoreApplication.translate("CustomerAccount2", u"Ticket Type", None));
        ___qtreewidgetitem1.setText(2, QCoreApplication.translate("CustomerAccount2", u"Drop Off Date", None));
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("CustomerAccount2", u"Picked up + Paid", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("CustomerAccount2", u"Paid", None));
        self.FirstName_2.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.PhoneNumber_2.setText(QCoreApplication.translate("CustomerAccount2", u"Phone Number", None))
        self.LastName_2.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.Notes_2.setText(QCoreApplication.translate("CustomerAccount2", u"Notes", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("CustomerAccount2", u"Tab 1", None))
        self.label_15.setText(QCoreApplication.translate("CustomerAccount2", u"Last Name", None))
        self.label_16.setText(QCoreApplication.translate("CustomerAccount2", u"First Name", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("CustomerAccount2", u"Tab 2", None))
        self.puandpbutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Pick up + Pay", None))
        self.qtbutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Quick Ticket", None))
        self.paybutton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Pay", None))
        self.label_18.setText(QCoreApplication.translate("CustomerAccount2", u"Page 2", None))
        self.pushButton_2.setText(QCoreApplication.translate("CustomerAccount2", u"Next Customer", None))
        self.pushButton_3.setText(QCoreApplication.translate("CustomerAccount2", u"Go To Customer Account 1", None))
    # retranslateUi






class Ui_GarmentandColorCreation(object):
    def setupUi(self, GarmentandColorCreation):
        if not GarmentandColorCreation.objectName():
            GarmentandColorCreation.setObjectName(u"GarmentandColorCreation")
        GarmentandColorCreation.resize(1007, 842)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        GarmentandColorCreation.setPalette(palette)
        GarmentandColorCreation.setStyleSheet(u"font: 9pt \"Segoe UI\";")
        self.centralwidget = QWidget(GarmentandColorCreation)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sgbutton = QPushButton(self.centralwidget)
        self.sgbutton.setObjectName(u"sgbutton")
        self.sgbutton.setGeometry(QRect(160, 370, 91, 24))
        self.sglist = QListWidget(self.centralwidget)
        self.sglist.setObjectName(u"sglist")
        self.sglist.setGeometry(QRect(460, 50, 501, 281))
        self.gninput = QLineEdit(self.centralwidget)
        self.gninput.setObjectName(u"gninput")
        self.gninput.setGeometry(QRect(140, 20, 113, 22))
        self.gnlabel = QLabel(self.centralwidget)
        self.gnlabel.setObjectName(u"gnlabel")
        self.gnlabel.setGeometry(QRect(30, 20, 91, 16))
        self.sglabel = QLabel(self.centralwidget)
        self.sglabel.setObjectName(u"sglabel")
        self.sglabel.setGeometry(QRect(680, 30, 91, 16))
        self.sglabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.avbutton = QPushButton(self.centralwidget)
        self.avbutton.setObjectName(u"avbutton")
        self.avbutton.setGeometry(QRect(270, 170, 121, 24))
        self.sibutton = QPushButton(self.centralwidget)
        self.sibutton.setObjectName(u"sibutton")
        self.sibutton.setGeometry(QRect(20, 90, 91, 24))
        self.avlist = QListWidget(self.centralwidget)
        self.avlist.setObjectName(u"avlist")
        self.avlist.setGeometry(QRect(80, 230, 251, 131))
        self.avlabel = QLabel(self.centralwidget)
        self.avlabel.setObjectName(u"avlabel")
        self.avlabel.setGeometry(QRect(160, 210, 81, 21))
        self.egbutton = QPushButton(self.centralwidget)
        self.egbutton.setObjectName(u"egbutton")
        self.egbutton.setGeometry(QRect(550, 340, 91, 24))
        self.dgbutton = QPushButton(self.centralwidget)
        self.dgbutton.setObjectName(u"dgbutton")
        self.dgbutton.setGeometry(QRect(790, 340, 91, 24))
        self.cninput = QLineEdit(self.centralwidget)
        self.cninput.setObjectName(u"cninput")
        self.cninput.setGeometry(QRect(150, 500, 113, 22))
        self.cnlabel = QLabel(self.centralwidget)
        self.cnlabel.setObjectName(u"cnlabel")
        self.cnlabel.setGeometry(QRect(70, 500, 71, 16))
        self.ccbutton = QPushButton(self.centralwidget)
        self.ccbutton.setObjectName(u"ccbutton")
        self.ccbutton.setGeometry(QRect(150, 580, 111, 24))
        self.sclist = QListWidget(self.centralwidget)
        self.sclist.setObjectName(u"sclist")
        self.sclist.setGeometry(QRect(580, 430, 256, 251))
        self.dcbutton = QPushButton(self.centralwidget)
        self.dcbutton.setObjectName(u"dcbutton")
        self.dcbutton.setGeometry(QRect(720, 690, 111, 24))
        self.scbutton = QPushButton(self.centralwidget)
        self.scbutton.setObjectName(u"scbutton")
        self.scbutton.setGeometry(QRect(150, 630, 111, 24))
        self.sclabel = QLabel(self.centralwidget)
        self.sclabel.setObjectName(u"sclabel")
        self.sclabel.setGeometry(QRect(680, 410, 91, 16))
        self.sclabel.setStyleSheet(u"font: 7pt \"Segoe UI\";")
        self.ecbutton = QPushButton(self.centralwidget)
        self.ecbutton.setObjectName(u"ecbutton")
        self.ecbutton.setGeometry(QRect(580, 690, 111, 24))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(140, 170, 111, 22))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 170, 51, 20))
        self.ImageLabel = QLabel(self.centralwidget)
        self.ImageLabel.setObjectName(u"ImageLabel")
        self.ImageLabel.setGeometry(QRect(120, 50, 151, 111))
        GarmentandColorCreation.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(GarmentandColorCreation)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1007, 33))
        GarmentandColorCreation.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(GarmentandColorCreation)
        self.statusbar.setObjectName(u"statusbar")
        GarmentandColorCreation.setStatusBar(self.statusbar)

        self.retranslateUi(GarmentandColorCreation)

        QMetaObject.connectSlotsByName(GarmentandColorCreation)
    # setupUi

    def retranslateUi(self, GarmentandColorCreation):
        GarmentandColorCreation.setWindowTitle(QCoreApplication.translate("GarmentandColorCreation", u"MainWindow", None))
        self.sgbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Save Garment", None))
        self.gnlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Garment Name:", None))
        self.sglabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Saved Garments", None))
        self.avbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Add Variation", None))
        self.sibutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Select Image", None))
        self.avlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"<html><head/><body><p><span style=\" font-size:7pt;\">Added Variations:</span></p></body></html>", None))
        self.egbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Edit Garment", None))
        self.dgbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Delete Garment", None))
        self.cnlabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Color Name:", None))
        self.ccbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Choose Color", None))
        self.dcbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Delete Color", None))
        self.scbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Save Color", None))
        self.sclabel.setText(QCoreApplication.translate("GarmentandColorCreation", u"Saved Colors", None))
        self.ecbutton.setText(QCoreApplication.translate("GarmentandColorCreation", u"Edit Color", None))
        self.label.setText(QCoreApplication.translate("GarmentandColorCreation", u"Variation:", None))
        self.ImageLabel.setText("")
    # retranslateUi





class Ui_TicketOptionsCreation(object):
    def setupUi(self, TicketOptionsCreation):
        if not TicketOptionsCreation.objectName():
            TicketOptionsCreation.setObjectName(u"TicketOptionsCreation")
        TicketOptionsCreation.resize(791, 692)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        TicketOptionsCreation.setPalette(palette)
        self.centralwidget = QWidget(TicketOptionsCreation)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tandpinput = QLineEdit(self.centralwidget)
        self.tandpinput.setObjectName(u"tandpinput")
        self.tandpinput.setGeometry(QRect(70, 70, 131, 22))
        self.tandpnamelabel = QLabel(self.centralwidget)
        self.tandpnamelabel.setObjectName(u"tandpnamelabel")
        self.tandpnamelabel.setGeometry(QRect(10, 70, 49, 16))
        self.savetbutton = QPushButton(self.centralwidget)
        self.savetbutton.setObjectName(u"savetbutton")
        self.savetbutton.setGeometry(QRect(0, 263, 91, 41))
        self.savepbutton = QPushButton(self.centralwidget)
        self.savepbutton.setObjectName(u"savepbutton")
        self.savepbutton.setGeometry(QRect(110, 263, 81, 41))
        self.tlist = QListWidget(self.centralwidget)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(220, 70, 211, 251))
        self.savedtlabel = QLabel(self.centralwidget)
        self.savedtlabel.setObjectName(u"savedtlabel")
        self.savedtlabel.setGeometry(QRect(330, 50, 81, 16))
        self.saveubutton = QPushButton(self.centralwidget)
        self.saveubutton.setObjectName(u"saveubutton")
        self.saveubutton.setGeometry(QRect(60, 553, 111, 41))
        self.uinput = QLineEdit(self.centralwidget)
        self.uinput.setObjectName(u"uinput")
        self.uinput.setGeometry(QRect(70, 430, 113, 22))
        self.unamelabel = QLabel(self.centralwidget)
        self.unamelabel.setObjectName(u"unamelabel")
        self.unamelabel.setGeometry(QRect(20, 430, 49, 16))
        self.unamelabel.setStyleSheet(u"\n"
"font: 9pt \"Segoe UI\";")
        self.uamountinput = QLineEdit(self.centralwidget)
        self.uamountinput.setObjectName(u"uamountinput")
        self.uamountinput.setGeometry(QRect(70, 500, 61, 22))
        self.uamountlabel = QLabel(self.centralwidget)
        self.uamountlabel.setObjectName(u"uamountlabel")
        self.uamountlabel.setGeometry(QRect(10, 500, 49, 16))
        self.ulist = QListWidget(self.centralwidget)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(220, 410, 201, 192))
        self.dnamelabel = QLabel(self.centralwidget)
        self.dnamelabel.setObjectName(u"dnamelabel")
        self.dnamelabel.setGeometry(QRect(430, 400, 49, 16))
        self.dinput = QLineEdit(self.centralwidget)
        self.dinput.setObjectName(u"dinput")
        self.dinput.setGeometry(QRect(430, 420, 113, 22))
        self.savedbutton = QPushButton(self.centralwidget)
        self.savedbutton.setObjectName(u"savedbutton")
        self.savedbutton.setGeometry(QRect(430, 553, 101, 41))
        self.dpercentinput = QLineEdit(self.centralwidget)
        self.dpercentinput.setObjectName(u"dpercentinput")
        self.dpercentinput.setGeometry(QRect(430, 470, 71, 22))
        self.dpercentlabel = QLabel(self.centralwidget)
        self.dpercentlabel.setObjectName(u"dpercentlabel")
        self.dpercentlabel.setGeometry(QRect(430, 450, 49, 16))
        self.damountlabel = QLabel(self.centralwidget)
        self.damountlabel.setObjectName(u"damountlabel")
        self.damountlabel.setGeometry(QRect(430, 500, 71, 16))
        self.damountinput = QLineEdit(self.centralwidget)
        self.damountinput.setObjectName(u"damountinput")
        self.damountinput.setGeometry(QRect(430, 520, 71, 22))
        self.dlist = QListWidget(self.centralwidget)
        self.dlist.setObjectName(u"dlist")
        self.dlist.setGeometry(QRect(550, 410, 211, 192))
        self.plist = QListWidget(self.centralwidget)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(540, 70, 221, 251))
        self.savedplabel = QLabel(self.centralwidget)
        self.savedplabel.setObjectName(u"savedplabel")
        self.savedplabel.setGeometry(QRect(610, 50, 81, 16))
        self.ImageLabel = QLabel(self.centralwidget)
        self.ImageLabel.setObjectName(u"ImageLabel")
        self.ImageLabel.setGeometry(QRect(90, 130, 141, 111))
        self.sibutton = QPushButton(self.centralwidget)
        self.sibutton.setObjectName(u"sibutton")
        self.sibutton.setGeometry(QRect(0, 153, 81, 41))
        self.deletebutton = QPushButton(self.centralwidget)
        self.deletebutton.setObjectName(u"deletebutton")
        self.deletebutton.setGeometry(QRect(430, 340, 101, 41))
        TicketOptionsCreation.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TicketOptionsCreation)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 791, 33))
        TicketOptionsCreation.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TicketOptionsCreation)
        self.statusbar.setObjectName(u"statusbar")
        TicketOptionsCreation.setStatusBar(self.statusbar)

        self.retranslateUi(TicketOptionsCreation)

        QMetaObject.connectSlotsByName(TicketOptionsCreation)
    # setupUi

    def retranslateUi(self, TicketOptionsCreation):
        TicketOptionsCreation.setWindowTitle(QCoreApplication.translate("TicketOptionsCreation", u"MainWindow", None))
        self.tandpinput.setText("")
        self.tandpnamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name:", None))
        self.savetbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Texture", None))
        self.savepbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Pattern", None))
        self.savedtlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Saved Textures ", None))
        self.saveubutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Upcharge", None))
        self.unamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name:", None))
        self.uamountlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Amount:", None))
        self.dnamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name:", None))
        self.savedbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Discount", None))
        self.dpercentlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"%  Off:", None))
        self.damountlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Amount Off:", None))
        self.savedplabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Saved Patterns", None))
        self.ImageLabel.setText("")
        self.sibutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Select Image", None))
        self.deletebutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Delete", None))
    # retranslateUi



class Ui_DetailedTicketCreation(object):
    def setupUi(self, DetailedTicketCreation):
        if not DetailedTicketCreation.objectName():
            DetailedTicketCreation.setObjectName(u"DetailedTicketCreation")
        DetailedTicketCreation.resize(1413, 852)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        DetailedTicketCreation.setPalette(palette)
        self.plist = QListWidget(DetailedTicketCreation)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(850, 460, 131, 191))
        self.clist = QListWidget(DetailedTicketCreation)
        self.clist.setObjectName(u"clist")
        self.clist.setGeometry(QRect(850, 670, 411, 151))
        self.ulist = QListWidget(DetailedTicketCreation)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(1130, 460, 131, 191))
        self.ulabel = QLabel(DetailedTicketCreation)
        self.ulabel.setObjectName(u"ulabel")
        self.ulabel.setGeometry(QRect(1140, 440, 61, 16))
        self.plabel = QLabel(DetailedTicketCreation)
        self.plabel.setObjectName(u"plabel")
        self.plabel.setGeometry(QRect(860, 440, 71, 16))
        self.clabel = QLabel(DetailedTicketCreation)
        self.clabel.setObjectName(u"clabel")
        self.clabel.setGeometry(QRect(860, 650, 49, 16))
        self.glist = QListWidget(DetailedTicketCreation)
        self.glist.setObjectName(u"glist")
        self.glist.setGeometry(QRect(850, 30, 411, 401))
        self.tlist = QListWidget(DetailedTicketCreation)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(990, 460, 131, 161))
        self.tlabel = QLabel(DetailedTicketCreation)
        self.tlabel.setObjectName(u"tlabel")
        self.tlabel.setGeometry(QRect(1000, 440, 61, 16))
        self.glabel = QLabel(DetailedTicketCreation)
        self.glabel.setObjectName(u"glabel")
        self.glabel.setGeometry(QRect(860, 10, 61, 16))
        self.piecesinput = QSpinBox(DetailedTicketCreation)
        self.piecesinput.setObjectName(u"piecesinput")
        self.piecesinput.setGeometry(QRect(1030, 630, 91, 31))
        self.pieceslabel = QLabel(DetailedTicketCreation)
        self.pieceslabel.setObjectName(u"pieceslabel")
        self.pieceslabel.setGeometry(QRect(990, 630, 41, 16))
        self.editgarmentbutton = QPushButton(DetailedTicketCreation)
        self.editgarmentbutton.setObjectName(u"editgarmentbutton")
        self.editgarmentbutton.setGeometry(QRect(1280, 540, 111, 41))
        self.deletegarmentbutton = QPushButton(DetailedTicketCreation)
        self.deletegarmentbutton.setObjectName(u"deletegarmentbutton")
        self.deletegarmentbutton.setGeometry(QRect(1280, 680, 111, 41))
        self.canceltbutton = QPushButton(DetailedTicketCreation)
        self.canceltbutton.setObjectName(u"canceltbutton")
        self.canceltbutton.setGeometry(QRect(30, 777, 111, 41))
        self.ptbutton = QPushButton(DetailedTicketCreation)
        self.ptbutton.setObjectName(u"ptbutton")
        self.ptbutton.setGeometry(QRect(30, 640, 111, 41))
        self.ptandtbutton = QPushButton(DetailedTicketCreation)
        self.ptandtbutton.setObjectName(u"ptandtbutton")
        self.ptandtbutton.setGeometry(QRect(30, 587, 111, 41))
        self.tctabs = QTabWidget(DetailedTicketCreation)
        self.tctabs.setObjectName(u"tctabs")
        self.tctabs.setGeometry(QRect(160, 10, 681, 811))
        self.tctabs1 = QWidget()
        self.tctabs1.setObjectName(u"tctabs1")
        self.sglist = QTreeWidget(self.tctabs1)
        self.sglist.headerItem().setText(0, "")
        self.sglist.setObjectName(u"sglist")
        self.sglist.setGeometry(QRect(0, 30, 691, 761))
        self.sglist.header().setDefaultSectionSize(139)
        self.ttname = QTextBrowser(self.tctabs1)
        self.ttname.setObjectName(u"ttname")
        self.ttname.setGeometry(QRect(0, 0, 691, 31))
        self.tctabs.addTab(self.tctabs1, "")
        self.tctabs2 = QWidget()
        self.tctabs2.setObjectName(u"tctabs2")
        self.ttname_2 = QTextBrowser(self.tctabs2)
        self.ttname_2.setObjectName(u"ttname_2")
        self.ttname_2.setGeometry(QRect(0, 0, 691, 31))
        self.sglist_2 = QTreeWidget(self.tctabs2)
        self.sglist_2.headerItem().setText(0, "")
        self.sglist_2.setObjectName(u"sglist_2")
        self.sglist_2.setGeometry(QRect(0, 30, 691, 751))
        self.sglist_2.header().setDefaultSectionSize(139)
        self.tctabs.addTab(self.tctabs2, "")
        self.tctabs3 = QWidget()
        self.tctabs3.setObjectName(u"tctabs3")
        self.sglist_3 = QTreeWidget(self.tctabs3)
        self.sglist_3.headerItem().setText(0, "")
        self.sglist_3.setObjectName(u"sglist_3")
        self.sglist_3.setGeometry(QRect(0, 30, 701, 751))
        self.sglist_3.header().setDefaultSectionSize(139)
        self.ttname_3 = QTextBrowser(self.tctabs3)
        self.ttname_3.setObjectName(u"ttname_3")
        self.ttname_3.setGeometry(QRect(0, 0, 691, 31))
        self.tctabs.addTab(self.tctabs3, "")
        self.ctbutton = QPushButton(DetailedTicketCreation)
        self.ctbutton.setObjectName(u"ctbutton")
        self.ctbutton.setGeometry(QRect(30, 720, 111, 41))
        self.addgarmentbutton = QPushButton(DetailedTicketCreation)
        self.addgarmentbutton.setObjectName(u"addgarmentbutton")
        self.addgarmentbutton.setGeometry(QRect(1280, 260, 111, 41))
        self.addtogarmentbutton = QPushButton(DetailedTicketCreation)
        self.addtogarmentbutton.setObjectName(u"addtogarmentbutton")
        self.addtogarmentbutton.setGeometry(QRect(1280, 400, 111, 41))
        self.tickettypebuttonwidget = QWidget(DetailedTicketCreation)
        self.tickettypebuttonwidget.setObjectName(u"tickettypebuttonwidget")
        self.tickettypebuttonwidget.setGeometry(QRect(9, 40, 141, 521))

        self.retranslateUi(DetailedTicketCreation)

        self.tctabs.setCurrentIndex(0)

    # setupUi

    def retranslateUi(self, DetailedTicketCreation):
        DetailedTicketCreation.setWindowTitle(QCoreApplication.translate("DetailedTicketCreation", u"Form", None))
        self.ulabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Upcharges", None))
        self.plabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Patterns", None))
        self.clabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Colors", None))
        self.tlabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Textures", None))
        self.glabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"Garments", None))
        self.pieceslabel.setText(QCoreApplication.translate("DetailedTicketCreation", u"#Pieces", None))
        self.editgarmentbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Edit Garment", None))
        self.deletegarmentbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Delete Garment", None))
        self.canceltbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Cancel Ticket", None))
        self.ptbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Print Ticket", None))
        self.ptandtbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Print Ticket + Tags", None))
        self.ttname.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs1), QCoreApplication.translate("DetailedTicketCreation", u"ticket1", None))
        self.ttname_2.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs2), QCoreApplication.translate("DetailedTicketCreation", u"ticket2", None))
        self.ttname_3.setHtml(QCoreApplication.translate("DetailedTicketCreation", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tctabs.setTabText(self.tctabs.indexOf(self.tctabs3), QCoreApplication.translate("DetailedTicketCreation", u"ticket3", None))
        self.ctbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Create Ticket", None))
        self.addgarmentbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Add Garment", None))
        self.addtogarmentbutton.setText(QCoreApplication.translate("DetailedTicketCreation", u"Add to Garment", None))
    # retranslateUi








class Ui_QuickTicketCreation(object):
    def setupUi(self, QuickTicketCreation):
        if not QuickTicketCreation.objectName():
            QuickTicketCreation.setObjectName(u"QuickTicketCreation")
        QuickTicketCreation.resize(559, 408)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        QuickTicketCreation.setPalette(palette)
        self.ttlabel = QLabel(QuickTicketCreation)
        self.ttlabel.setObjectName(u"ttlabel")
        self.ttlabel.setGeometry(QRect(20, 20, 71, 16))
        self.qtdlabel = QLabel(QuickTicketCreation)
        self.qtdlabel.setObjectName(u"qtdlabel")
        self.qtdlabel.setGeometry(QRect(240, 20, 71, 16))
        self.qtdselection = QDateEdit(QuickTicketCreation)
        self.qtdselection.setObjectName(u"qtdselection")
        self.qtdselection.setGeometry(QRect(240, 40, 121, 22))
        self.qtdselection_2 = QDateEdit(QuickTicketCreation)
        self.qtdselection_2.setObjectName(u"qtdselection_2")
        self.qtdselection_2.setGeometry(QRect(240, 130, 121, 22))
        self.qtdselection_3 = QDateEdit(QuickTicketCreation)
        self.qtdselection_3.setObjectName(u"qtdselection_3")
        self.qtdselection_3.setGeometry(QRect(240, 220, 121, 22))
        self.ttselection = QComboBox(QuickTicketCreation)
        self.ttselection.setObjectName(u"ttselection")
        self.ttselection.setGeometry(QRect(20, 40, 111, 22))
        self.ttselection_2 = QComboBox(QuickTicketCreation)
        self.ttselection_2.setObjectName(u"ttselection_2")
        self.ttselection_2.setGeometry(QRect(20, 130, 111, 22))
        self.ttselection_3 = QComboBox(QuickTicketCreation)
        self.ttselection_3.setObjectName(u"ttselection_3")
        self.ttselection_3.setGeometry(QRect(20, 220, 111, 22))
        self.qtninput = QPlainTextEdit(QuickTicketCreation)
        self.qtninput.setObjectName(u"qtninput")
        self.qtninput.setGeometry(QRect(380, 40, 161, 61))
        self.qtninput_2 = QPlainTextEdit(QuickTicketCreation)
        self.qtninput_2.setObjectName(u"qtninput_2")
        self.qtninput_2.setGeometry(QRect(380, 130, 161, 61))
        self.qtninput_3 = QPlainTextEdit(QuickTicketCreation)
        self.qtninput_3.setObjectName(u"qtninput_3")
        self.qtninput_3.setGeometry(QRect(380, 220, 161, 61))
        self.qtnlabel = QLabel(QuickTicketCreation)
        self.qtnlabel.setObjectName(u"qtnlabel")
        self.qtnlabel.setGeometry(QRect(380, 20, 49, 16))
        self.ttlabel_2 = QLabel(QuickTicketCreation)
        self.ttlabel_2.setObjectName(u"ttlabel_2")
        self.ttlabel_2.setGeometry(QRect(20, 110, 71, 16))
        self.ttlabel_3 = QLabel(QuickTicketCreation)
        self.ttlabel_3.setObjectName(u"ttlabel_3")
        self.ttlabel_3.setGeometry(QRect(20, 200, 71, 16))
        self.qtdlabel_2 = QLabel(QuickTicketCreation)
        self.qtdlabel_2.setObjectName(u"qtdlabel_2")
        self.qtdlabel_2.setGeometry(QRect(240, 110, 71, 16))
        self.qtdlabel_3 = QLabel(QuickTicketCreation)
        self.qtdlabel_3.setObjectName(u"qtdlabel_3")
        self.qtdlabel_3.setGeometry(QRect(240, 200, 71, 16))
        self.qtnlabel_2 = QLabel(QuickTicketCreation)
        self.qtnlabel_2.setObjectName(u"qtnlabel_2")
        self.qtnlabel_2.setGeometry(QRect(380, 110, 49, 16))
        self.qtnlabel_3 = QLabel(QuickTicketCreation)
        self.qtnlabel_3.setObjectName(u"qtnlabel_3")
        self.qtnlabel_3.setGeometry(QRect(380, 200, 49, 16))
        self.qtclosebutton = QPushButton(QuickTicketCreation)
        self.qtclosebutton.setObjectName(u"qtclosebutton")
        self.qtclosebutton.setGeometry(QRect(320, 310, 101, 24))
        self.qtsandpbutton = QPushButton(QuickTicketCreation)
        self.qtsandpbutton.setObjectName(u"qtsandpbutton")
        self.qtsandpbutton.setGeometry(QRect(440, 310, 101, 24))
        self.atninput = QPlainTextEdit(QuickTicketCreation)
        self.atninput.setObjectName(u"atninput")
        self.atninput.setGeometry(QRect(20, 290, 291, 71))
        self.atnlabel = QLabel(QuickTicketCreation)
        self.atnlabel.setObjectName(u"atnlabel")
        self.atnlabel.setGeometry(QRect(20, 270, 111, 16))
        self.qtpselection_2 = QSpinBox(QuickTicketCreation)
        self.qtpselection_2.setObjectName(u"qtpselection_2")
        self.qtpselection_2.setGeometry(QRect(160, 130, 88, 22))
        self.qtpselection_3 = QSpinBox(QuickTicketCreation)
        self.qtpselection_3.setObjectName(u"qtpselection_3")
        self.qtpselection_3.setGeometry(QRect(160, 220, 88, 22))
        self.qtpselection = QSpinBox(QuickTicketCreation)
        self.qtpselection.setObjectName(u"qtpselection")
        self.qtpselection.setGeometry(QRect(160, 40, 88, 22))
        self.qtplabel_3 = QLabel(QuickTicketCreation)
        self.qtplabel_3.setObjectName(u"qtplabel_3")
        self.qtplabel_3.setGeometry(QRect(160, 200, 49, 16))
        self.qtplabel_2 = QLabel(QuickTicketCreation)
        self.qtplabel_2.setObjectName(u"qtplabel_2")
        self.qtplabel_2.setGeometry(QRect(160, 110, 49, 16))
        self.qtplabel = QLabel(QuickTicketCreation)
        self.qtplabel.setObjectName(u"qtplabel")
        self.qtplabel.setGeometry(QRect(160, 20, 49, 16))

        self.retranslateUi(QuickTicketCreation)

        QMetaObject.connectSlotsByName(QuickTicketCreation)
    # setupUi

    def retranslateUi(self, QuickTicketCreation):
        QuickTicketCreation.setWindowTitle(QCoreApplication.translate("QuickTicketCreation", u"Form", None))
        self.ttlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.qtdlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Date", None))
        self.qtnlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.ttlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.ttlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Ticket Type", None))
        self.qtdlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Date", None))
        self.qtdlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Date", None))
        self.qtnlabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.qtnlabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes", None))
        self.qtclosebutton.setText(QCoreApplication.translate("QuickTicketCreation", u"Close", None))
        self.qtsandpbutton.setText(QCoreApplication.translate("QuickTicketCreation", u"Create + Print", None))
        self.atnlabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Notes For All Tickets", None))
        self.qtplabel_3.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
        self.qtplabel_2.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
        self.qtplabel.setText(QCoreApplication.translate("QuickTicketCreation", u"Pieces", None))
    # retranslateUi


class Ui_TicketTypeCreation(object):
    def setupUi(self, TicketTypeCreation):
        if not TicketTypeCreation.objectName():
            TicketTypeCreation.setObjectName(u"TicketTypeCreation")
        TicketTypeCreation.resize(1182, 823)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        TicketTypeCreation.setPalette(palette)
        self.dlist = QListWidget(TicketTypeCreation)
        self.dlist.setObjectName(u"dlist")
        self.dlist.setGeometry(QRect(280, 90, 131, 192))
        self.ulist = QListWidget(TicketTypeCreation)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(280, 310, 131, 192))
        self.tlist = QListWidget(TicketTypeCreation)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(280, 530, 131, 192))
        self.plist = QListWidget(TicketTypeCreation)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(140, 530, 131, 192))
        self.clist = QListWidget(TicketTypeCreation)
        self.clist.setObjectName(u"clist")
        self.clist.setGeometry(QRect(0, 530, 131, 192))
        self.glist = QListWidget(TicketTypeCreation)
        self.glist.setObjectName(u"glist")
        self.glist.setGeometry(QRect(0, 91, 271, 411))
        self.glabel = QLabel(TicketTypeCreation)
        self.glabel.setObjectName(u"glabel")
        self.glabel.setGeometry(QRect(10, 70, 61, 16))
        self.plabel = QLabel(TicketTypeCreation)
        self.plabel.setObjectName(u"plabel")
        self.plabel.setGeometry(QRect(140, 510, 71, 16))
        self.tlabel = QLabel(TicketTypeCreation)
        self.tlabel.setObjectName(u"tlabel")
        self.tlabel.setGeometry(QRect(280, 510, 61, 16))
        self.ulabel = QLabel(TicketTypeCreation)
        self.ulabel.setObjectName(u"ulabel")
        self.ulabel.setGeometry(QRect(280, 290, 61, 16))
        self.clabel = QLabel(TicketTypeCreation)
        self.clabel.setObjectName(u"clabel")
        self.clabel.setGeometry(QRect(0, 510, 49, 16))
        self.ttinput = QLineEdit(TicketTypeCreation)
        self.ttinput.setObjectName(u"ttinput")
        self.ttinput.setGeometry(QRect(490, 30, 113, 22))
        self.ttlabel = QLabel(TicketTypeCreation)
        self.ttlabel.setObjectName(u"ttlabel")
        self.ttlabel.setGeometry(QRect(490, 10, 101, 16))
        self.dlabel = QLabel(TicketTypeCreation)
        self.dlabel.setObjectName(u"dlabel")
        self.dlabel.setGeometry(QRect(280, 70, 61, 16))
        self.cglist = QListWidget(TicketTypeCreation)
        self.cglist.setObjectName(u"cglist")
        self.cglist.setGeometry(QRect(440, 90, 271, 371))
        self.cclist = QListWidget(TicketTypeCreation)
        self.cclist.setObjectName(u"cclist")
        self.cclist.setGeometry(QRect(440, 490, 271, 141))
        self.cclabel = QLabel(TicketTypeCreation)
        self.cclabel.setObjectName(u"cclabel")
        self.cclabel.setGeometry(QRect(440, 470, 81, 16))
        self.cglabel = QLabel(TicketTypeCreation)
        self.cglabel.setObjectName(u"cglabel")
        self.cglabel.setGeometry(QRect(440, 70, 111, 16))
        self.savettbutton = QPushButton(TicketTypeCreation)
        self.savettbutton.setObjectName(u"savettbutton")
        self.savettbutton.setGeometry(QRect(1050, 740, 131, 24))
        self.editttbutton = QPushButton(TicketTypeCreation)
        self.editttbutton.setObjectName(u"editttbutton")
        self.editttbutton.setGeometry(QRect(900, 740, 111, 21))
        self.deletettbutton = QPushButton(TicketTypeCreation)
        self.deletettbutton.setObjectName(u"deletettbutton")
        self.deletettbutton.setGeometry(QRect(750, 740, 111, 24))
        self.sttlist = QListWidget(TicketTypeCreation)
        self.sttlist.setObjectName(u"sttlist")
        self.sttlist.setGeometry(QRect(440, 660, 271, 161))
        self.sttlabel = QLabel(TicketTypeCreation)
        self.sttlabel.setObjectName(u"sttlabel")
        self.sttlabel.setGeometry(QRect(440, 640, 101, 16))
        self.cpatterns = QListWidget(TicketTypeCreation)
        self.cpatterns.setObjectName(u"cpatterns")
        self.cpatterns.setGeometry(QRect(720, 90, 221, 301))
        self.ctextures = QListWidget(TicketTypeCreation)
        self.ctextures.setObjectName(u"ctextures")
        self.ctextures.setGeometry(QRect(950, 90, 221, 301))
        self.cupcharges = QListWidget(TicketTypeCreation)
        self.cupcharges.setObjectName(u"cupcharges")
        self.cupcharges.setGeometry(QRect(720, 420, 221, 301))
        self.cdiscounts = QListWidget(TicketTypeCreation)
        self.cdiscounts.setObjectName(u"cdiscounts")
        self.cdiscounts.setGeometry(QRect(950, 420, 221, 301))
        self.label = QLabel(TicketTypeCreation)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(720, 400, 101, 16))
        self.label_2 = QLabel(TicketTypeCreation)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(950, 400, 101, 16))
        self.label_3 = QLabel(TicketTypeCreation)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(720, 70, 91, 16))
        self.label_4 = QLabel(TicketTypeCreation)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(950, 70, 91, 16))

        self.retranslateUi(TicketTypeCreation)

        QMetaObject.connectSlotsByName(TicketTypeCreation)
    # setupUi

    def retranslateUi(self, TicketTypeCreation):
        TicketTypeCreation.setWindowTitle(QCoreApplication.translate("TicketTypeCreation", u"Form", None))
        self.glabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Garments", None))
        self.plabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Patterns", None))
        self.tlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Textures", None))
        self.ulabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Upcharges", None))
        self.clabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Colors", None))
        self.ttlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Ticket Type Name:", None))
        self.dlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Discounts", None))
        self.cclabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Colors", None))
        self.cglabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Garments", None))
        self.savettbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Save Ticket Type", None))
        self.editttbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Edit Ticket Type", None))
        self.deletettbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Delete Ticket Type", None))
        self.sttlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Saved Ticket Types", None))
        self.label.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Upcharges", None))
        self.label_2.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Discounts", None))
        self.label_3.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Patterns", None))
        self.label_4.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Textures", None))
    # retranslateUi

    
    
    

class Ui_garmentpricing(object):
    def setupUi(self, garmentpricing):
        if not garmentpricing.objectName():
            garmentpricing.setObjectName(u"garmentpricing")
        garmentpricing.setEnabled(True)
        garmentpricing.resize(708, 602)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        garmentpricing.setPalette(palette)
        font = QFont()
        font.setBold(True)
        garmentpricing.setFont(font)
        garmentpricing.setMouseTracking(False)
        garmentpricing.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        garmentpricing.setAcceptDrops(False)
        self.centralwidget = QWidget(garmentpricing)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.garmentvariationlist = QTreeWidget(self.centralwidget)
        self.garmentvariationlist.setObjectName(u"garmentvariationlist")
        self.garmentvariationlist.setGeometry(QRect(20, 100, 351, 461))
        self.garmentvariationlist.setMouseTracking(False)
        self.garmentvariationlist.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.garmentvariationlist.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.setprice = QPushButton(self.centralwidget)
        self.setprice.setObjectName(u"setprice")
        self.setprice.setGeometry(QRect(480, 370, 121, 41))
        self.price = QLineEdit(self.centralwidget)
        self.price.setObjectName(u"price")
        self.price.setGeometry(QRect(480, 290, 121, 31))
        self.price.setMouseTracking(True)
        self.price.setContextMenuPolicy(Qt.ContextMenuPolicy.PreventContextMenu)
        self.price.setAcceptDrops(False)
        self.price.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.price.setAutoFillBackground(False)
        self.price.setMaxLength(32766)
        self.price.setDragEnabled(True)
        self.price.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 0, 401, 81))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.label.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(36)
        font1.setWeight(QFont.Black)
        font1.setItalic(False)
        self.label.setFont(font1)
        self.label.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label.setMouseTracking(False)
        self.label.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.label.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"")
        self.label.setLocale(QLocale(QLocale.Embu, QLocale.Kenya))
        self.label.setLineWidth(1)
        self.label.setTextFormat(Qt.TextFormat.PlainText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setIndent(3)
        garmentpricing.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(garmentpricing)
        self.statusbar.setObjectName(u"statusbar")
        garmentpricing.setStatusBar(self.statusbar)

        self.retranslateUi(garmentpricing)

        QMetaObject.connectSlotsByName(garmentpricing)
    # setupUi

    def retranslateUi(self, garmentpricing):
        garmentpricing.setWindowTitle(QCoreApplication.translate("garmentpricing", u"MainWindow", None))
        ___qtreewidgetitem = self.garmentvariationlist.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("garmentpricing", u"Garments and Variations Pricing", None));
        self.setprice.setText(QCoreApplication.translate("garmentpricing", u"Set Price", None))
        self.price.setText("")
        self.price.setPlaceholderText(QCoreApplication.translate("garmentpricing", u"Input Price", None))
        self.label.setText(QCoreApplication.translate("garmentpricing", u"Garment Pricing", None))
    # retranslateUi





