from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, Qt)
from PySide6.QtGui import (QBrush, QColor, QFont, QPalette, QPixmap)
from PySide6.QtWidgets import (QLabel, QLineEdit, QPushButton,
    QFrame, 
    QListWidget)


class Ui_TicketTypeCreation(object):
    def setupUi(self, TicketTypeCreation):
        if not TicketTypeCreation.objectName():
            TicketTypeCreation.setObjectName(u"TicketTypeCreation")
        TicketTypeCreation.resize(1920, 1080)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        TicketTypeCreation.setPalette(palette)
        self.dlist = QListWidget(TicketTypeCreation)
        self.dlist.setObjectName(u"dlist")
        self.dlist.setGeometry(QRect(150, 720, 261, 291))
        self.ulist = QListWidget(TicketTypeCreation)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(650, 650, 201, 361))
        self.tlist = QListWidget(TicketTypeCreation)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(430, 650, 201, 361))
        self.plist = QListWidget(TicketTypeCreation)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(650, 170, 201, 431))
        self.clist = QListWidget(TicketTypeCreation)
        self.clist.setObjectName(u"clist")
        self.clist.setGeometry(QRect(430, 170, 201, 431))
        self.glist = QListWidget(TicketTypeCreation)
        self.glist.setObjectName(u"glist")
        self.glist.setGeometry(QRect(150, 170, 261, 511))
        self.glabel = QLabel(TicketTypeCreation)
        self.glabel.setObjectName(u"glabel")
        self.glabel.setGeometry(QRect(150, 140, 91, 31))
        font = QFont()
        font.setPointSize(14)
        self.glabel.setFont(font)
        self.plabel = QLabel(TicketTypeCreation)
        self.plabel.setObjectName(u"plabel")
        self.plabel.setGeometry(QRect(650, 140, 71, 31))
        self.plabel.setFont(font)
        self.tlabel = QLabel(TicketTypeCreation)
        self.tlabel.setObjectName(u"tlabel")
        self.tlabel.setGeometry(QRect(430, 620, 121, 31))
        self.tlabel.setFont(font)
        self.ulabel = QLabel(TicketTypeCreation)
        self.ulabel.setObjectName(u"ulabel")
        self.ulabel.setGeometry(QRect(650, 620, 151, 31))
        self.ulabel.setFont(font)
        self.clabel = QLabel(TicketTypeCreation)
        self.clabel.setObjectName(u"clabel")
        self.clabel.setGeometry(QRect(430, 140, 61, 31))
        self.clabel.setFont(font)
        self.ttinput = QLineEdit(TicketTypeCreation)
        self.ttinput.setObjectName(u"ttinput")
        self.ttinput.setGeometry(QRect(870, 170, 241, 61))
        self.ttlabel = QLabel(TicketTypeCreation)
        self.ttlabel.setObjectName(u"ttlabel")
        self.ttlabel.setGeometry(QRect(870, 140, 151, 31))
        self.ttlabel.setFont(font)
        self.dlabel = QLabel(TicketTypeCreation)
        self.dlabel.setObjectName(u"dlabel")
        self.dlabel.setGeometry(QRect(150, 690, 91, 31))
        self.dlabel.setFont(font)
        self.cglist = QListWidget(TicketTypeCreation)
        self.cglist.setObjectName(u"cglist")
        self.cglist.setGeometry(QRect(870, 270, 241, 741))
        self.cclist = QListWidget(TicketTypeCreation)
        self.cclist.setObjectName(u"cclist")
        self.cclist.setGeometry(QRect(1130, 170, 201, 431))
        self.cclabel = QLabel(TicketTypeCreation)
        self.cclabel.setObjectName(u"cclabel")
        self.cclabel.setGeometry(QRect(1130, 140, 141, 31))
        self.cclabel.setFont(font)
        self.cglabel = QLabel(TicketTypeCreation)
        self.cglabel.setObjectName(u"cglabel")
        self.cglabel.setGeometry(QRect(870, 240, 181, 31))
        self.cglabel.setFont(font)
        self.savettbutton = QPushButton(TicketTypeCreation)
        self.savettbutton.setObjectName(u"savettbutton")
        self.savettbutton.setGeometry(QRect(1620, 1020, 151, 51))
        self.editttbutton = QPushButton(TicketTypeCreation)
        self.editttbutton.setObjectName(u"editttbutton")
        self.editttbutton.setGeometry(QRect(1460, 1020, 151, 51))
        self.deletettbutton = QPushButton(TicketTypeCreation)
        self.deletettbutton.setObjectName(u"deletettbutton")
        self.deletettbutton.setGeometry(QRect(1300, 1020, 151, 51))
        self.sttlist = QListWidget(TicketTypeCreation)
        self.sttlist.setObjectName(u"sttlist")
        self.sttlist.setGeometry(QRect(1130, 650, 201, 361))
        self.sttlabel = QLabel(TicketTypeCreation)
        self.sttlabel.setObjectName(u"sttlabel")
        self.sttlabel.setGeometry(QRect(1130, 620, 181, 31))
        self.sttlabel.setFont(font)
        self.cpatterns = QListWidget(TicketTypeCreation)
        self.cpatterns.setObjectName(u"cpatterns")
        self.cpatterns.setGeometry(QRect(1350, 170, 201, 431))
        self.ctextures = QListWidget(TicketTypeCreation)
        self.ctextures.setObjectName(u"ctextures")
        self.ctextures.setGeometry(QRect(1570, 170, 201, 431))
        self.cupcharges = QListWidget(TicketTypeCreation)
        self.cupcharges.setObjectName(u"cupcharges")
        self.cupcharges.setGeometry(QRect(1350, 650, 201, 361))
        self.cdiscounts = QListWidget(TicketTypeCreation)
        self.cdiscounts.setObjectName(u"cdiscounts")
        self.cdiscounts.setGeometry(QRect(1570, 650, 201, 361))
        self.label = QLabel(TicketTypeCreation)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1350, 620, 181, 31))
        self.label.setFont(font)
        self.label_2 = QLabel(TicketTypeCreation)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1570, 620, 171, 31))
        self.label_2.setFont(font)
        self.label_3 = QLabel(TicketTypeCreation)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(1350, 140, 161, 31))
        self.label_3.setFont(font)
        self.label_4 = QLabel(TicketTypeCreation)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(1570, 140, 171, 31))
        self.label_4.setFont(font)
        self.label_5 = QLabel(TicketTypeCreation)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(472, 20, 981, 102))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
        self.label_5.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Ravie"])
        font1.setPointSize(48)
        self.label_5.setFont(font1)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setFrameShape(QFrame.Shape.Box)
        self.label_5.setFrameShadow(QFrame.Shadow.Plain)
        self.label_5.setLineWidth(6)
        self.label_5.setMidLineWidth(5)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_6 = QLabel(TicketTypeCreation)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(152, 0, 296, 143))
        self.label_6.setPixmap(QPixmap(u":images/Logo2.jpg"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(TicketTypeCreation)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(1477, 0, 292, 143))
        self.label_7.setPixmap(QPixmap(u":images/Logo2.jpg"))
        self.label_7.setScaledContents(True)
        self.label_5.raise_()
        self.dlist.raise_()
        self.ulist.raise_()
        self.tlist.raise_()
        self.plist.raise_()
        self.clist.raise_()
        self.glist.raise_()
        self.glabel.raise_()
        self.plabel.raise_()
        self.tlabel.raise_()
        self.ulabel.raise_()
        self.clabel.raise_()
        self.ttinput.raise_()
        self.ttlabel.raise_()
        self.dlabel.raise_()
        self.cglist.raise_()
        self.cclist.raise_()
        self.cclabel.raise_()
        self.cglabel.raise_()
        self.savettbutton.raise_()
        self.editttbutton.raise_()
        self.deletettbutton.raise_()
        self.sttlist.raise_()
        self.sttlabel.raise_()
        self.cpatterns.raise_()
        self.ctextures.raise_()
        self.cupcharges.raise_()
        self.cdiscounts.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_7.raise_()

        self.retranslateUi(TicketTypeCreation)

        QMetaObject.connectSlotsByName(TicketTypeCreation)
    # setupUi

    def retranslateUi(self, TicketTypeCreation):
        TicketTypeCreation.setWindowTitle(QCoreApplication.translate("TicketTypeCreation", u"Form", None))
        self.glabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Garments", None))
        self.plabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Patterns", None))
        self.tlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Textures", None))
        self.ulabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Upcharges", None))
        self.clabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Colors", None))
        self.ttlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Ticket Type Name:", None))
        self.dlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Discounts", None))
        self.cclabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Colors", None))
        self.cglabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Garments", None))
        self.savettbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Save Ticket Type", None))
        self.editttbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Edit Ticket Type", None))
        self.deletettbutton.setText(QCoreApplication.translate("TicketTypeCreation", u"Delete Ticket Type", None))
        self.sttlabel.setText(QCoreApplication.translate("TicketTypeCreation", u"Saved Ticket Types", None))
        self.label.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Upcharges", None))
        self.label_2.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Discounts", None))
        self.label_3.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Patterns", None))
        self.label_4.setText(QCoreApplication.translate("TicketTypeCreation", u"Chosen Textures", None))
        self.label_5.setText(QCoreApplication.translate("TicketTypeCreation", u"<html><head/><body><p><span style=\" color:#5500ff;\">Ticket Type Creation</span></p></body></html>", None))
        self.label_6.setText("")
        self.label_7.setText("")
    # retranslateUi



