from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, Qt)
from PySide6.QtGui import (QBrush, QColor, QPalette)
from PySide6.QtWidgets import (QLabel, QLineEdit, QMenuBar, QPushButton,
    QStatusBar, QWidget, QListWidget)


class Ui_TicketOptionsCreation(object):
    def setupUi(self, TicketOptionsCreation):
        if not TicketOptionsCreation.objectName():
            TicketOptionsCreation.setObjectName(u"TicketOptionsCreation")
        TicketOptionsCreation.resize(791, 692)
        palette = QPalette()
        brush = QBrush(QColor(255, 227, 203, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(26, 110, 175, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(136, 136, 136, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(120, 131, 170, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush6 = QBrush(QColor(85, 0, 255, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        brush7 = QBrush(QColor(255, 85, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        TicketOptionsCreation.setPalette(palette)
        self.centralwidget = QWidget(TicketOptionsCreation)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tandpinput = QLineEdit(self.centralwidget)
        self.tandpinput.setObjectName(u"tandpinput")
        self.tandpinput.setGeometry(QRect(70, 70, 131, 22))
        self.tandpnamelabel = QLabel(self.centralwidget)
        self.tandpnamelabel.setObjectName(u"tandpnamelabel")
        self.tandpnamelabel.setGeometry(QRect(10, 70, 49, 16))
        self.savetbutton = QPushButton(self.centralwidget)
        self.savetbutton.setObjectName(u"savetbutton")
        self.savetbutton.setGeometry(QRect(0, 263, 91, 41))
        self.savepbutton = QPushButton(self.centralwidget)
        self.savepbutton.setObjectName(u"savepbutton")
        self.savepbutton.setGeometry(QRect(110, 263, 81, 41))
        self.tlist = QListWidget(self.centralwidget)
        self.tlist.setObjectName(u"tlist")
        self.tlist.setGeometry(QRect(220, 70, 211, 251))
        self.savedtlabel = QLabel(self.centralwidget)
        self.savedtlabel.setObjectName(u"savedtlabel")
        self.savedtlabel.setGeometry(QRect(330, 50, 81, 16))
        self.saveubutton = QPushButton(self.centralwidget)
        self.saveubutton.setObjectName(u"saveubutton")
        self.saveubutton.setGeometry(QRect(60, 553, 111, 41))
        self.uinput = QLineEdit(self.centralwidget)
        self.uinput.setObjectName(u"uinput")
        self.uinput.setGeometry(QRect(70, 430, 113, 22))
        self.unamelabel = QLabel(self.centralwidget)
        self.unamelabel.setObjectName(u"unamelabel")
        self.unamelabel.setGeometry(QRect(20, 430, 49, 16))
        self.unamelabel.setStyleSheet(u"\n"
"font: 9pt \"Segoe UI\";")
        self.uamountinput = QLineEdit(self.centralwidget)
        self.uamountinput.setObjectName(u"uamountinput")
        self.uamountinput.setGeometry(QRect(70, 500, 61, 22))
        self.uamountlabel = QLabel(self.centralwidget)
        self.uamountlabel.setObjectName(u"uamountlabel")
        self.uamountlabel.setGeometry(QRect(10, 500, 49, 16))
        self.ulist = QListWidget(self.centralwidget)
        self.ulist.setObjectName(u"ulist")
        self.ulist.setGeometry(QRect(220, 410, 201, 192))
        self.dnamelabel = QLabel(self.centralwidget)
        self.dnamelabel.setObjectName(u"dnamelabel")
        self.dnamelabel.setGeometry(QRect(430, 400, 49, 16))
        self.dinput = QLineEdit(self.centralwidget)
        self.dinput.setObjectName(u"dinput")
        self.dinput.setGeometry(QRect(430, 420, 113, 22))
        self.savedbutton = QPushButton(self.centralwidget)
        self.savedbutton.setObjectName(u"savedbutton")
        self.savedbutton.setGeometry(QRect(430, 553, 101, 41))
        self.dpercentinput = QLineEdit(self.centralwidget)
        self.dpercentinput.setObjectName(u"dpercentinput")
        self.dpercentinput.setGeometry(QRect(430, 470, 71, 22))
        self.dpercentlabel = QLabel(self.centralwidget)
        self.dpercentlabel.setObjectName(u"dpercentlabel")
        self.dpercentlabel.setGeometry(QRect(430, 450, 49, 16))
        self.damountlabel = QLabel(self.centralwidget)
        self.damountlabel.setObjectName(u"damountlabel")
        self.damountlabel.setGeometry(QRect(430, 500, 71, 16))
        self.damountinput = QLineEdit(self.centralwidget)
        self.damountinput.setObjectName(u"damountinput")
        self.damountinput.setGeometry(QRect(430, 520, 71, 22))
        self.dlist = QListWidget(self.centralwidget)
        self.dlist.setObjectName(u"dlist")
        self.dlist.setGeometry(QRect(550, 410, 211, 192))
        self.plist = QListWidget(self.centralwidget)
        self.plist.setObjectName(u"plist")
        self.plist.setGeometry(QRect(540, 70, 221, 251))
        self.savedplabel = QLabel(self.centralwidget)
        self.savedplabel.setObjectName(u"savedplabel")
        self.savedplabel.setGeometry(QRect(610, 50, 81, 16))
        self.ImageLabel = QLabel(self.centralwidget)
        self.ImageLabel.setObjectName(u"ImageLabel")
        self.ImageLabel.setGeometry(QRect(90, 130, 141, 111))
        self.sibutton = QPushButton(self.centralwidget)
        self.sibutton.setObjectName(u"sibutton")
        self.sibutton.setGeometry(QRect(0, 153, 81, 41))
        self.deletebutton = QPushButton(self.centralwidget)
        self.deletebutton.setObjectName(u"deletebutton")
        self.deletebutton.setGeometry(QRect(430, 340, 101, 41))
        TicketOptionsCreation.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TicketOptionsCreation)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 791, 33))
        TicketOptionsCreation.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TicketOptionsCreation)
        self.statusbar.setObjectName(u"statusbar")
        TicketOptionsCreation.setStatusBar(self.statusbar)

        self.retranslateUi(TicketOptionsCreation)

        QMetaObject.connectSlotsByName(TicketOptionsCreation)
    # setupUi

    def retranslateUi(self, TicketOptionsCreation):
        TicketOptionsCreation.setWindowTitle(QCoreApplication.translate("TicketOptionsCreation", u"MainWindow", None))
        self.tandpinput.setText("")
        self.tandpnamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name:", None))
        self.savetbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Texture", None))
        self.savepbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Pattern", None))
        self.savedtlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Saved Textures ", None))
        self.saveubutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Upcharge", None))
        self.unamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name:", None))
        self.uamountlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Amount:", None))
        self.dnamelabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Name:", None))
        self.savedbutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Save Discount", None))
        self.dpercentlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"%  Off:", None))
        self.damountlabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Amount Off:", None))
        self.savedplabel.setText(QCoreApplication.translate("TicketOptionsCreation", u"Saved Patterns", None))
        self.ImageLabel.setText("")
        self.sibutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Select Image", None))
        self.deletebutton.setText(QCoreApplication.translate("TicketOptionsCreation", u"Delete", None))
    # retranslateUi
